(function(){
const $=id=>document.getElementById(id);const esc=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;');
const LVN={k5:'Kids (K to 5th)',g8:'8th grade',hs:'High school',col:'College',max:'Max'};const BAND={k5:0,g8:1,hs:2,col:3,max:3};
let level='g8';try{level=localStorage.getItem('one-rule-level')||'g8'}catch(e){}
const bsel=$('cb-board'),csel=$('cb-chapter'),out=$('cards');
CARDS.boards.forEach((b,i)=>{const o=document.createElement('option');o.value=b.id;o.textContent=b.title;bsel.appendChild(o)});
function fillChapters(){csel.innerHTML='';const b=CARDS.boards.find(x=>x.id===bsel.value);b.chapters.forEach(c=>{const o=document.createElement('option');o.value=c.n;o.textContent=`${c.n} · ${c.title[level]||c.title.k5}`;csel.appendChild(o)})}
function link(b,c){try{const u=new URL(b.url);u.searchParams.set('level',level);return u.toString()+'#ch'+c.n}catch(e){return b.url+'#ch'+c.n}}
function card(b,c){const t=c.title[level]||c.title.k5;const ms=c.missions.filter(m=>m.lv.includes(level));const ck=c.check&&c.check[level];const disc=Array.isArray(c.discuss)?c.discuss:(c.discuss[BAND[level]]||[]);
  let key='';if(ck){if(ck.type==='num')key=`<p class="q">${esc(ck.q)}</p><p class="key"><b>Answer key:</b> ${ck.a} ${esc(ck.u)} (${esc(ck.uname)}), accept about ±${Math.round(ck.tol*100)}%. <i>${esc(ck.ok)}</i></p><p class="key"><b>Hint if stuck:</b> ${esc(ck.hint)}</p>`;else key=`<p class="q">${esc(ck.q)}</p><ol class="opts">${ck.opts.map((o,i)=>`<li${i===ck.idx?' class="right"':''}>${esc(o)}${i===ck.idx?' <b>← correct</b>':''}</li>`).join('')}</ol><p class="key"><b>Hint if stuck:</b> ${esc(ck.hint)}</p>`}
  return `<article class="lcard"><header><p class="eyebrow">${esc(b.title)} · Chapter ${c.n} · ${LVN[level]}</p><h2>${esc(t)}</h2><p class="meta">About 25 minutes · one device per pair · projector optional${c.std?' · <b>Standards</b> '+esc(c.std):''}</p></header>
<section><h3>Warm-up <small>2 min</small></h3><p>${esc(c.warm)}</p></section>
<section><h3>Experiment <small>10 min</small></h3><p>${esc(c.figcap)}</p><p class="sl"><b>Student link:</b> <a href="${link(b,c)}">${link(b,c)}</a></p></section>
<section><h3>Missions <small>the page checks these off</small></h3><ul class="ms">${ms.map(m=>`<li><span class="box"></span>${esc(m.text)} <span class="pill ${m.skill?'try':'must'}">${m.skill?'try your best':'must do'}</span></li>`).join('')}</ul></section>
<section><h3>Teach it back <small>3 min</small></h3>${key||'<p>—</p>'}</section>
<section><h3>Discuss <small>5 min</small></h3><ol>${disc.map(q=>`<li>${esc(q)}</li>`).join('')}</ol></section>
<section><h3>Exit ticket <small>3 min</small></h3><p>${esc(c.exit)}</p><p class="skill"><b>By the end, students can:</b> ${esc(c.skill)}.</p><p class="skill"><b>Receipts:</b> students press “Hand it in” at the end of the chapter; the code on each receipt can be checked below.</p></section></article>`}
function render(all){const b=CARDS.boards.find(x=>x.id===bsel.value);if(all)out.innerHTML=b.chapters.map(c=>card(b,c)).join('');else{const c=b.chapters.find(x=>String(x.n)===csel.value)||b.chapters[0];out.innerHTML=card(b,c)}}
function setLevel(l){level=l;try{localStorage.setItem('one-rule-level',l)}catch(e){}document.querySelectorAll('[data-glevel]').forEach(x=>x.classList.toggle('is-on',x.dataset.glevel===l));const keep=csel.value;fillChapters();if(keep)csel.value=keep;render(false)}
document.querySelectorAll('[data-glevel]').forEach(x=>x.addEventListener('click',()=>setLevel(x.dataset.glevel)));
bsel.addEventListener('change',()=>{fillChapters();render(false)});csel.addEventListener('change',()=>render(false));
$('cb-print').addEventListener('click',()=>{render(false);setTimeout(()=>window.print(),50)});$('cb-printall').addEventListener('click',()=>{render(true);setTimeout(()=>window.print(),50)});
const q=new URLSearchParams(location.search);if(q.get('board'))bsel.value=q.get('board');fillChapters();if(q.get('ch'))csel.value=q.get('ch');setLevel(q.get('level')||level);
// standards search
const sbox=$('sbox'),sout=$('sout');if(sbox){sbox.addEventListener('input',()=>{const q=sbox.value.trim().toUpperCase();if(!q){sout.innerHTML='';return}const hits=[];CARDS.boards.forEach(b=>b.chapters.forEach(c=>{if((c.std||'').toUpperCase().includes(q))hits.push({b,c})}));sout.innerHTML=hits.length?hits.map(({b,c})=>`<li><a href="${link(b,c)}">${esc(b.title)} ${c.n} · ${esc(c.title[level]||c.title.k5)}</a><small>${esc(c.std)}</small></li>`).join(''):'<li><small>no chapter lists that code yet</small></li>'})}
// class roster from many receipts
function parseReceipt(block){const lines=block.split('\n').map(l=>l.trim()).filter(Boolean);const i=lines.findIndex(l=>/^Code:/i.test(l));if(i<0||lines[0]!=='THE CHALKBOARD RECEIPT')return null;const given=lines[i].replace(/^Code:\s*/i,'').trim().toUpperCase();const ok=fnv(lines.slice(0,i).join('\n'))===given;const f=k=>{const l=lines.find(x=>x.toLowerCase().startsWith(k.toLowerCase()+':'));return l?l.slice(k.length+1).trim():''};const m=f('Missions').match(/^(\d+)\/(\d+)/);return{ok,name:f('Name'),board:f('Board'),chapter:f('Chapter').split('·')[0].trim(),level:f('Level'),date:f('Date'),done:m?+m[1]:0,total:m?+m[2]:0,tb:f('Teach it back'),exit:f('Exit ticket')}}
$('ro-go').addEventListener('click',()=>{const raw=$('ro').value.replace(/\r/g,'');const blocks=raw.split(/(?=THE CHALKBOARD RECEIPT)/).map(b=>b.trim()).filter(Boolean);const rows=blocks.map(parseReceipt).filter(Boolean);const out=$('ro-out');if(!rows.length){out.innerHTML='<p class="fb bad">No receipts found. Paste them one after another; each starts with THE CHALKBOARD RECEIPT.</p>';return}
  const names=[...new Set(rows.map(r=>r.name))].sort();const cols=[...new Set(rows.map(r=>r.board+' '+r.chapter))].sort();
  const cell=(n,c)=>{const r=rows.filter(x=>x.name===n&&x.board+' '+x.chapter===c).sort((a,b)=>a.date<b.date?1:-1)[0];if(!r)return'<td class="empty">—</td>';return`<td class="${r.ok?(r.tb==='passed'?'good':'part'):'bad'}" title="${esc(r.exit)}">${r.done}/${r.total}${r.tb==='passed'?' ✓':''}${r.ok?'':' ✗ code'}</td>`};
  out.innerHTML=`<p class="fb ok">${rows.length} receipt${rows.length>1?'s':''} · ${names.length} student${names.length>1?'s':''} · ${rows.filter(r=>!r.ok).length} with a bad code</p><div class="rowrap"><table class="roster"><thead><tr><th>Student</th>${cols.map(c=>`<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${names.map(n=>`<tr><th>${esc(n)}</th>${cols.map(c=>cell(n,c)).join('')}</tr>`).join('')}</tbody></table></div><p class="small">Cells show missions done and a ✓ when the teach-back passed. Hover a cell for the exit ticket. Latest receipt per student and chapter wins.</p><button class="btn" id="ro-csv">Copy as spreadsheet</button>`;
  $('ro-csv').addEventListener('click',async()=>{const head=['student','board','chapter','level','date','missions done','missions total','teach it back','exit ticket','code ok'];const tsv=[head.join('\t'),...rows.map(r=>[r.name,r.board,r.chapter,r.level,r.date,r.done,r.total,r.tb,r.exit.replace(/\t/g,' '),r.ok?'yes':'NO'].join('\t'))].join('\n');try{await navigator.clipboard.writeText(tsv);$('ro-csv').textContent='Copied: paste into Sheets or Excel'}catch(e){$('ro-csv').textContent='Copy blocked: select the table instead'}})});
// receipt checker
function fnv(str){let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(36).toUpperCase().padStart(7,'0').slice(-6)}
$('vr-go').addEventListener('click',()=>{const raw=$('vr').value.replace(/\r/g,'').trim();const lines=raw.split('\n').map(l=>l.trim()).filter(l=>l.length);const i=lines.findIndex(l=>/^Code:/i.test(l));const o=$('vr-out');if(i<0||lines[0]!=='THE CHALKBOARD RECEIPT'){o.textContent='That does not look like a receipt: it should start with THE CHALKBOARD RECEIPT and end with a Code line.';o.className='fb bad';return}
  const given=lines[i].replace(/^Code:\s*/i,'').trim().toUpperCase();const body=lines.slice(0,i).join('\n');const ok=fnv(body)===given;const f=k=>{const l=lines.find(x=>x.toLowerCase().startsWith(k.toLowerCase()+':'));return l?l.slice(k.length+1).trim():'?'};
  o.innerHTML=ok?`<b>Valid receipt.</b> ${esc(f('Name'))} · ${esc(f('Board'))}, chapter ${esc(f('Chapter'))} · ${esc(f('Level'))} · ${esc(f('Date'))}<br>Missions ${esc(f('Missions'))} · Teach it back: ${esc(f('Teach it back'))}<br>Exit ticket: “${esc(f('Exit ticket'))}”`:'<b>Code does not match.</b> The text was edited after the receipt was made, or a line was dropped when pasting. Ask for it again.';o.className='fb '+(ok?'ok':'bad')});
})();
