# Physical twins of the digital experiments. Each pairs with a board chapter.
KITS=[
 ('launch',[
  dict(ch=1,title='Coin push',mins=10,materials='A coin, a smooth table, a rough placemat or towel.',steps=['Flick the coin across the bare table and measure how far it slides.','Do the same push across the towel.','Try a heavier coin with the same flick.'],notice='The push ends at your finger; friction does the stopping. Rougher surface, shorter slide. The heavier coin needs a harder flick to reach the same speed but stops in about the same distance.'),
  dict(ch=2,title='Paper and book drop',mins=5,materials='A hardback book, a sheet of paper.',steps=['Drop the book and the paper side by side. The paper floats.','Put the paper on top of the book and drop them together. They land together.','Crumple the paper into a tight ball and drop it beside the book.'],notice='The book shields the paper from the air, so gravity alone acts on both and they fall the same. Crumpling shrinks the paper\'s area so the air matters less.'),
  dict(ch=3,title='Ruler ramp and marble',mins=15,materials='A ruler with a groove or a length of track, books to prop it, a marble, masking tape, a cup as the target.',steps=['Prop the ruler on one book. Release the marble from the top and mark where it lands with tape.','Add a second book. Mark the new landing spot.','Put the cup where you predict the marble will land from three books. Test it.'],notice='Higher start, faster marble, longer flight, but not double: the speed goes with the square root of the height. A heavier marble lands in the same place.'),
  dict(ch=4,title='Coin crash',mins=5,materials='Two identical coins, one larger coin.',steps=['Slide one coin into a resting identical coin. The mover stops; the other takes off.','Slide the small coin into the large one. It bounces back.','Slide the large coin into the small one. Both keep going.'],notice='Equal masses swap motion. A light thing bouncing off a heavy one, and a heavy thing barely noticing a light one, are momentum conservation with no equations.'),
  dict(ch=6,title='Balloon rocket',mins=10,materials='A balloon, a drinking straw, string, tape.',steps=['Thread the string through the straw and tie it across the room, slightly uphill.','Blow up the balloon, hold it closed, tape it to the straw.','Let go.'],notice='The balloon pushes air backward; the air pushes the balloon forward. It is not pushing on the room air: it would work in a vacuum. Ask what runs out first, air or string.'),
 ]),
 ('heat',[
  dict(ch=1,title='Spoon in hot water',mins=5,materials='A metal spoon, a wooden spoon, a plastic spoon, a mug of hot tap water.',steps=['Stand all three spoons in the mug.','After a minute, touch each handle.'],notice='Metal carries heat fast, wood and plastic barely at all. That is the bar between the two blocks. Which spoon would you make a heat sink from?'),
  dict(ch=2,title='Time the kettle',mins=10,materials='A kettle or pot, a measuring jug, a stopwatch, the kettle\'s wattage from its label.',steps=['Boil exactly one litre from cold and time it.','Repeat with half a litre.','Compare with 4,186 J per kg per degree divided by the label wattage.'],notice='Half the water takes roughly half the time. The measured time is a little longer than the arithmetic because the kettle warms up and loses heat as it goes.'),
  dict(ch=4,title='Hand-warmed module',mins=10,materials='A thermoelectric module (a few dollars online), an LED or a small motor, a bowl of ice water.',steps=['Press the module between your palm and a cold metal surface or a bowl of ice water.','Connect the LED. Watch for a glow. Swap the wires if not.','Try a cup of hot water on the top instead of your hand.'],notice='Your hand is the hot side at 33 °C. The bigger the difference, the brighter the glow. A module on a candle can light an LED easily; the same module on a warm hand needs a very cold other side.'),
  dict(ch=5,title='Where the heat goes',mins=5,materials='A running laptop or phone, your hand.',steps=['Feel the back of a laptop that has been working hard.','Ask: the laptop used 30 W of electricity; where is it now?'],notice='All of it became heat. Turning electricity into heat is easy and complete; turning heat back into electricity is hard and partial. That asymmetry is the second law.'),
 ]),
 ('electricity',[
  dict(ch=1,title='Read the labels',mins=10,materials='A phone charger, a light bulb box, a power bank, the electricity bill.',steps=['Find the watts on the charger and the bulb.','Find the watt-hours (or mAh and volts) on the power bank.','Find the kWh on the bill.'],notice='Every number is either a rate (W) or an amount (Wh). Sort them into two columns. Then work out how many hours the power bank could run the bulb.'),
  dict(ch=2,title='Battery, bulb, wire',mins=10,materials='A AA battery, a flashlight bulb, a wire, a pencil lead.',steps=['Light the bulb with one wire, the battery and the bulb touching.','Put the pencil lead in the circuit and slide the wire along it.'],notice='The lead is a resistor. More lead in the path, dimmer bulb: more opposition, less flow. This is the ohm slider in your hand.'),
  dict(ch=5,title='Stack the batteries',mins=5,materials='Two AA batteries, a 3 V LED, tape.',steps=['Try to light the LED with one battery. Nothing, or very dim.','Tape two batteries end to end and try again.','Put the batteries side by side (same ends together) and try again.'],notice='End to end the pushes add and the LED lights. Side by side the push is the same as one battery, so it stays dim, but they would last twice as long.'),
  dict(ch=9,title='The full hose',mins=5,materials='A garden hose already full of water, or a straw full of water with a finger over the end.',steps=['Push water in one end.','Watch water come out the other end immediately.'],notice='The water that came out was not the water you pushed. Electrons in a wire work the same way: the wire is full, and the push travels far faster than the stuff.'),
 ]),
 ('einstein',[
  dict(ch=2,title='Bedsheet gravity',mins=15,materials='A bedsheet or stretchy fabric, four people to hold it, a heavy ball, marbles.',steps=['Hold the sheet taut and flat. Roll a marble across: straight line.','Put the heavy ball in the middle. Roll a marble past it.','Roll a marble sideways fast enough to circle the ball.'],notice='The marble is not pulled by the ball; it follows the dent. Faster sideways roll makes a longer orbit. Everything the simulation does, the sheet does, except time.'),
  dict(ch=3,title='Iron filings and a magnet',mins=10,materials='A bar magnet, iron filings or steel wool cut fine, a sheet of paper.',steps=['Put the paper over the magnet and sprinkle the filings.','Tap the paper.','Move a compass around the edge.'],notice='The filings draw the field lines the simulation computes. The compass points along them. Nothing about the paper bent; the pattern sits on top of it.'),
  dict(ch=9,title='Two rulebooks on one desk',mins=10,materials='A magnet, a paper clip, a small ball.',steps=['Drop the ball: gravity. Lift the clip with the magnet: magnetism.','Try to pick the ball up with the magnet. Try to drop the clip past the magnet.'],notice='Two pulls on one desk that ignore each other completely. That is what Einstein could not stand.'),
 ]),
 ('infinity',[
  dict(ch=1,title='Cups and spoons',mins=5,materials='A pile of cups, a pile of spoons.',steps=['Without counting, put one spoon in each cup.','Whatever is left over tells you which pile was bigger.'],notice='Matching decides same-size without numbers. This is the whole tool Cantor used for infinite piles.'),
  dict(ch=2,title='The hallway hotel',mins=10,materials='A hallway of chairs, a class of students.',steps=['Every chair has a student. A new student arrives.','Everyone moves one chair down. Where does the last student go?','Now say the hallway never ends.'],notice='With a real hallway someone falls off the end. With an endless one, nobody does, and there is always a free chair. Infinite means the trick never fails.'),
  dict(ch=4,title='Beat the list',mins=10,materials='Paper, a partner.',steps=['Your partner writes five rows of five random 0s and 1s and claims it is every possible row.','You write a new row by flipping the first digit of row one, second of row two, and so on.','Show it is not on their list. Let them add it. Do it again.'],notice='The list can never catch up. That is the diagonal argument played as a game.'),
 ]),
 ('history',[
  dict(ch=1,title='Scribe chain',mins=15,materials='A paragraph on paper, six students, pens.',steps=['Student one copies the paragraph by hand and passes only their copy on.','Each student copies the copy they received.','Compare the last copy with the original.'],notice='Errors accumulate and are inherited. Find one mistake that every later copy shares: it tells you where in the chain it was born.'),
  dict(ch=2,title='Find the family',mins=15,materials='Five copies of a sentence prepared by the teacher with planted shared errors.',steps=['Give each group all five copies.','Ask them to draw the family tree from shared mistakes and reconstruct the original.'],notice='Groups discover on their own that three copies can be wrong together if they descend from one bad parent. Count branches, not copies.'),
  dict(ch=4,title='Halving pennies',mins=10,materials='64 pennies, a table.',steps=['Each round, remove half the pennies. Count rounds until one is left.','Ask how many rounds ago there were 64.'],notice='Six halvings from 64 to 1. Carbon-14 does this every 5,730 years, and the pennies left tell you the rounds elapsed. That is the whole dating method.'),
  dict(ch=5,title='Three copies vote',mins=10,materials='Three copies of a short text, one with a planted error in each copy at different places.',steps=['Compare the three line by line.','Wherever they disagree, take the majority.'],notice='You recovered the original with no copy being perfect. This is exactly what the copies-and-voting switch does to the picture.'),
 ]),
 ('life',[
  dict(ch=1,title='Whisper the recipe',mins=10,materials='A 20-letter code of A, T, C and G on a card; paper for everyone.',steps=['The first student reads the card and copies it by hand, then hides the card.','Each student copies the previous student\'s copy, never the original. Go eight copies deep.','Lay all the copies in a line next to the original and circle every changed letter.'],notice='Mistakes appear, and once a mistake is made every later copy inherits it. Nobody copies from the original, which is exactly how cells copy DNA. Count how many mistakes are shared by all the later copies.'),
  dict(ch=2,title='Toothpick moths',mins=15,materials='Coloured toothpicks or short bits of yarn (green, brown, red, yellow), 20 of each; a patch of grass or a green carpet; a timer.',steps=['Scatter all 80 toothpicks over the grass while the birds look away.','Birds get 30 seconds to collect as many as they can, one at a time.','Count the survivors by colour. Give each survivor two babies of its colour and play again.'],notice='Green survives on green because the birds cannot see it, not because it is better in any other way. After three rounds the population is mostly green. Move to a brown floor and the same rule turns the population brown.'),
  dict(ch=3,title='Coin peas',mins=10,materials='Two coins per pair of students, paper for a tally.',steps=['Each coin is a parent: heads is T, tails is t. Flip both; that is one baby. Write TT, Tt or tt.','Make 40 babies. Tally tall (any T) and short (tt).','Pool the whole class and compare the tall : short ratio with 3 : 1.'],notice='Pairs get wobbly ratios; the class total lands close to 3 : 1. Small samples wobble and big ones settle, which is why Mendel counted thousands.'),
  dict(ch=5,title='Beads in a bag',mins=10,materials='A bag, 5 red beads and 5 blue beads, paper.',steps=['The bag is the island. To make the next generation, draw one bead, note its colour, put it back, and repeat ten times.','Empty the bag and refill it with the colours you noted: that is the new population.','Repeat until only one colour is left. Count the generations.'],notice='Nobody chose a colour, and one still took over. Do it with 20 beads and it takes longer. Do it after a storm (draw only five) and the mix can jump in a single generation.'),
  dict(ch=6,title='Sort the cousins',mins=15,materials='Cards with six animals (say cat, lion, dog, cow, whale, shark) and a list of eight features per animal (hair, milk, four legs, retractable claws, hooves, gills, flippers, live birth).',steps=['For every pair, count the features they share. Write the counts in a grid.','Join the pair with the highest count. Treat the pair as one and keep joining.','Draw the tree. Discuss why the whale ends up next to the cow and not the shark.'],notice='Shared features from a common ancestor group animals together. A feature that evolved twice, like flippers in whales and fins in sharks, can mislead, which is why more features (and DNA letters) give a better tree.'),
 ]),
 ('scale',[
  dict(ch=1,title='The solar system on the playground',mins=20,materials='A basketball, a peppercorn, a pea, a marble, a tape measure or a known pace length, chalk.',steps=['The basketball is the Sun. Put it at one end of the field.','Earth is the peppercorn, 26 m away. Jupiter is the marble at 135 m. Neptune would be 780 m away: point at where it would be.','Ask where the next star would be at this scale (about 7,000 km: roughly the next continent).'],notice='At the scale where the Sun is a basketball, the planets are specks separated by empty field, and the nearest star is on another continent. The eyepiece shows the same emptiness at every step outward.'),
  dict(ch=2,title='Measure a hair with a phone',mins=10,materials='A hair, clear tape, a ruler with millimetre marks, a phone camera with zoom.',steps=['Tape the hair across the ruler so it crosses the millimetre marks.','Zoom the camera in as far as it goes and take a picture.','Estimate how many hairs would fit in one millimetre. Divide 1 mm by that number.'],notice='A hair is about a tenth of a millimetre, which is where your eyes give out and the eyepiece has only just begun. Ten more turns of the focus and you would be at an atom.'),
 ]),
]
