KEY='scale'
TITLE='The Eyepiece'
FAVICON='🔭'
DESC="One eyepiece that is a telescope and a microscope at once: turn the focus from the edge of the observable universe all the way in to the Planck length, 62 powers of ten, with every object drawn at its true relative size and every reading in metres and powers of ten."
EYEBROW="Scale: telescope and microscope in one"
TRAIL=[('top','Start'),('ch1','1 · All the way out'),('ch2','2 · All the way in')]
HERO={
 'k5':"Look through the eyepiece. Turn the focus one way and you fly out past the Moon, the Sun, the stars, the galaxies, to the edge of everything we can see. Turn it the other way and you dive into your hand, into a cell, into an atom, and past the smallest thing anyone has ever measured. Every object is drawn at its real size compared to the others.",
 'g8':"One instrument, two directions. Every click of the focus is one power of ten. Going out, it takes 27 of them to reach the edge of the observable universe. Going in, it takes 35 to reach the Planck length, and for the last fifteen there is nothing to draw, because nobody has ever seen anything there. Learn to read a size as a power of ten and the whole universe fits on one ruler.",
 'hs':"Sixty-two orders of magnitude from 10⁻³⁵ m to 10²⁷ m, on a logarithmic focus. The instrument shows why the human scale sits near the middle, why light cannot resolve anything much below its own wavelength, why the atom is empty, and where measured physics stops. Each object carries its size in scientific notation; read them off and the exponents tell the story.",
 'col':"A log-scale viewer across the full range of measured length, with the honest gaps: the desert between the electroweak scale and the Planck length, and the horizon beyond which the universe is unobservable. Use it to place cross-sections, wavelengths and resolution limits (Abbe, Rutherford, the LHC's reach) on one axis, and to see why the interesting physics clusters at particular exponents.",
 'max':"Lengths are the one quantity we can lay out end to end across all of physics, and the layout is not uniform: structure at 10⁻¹⁵, 10⁻¹⁰, 10⁰, 10⁷, 10⁹, 10²¹ and 10²⁶ m, with near-emptiness between. The eyepiece is a map of where the fundamental constants, ħ, c, G, e and the masses, set the scales, and of the two edges, Planck and horizon, where the map stops being a map.",
}
STANDARDS={1:"5-ESS1-1, MS-ESS1-2, MS-ESS1-3, HS-ESS1-2 · Crosscutting: scale, proportion and quantity",2:"5-PS1-1, MS-PS1-1, HS-PS1-1, HS-PS4-3 · Crosscutting: scale, proportion and quantity"}
CH={}
CH[1]={
 'k5':("All the way out",None,["Start with you. Turn the focus and you get smaller and smaller as the world gets bigger: a whale, a mountain, the whole Earth, then the Sun, which is a hundred Earths wide. Keep going. The Sun becomes a dot among stars, the stars become a galaxy, the galaxies become specks. Then it stops. Not because space ends, but because light from farther away has not reached us yet.","Every turn of the focus makes the view ten times wider. Count the turns."]),
 'g8':("Powers of ten, outward",None,["Each notch on the focus multiplies the field of view by ten. You are about 10⁰ m tall. The Earth is 10⁷ m across, the Sun 10⁹, the solar system 10¹³, the gap to the nearest star 10¹⁶, the Milky Way 10²¹, and the observable universe about 10²⁷. Twenty-seven notches, and most of them are empty: the universe is almost entirely nothing with a little something scattered through it.","The edge is not a wall. The universe is 13.8 billion years old, so we can only see things whose light has had that long to arrive. Every year the edge moves out by one light-year, and every observer, anywhere, is at the centre of their own."]),
 'hs':("Reading the exponents",None,["Write a size as a × 10ⁿ and n does the work: the Earth (1.3 × 10⁷ m) and the Sun (1.4 × 10⁹ m) differ by two exponents, so a hundred Earths fit across the Sun. The Sun and the Milky Way differ by twelve, which is why a galaxy of 10¹¹ stars is still mostly empty: the stars are 10⁷ solar diameters apart.","Light-years are a convenience: 1 ly = 9.46 × 10¹⁵ m, which is just the speed of light times the seconds in a year. The observable universe, at 8.8 × 10²⁶ m across, is 93 billion light-years, larger than 2 × 13.8 billion because space has expanded while the light travelled."]),
 'col':("Hierarchy and emptiness",None,["Structure is hierarchical and sparse: planets in systems (10¹³ m), systems in galaxies (10²¹ m), galaxies in groups (10²³ m), groups in superclusters and filaments (10²⁴ to 10²⁵ m), and above about 10²⁵ m the cosmic web becomes statistically uniform, which is the scale on which the cosmological principle holds and Friedmann's equations apply. Below it, gravity has had time to make lumps; above it, it has not.","The particle horizon, 46.5 billion light-years in comoving radius, is the current limit of observation, not of existence. The cosmic microwave background is the farthest light we can see, emitted when the universe was 380,000 years old; anything earlier is opaque to photons and reachable only through neutrinos or gravitational waves."]),
 'max':("The horizon as an edge of knowledge",None,["Observability has its own hierarchy: the particle horizon (what could have reached us), the event horizon of an accelerating universe (what ever will), and the Hubble radius (where recession reaches c), none of which coincide. In a ΛCDM universe the event horizon is about 16 billion light-years away, so galaxies beyond it, already visible, will fade from view; the observable universe grows in comoving terms but the reachable universe shrinks.","Whether space is finite is undetermined: the curvature is consistent with zero to a fraction of a percent, which bounds the radius of any closed universe to far beyond the horizon. The eyepiece stops at 10²⁷ m because that is where measurement stops, which is a different statement from where space does."]),
}
CH[2]={
 'k5':("All the way in",None,["Turn the focus the other way. Your hand fills the view, then one hair, then things too small to see: a cell, a germ, a virus. Then the pieces cells are built from, then atoms, which are almost all empty space with a tiny heavy dot in the middle. Then inside that dot.","Then something strange: fifteen turns of the focus where nothing at all is drawn. Nobody has ever seen anything there. At the very end is the smallest length that means anything: the Planck length."]),
 'g8':("Powers of ten, inward",None,["A hair is 10⁻⁴ m wide, a red blood cell 10⁻⁵, a bacterium 10⁻⁶, a virus 10⁻⁷, a molecule 10⁻⁹, an atom 10⁻¹⁰, a nucleus 10⁻¹⁴, a proton 10⁻¹⁵. Somewhere past 10⁻⁶ m you leave what a light microscope can show, because light itself is 5 × 10⁻⁷ m from wave to wave and cannot pick out anything much smaller than its own ripples. After that we look with electrons, X-rays, and finally with collisions.","The atom is a shock at this scale. If the nucleus were a pea in the middle of a football field, the electrons would be somewhere out in the stands, and everything between is empty. You are mostly nothing, held apart by electric forces."]),
 'hs':("Resolution and the atom",None,["A microscope cannot resolve detail finer than about half the wavelength it uses (the Abbe limit, d ≈ λ ÷ 2NA), so visible light stops near 200 nm. Electron microscopes use electrons with de Broglie wavelengths of picometres and reach atoms; X-ray crystallography reads bond lengths; and to see inside a proton you need to hit it with something carrying enough energy that its wavelength is smaller than the proton: λ = h ÷ p. Higher energy, shorter wavelength, smaller view.","Rutherford found the nucleus in 1911 by firing alpha particles at gold foil: most passed through and one in 8,000 bounced back, which only makes sense if the atom's mass sits in a spot 10⁻⁴ of its diameter across."]),
 'col':("The desert",None,["Below 10⁻¹⁸ m no structure has been found. Quarks and electrons behave as points down to the LHC's reach of about 10⁻¹⁹ m, and between there and the Planck length (1.6 × 10⁻³⁵ m) lie sixteen orders of magnitude that no experiment has entered. Theories fill it (grand unification near 10⁻³² m, strings near the Planck scale), but the eyepiece leaves it blank because that is the honest state of the evidence.","The Planck length is √(ħG/c³): the scale at which a photon energetic enough to resolve it would have enough energy to form a black hole of the same size. It is not a pixel size of space; it is where quantum mechanics and gravity both matter and no accepted theory covers both."]),
 'max':("Where the constants set the scales",None,["Every notch on the inward focus corresponds to a physical constant. The Bohr radius ħ²/(m_e e² k) sets 10⁻¹⁰ m; the proton size comes from QCD's confinement scale, Λ_QCD ≈ 200 MeV, giving 10⁻¹⁵ m; the electroweak scale 1/(246 GeV) gives 10⁻¹⁸ m; the Planck length combines ħ, G and c. The lengths of chemistry and biology (10⁻⁹ to 10⁻⁵ m) follow from the Bohr radius times the counting of atoms, which is why life is the size it is.","The desert is the hierarchy problem stated in metres: nothing in the Standard Model explains why the electroweak scale sits seventeen decades above the Planck scale. Naturalness predicted new structure near 10⁻¹⁹ m; the LHC has not found it, and the eyepiece's blank band is the current shape of that ignorance."]),
}
GROWN={
 1:"Let kids count notches out loud. The number that matters is not any one size but the count of tens between two things.",
 2:"The empty band near the end is deliberate and true. If a child asks what is there, the honest answer is that nobody knows, and that is a good place to leave it.",
}
UNITS=[('m','metres'),('km','kilometres'),('mm','millimetres'),('µm','micrometres'),('nm','nanometres'),('ly','light-years'),('Gyr','billion years'),('n','a plain number or count')]
UNIT_WHY={'m':'metres measure a length','km':'kilometres measure a length: a thousand metres','mm':'millimetres measure a length: a thousandth of a metre','µm':'micrometres measure a length: a millionth of a metre','nm':'nanometres measure a length: a billionth of a metre','ly':'a light-year is a length: how far light goes in a year','Gyr':'billion years measures a time','n':'a count or a ratio, no unit'}
CHECK={
 1:{'k5':("The Earth is about 13,000 km across. The Sun is 100 times wider. How wide is the Sun?",1300000,'km',.05,"100 times 13,000.","Right. About 1,300,000 km: 109 Earths in a row."),
    'g8':("The Milky Way is 10²¹ m across and the solar system is 10¹³ m. How many powers of ten bigger is the galaxy?",8,'n',.02,"Subtract the exponents.","Right. Eight: a hundred million times wider."),
    'hs':("Light travels 3 × 10⁸ m/s and a year has 3.15 × 10⁷ seconds. How far is one light-year, in metres?",9.46e15,'m',.03,"Speed times time.","Right. 9.46 × 10¹⁵ m."),
    'col':("The observable universe is 8.8 × 10²⁶ m across; the Planck length is 1.6 × 10⁻³⁵ m. How many powers of ten separate them?",61.7,'n',.02,"log₁₀ of the ratio.","Right. About 62 orders of magnitude, and you are near the middle."),
    'max':("Andromeda is 2.5 million light-years away and approaching at 110 km/s. Ignoring acceleration, time to arrival in billions of years? (1 ly = 9.46 × 10¹² km)",6.8,'Gyr',.05,"Distance in km over speed, then seconds to years.","Right. Roughly 7 billion years by this estimate; with gravity speeding it up, about 4.5.")},
 2:{'k5':("A hair is 100 micrometres wide. A blood cell is 10 times smaller. How wide is the blood cell?",10,'µm',.02,"100 divided by 10.","Right. About 10 micrometres, close to the real 8."),
    'g8':("A virus is 100 nanometres across and an atom is 0.1 nanometres. How many atoms would fit across the virus?",1000,'n',.02,"100 ÷ 0.1.","Right. A thousand."),
    'hs':("Visible light can resolve about 250 nm at best. A ribosome is 25 nm. How many times too small to see with light?",10,'n',.02,"250 ÷ 25.","Right. Ten times: that is why ribosomes were found with electrons."),
    'col':("A gold nucleus is 1.5 × 10⁻¹⁴ m across inside an atom 3 × 10⁻¹⁰ m across. The nucleus is 1 part in how many of the atom's width?",20000,'n',.05,"Divide the diameters.","Right. One in 20,000: a pea in a stadium."),
    'max':("The Planck length is √(ħG/c³). With ħ = 1.05 × 10⁻³⁴ J·s, G = 6.67 × 10⁻¹¹ and c = 3 × 10⁸ m/s, what is it in metres?",1.6e-35,'m',.06,"Multiply ħ by G, divide by c³, take the square root.","Right. About 1.6 × 10⁻³⁵ m.")},
}
FIG={
 1:'''<div class="panel"><canvas id="cv-tele" aria-label="A round eyepiece. Drag up and down or use the mouse wheel to change the field of view from a person out to the observable universe; objects are drawn at true relative size."></canvas></div>
    <div class="controls"><button class="btn" id="te-in">Zoom in ×10</button><button class="btn primary" id="te-out">Zoom out ×10</button><label class="slider">Focus <input type="range" id="te-e" min="-34.5" max="27.3" step="0.05" value="0.7"><span class="val" id="te-e-val"></span></label><span class="lbl">Objectives</span><button class="btn" data-teobj="0.7">You</button><button class="btn" data-teobj="7.4">Earth</button><button class="btn" data-teobj="9.5">Sun</button><button class="btn" data-teobj="13.2">Solar system</button><button class="btn" data-teobj="16.8">Nearest star</button><button class="btn" data-teobj="21.3">Milky Way</button><button class="btn" data-teobj="23.3">Local Group</button><button class="btn" data-teobj="27.2">Universe</button></div>
    <figcaption><b>Try this:</b> drag the eyepiece up, or roll the wheel, and count the powers of ten until the Earth fits. Keep going until the Sun is a dot, then until the galaxy is. Find the emptiest place on the way.</figcaption>''',
 2:'''<div class="panel"><canvas id="cv-micro" aria-label="A round eyepiece. Drag or use the wheel to change the field of view from a person down to the Planck length; objects are drawn at true relative size and the unexplored band is left blank."></canvas></div>
    <div class="controls"><button class="btn primary" id="mi-in">Zoom in ×10</button><button class="btn" id="mi-out">Zoom out ×10</button><label class="slider">Focus <input type="range" id="mi-e" min="-34.5" max="27.3" step="0.05" value="0.3"><span class="val" id="mi-e-val"></span></label><span class="lbl">Objectives</span><button class="btn" data-miobj="0.3">You</button><button class="btn" data-miobj="-3.7">Hair</button><button class="btn" data-miobj="-5">Cell</button><button class="btn" data-miobj="-6.8">Virus</button><button class="btn" data-miobj="-8.6">DNA</button><button class="btn" data-miobj="-9.8">Atom</button><button class="btn" data-miobj="-13.7">Nucleus</button><button class="btn" data-miobj="-14.7">Proton</button><button class="btn" data-miobj="-34.5">Planck</button></div>
    <figcaption><b>Try this:</b> dive into your hand until one cell fills the view, then a virus, then an atom. Find the wavelength of light on the way and notice what happens to the picture after it. Then cross the empty band.</figcaption>''',
}
ALL=['k5','g8','hs','col','max']
MISSIONS=[
 ('sc1','ch1',ALL,"Zoom out until the whole Earth fits in the eyepiece."),
 ('sc1b','ch1',ALL,"Keep going until the Sun is a dot and the whole solar system is in view."),
 ('sc1c','ch1',ALL,"Find the emptiest place: the gap between the Sun and the nearest star."),
 ('sc1d','ch1',ALL,"Reach the edge of the observable universe."),
 ('sc1e','ch1',['g8','hs','col','max'],"Come back home: from the universe, land on Earth using only the focus, no objective buttons."),
 ('sc2','ch2',ALL,"Zoom in until a red blood cell fills the eyepiece."),
 ('sc2b','ch2',ALL,"Find the virus."),
 ('sc2c','ch2',['g8','hs','col','max'],"Find the wavelength of visible light: nothing much smaller than it can be seen with light."),
 ('sc2d','ch2',ALL,"Reach an atom."),
 ('sc2e','ch2',ALL,"Go inside: find the proton."),
 ('sc2f','ch2',['g8','hs','col','max'],"Cross the empty band all the way to the Planck length."),
 ('sc2g','ch2',['hs','col','max'],"From you to the atom using only the focus, no objective buttons."),
]+[(f'tb{n}',f'ch{n}',ALL,"Teach it back: answer the check question below with the right unit.") for n in range(1,3)]
CLOSING=("Sixty-two powers of ten, and you are near the middle.","From the Planck length to the edge of what light has had time to show us, everything sits on one ruler. Read the exponent and you know where you are.")
