KEY='time'
TITLE='The Stopwatch'
FAVICON='⏱️'
DESC="One stopwatch that is a slow-motion camera and a time-lapse camera at once: turn it from one second up to the age of the universe and the last stars, or down through milliseconds, femtoseconds and attoseconds to the Planck time, and watch what happens at every power of ten."
EYEBROW="Time: slow motion and time-lapse in one"
TRAIL=[('top','Start'),('ch1','1 · All the way slow'),('ch2','2 · All the way fast')]
HERO={
 'k5':"Look through the stopwatch. Turn it one way and time speeds up: the Earth spins, the Moon swings round, people live whole lives, dinosaurs come and go, stars burn out. Turn it the other way and time slows down: you watch a fly's wing flap, a molecule wobble, light crawl across an atom, all the way down to the tiniest bit of time there is.",
 'g8':"Every click is a power of ten in time. Up from one second: a day is about 10⁵ seconds, a year 10⁷, a human life 10⁹, the universe 10¹⁷. Down from one second: a wingbeat is 10⁻³, a flash of light 10⁻¹⁵, the shortest time ever measured about 10⁻¹⁹, and the Planck time 10⁻⁴⁴. The stopwatch shows what is happening at each one, playing at its real speed.",
 'hs':"About 150 orders of magnitude of time, from the Planck time (5.4 × 10⁻⁴⁴ s) to the evaporation of the largest black holes (around 10¹⁰⁷ s). The lens plays every event at its true rate relative to the window: events much faster than the window blur, events much slower freeze. Read the exponents and you can place any process, from a chemical bond to a galactic year, on one axis.",
 'col':"A log-time viewer: periods, lifetimes and ages from particle physics to cosmology, with the honest gaps. It shows why chemistry lives at femtoseconds, biology at milliseconds to years, geology at millions of years, and why nothing we can measure happens between the electroweak and Planck scales. Periodic processes, decays and one-off durations are drawn differently, because they are different kinds of time.",
 'max':"Time scales are set by energies: a process at energy E happens on a time of order ħ/E. That single relation lines up the Planck time (ħ/E_Planck), weak decays, atomic orbits (ħ/13.6 eV ≈ 50 as), molecular vibrations, and thermal jiggling at room temperature (ħ/kT ≈ 25 fs). Above the human scale gravity and orbital mechanics take over. The stopwatch is that map, from ħ/E_Planck to the cosmic horizon and past it.",
}
STANDARDS={1:"5-ESS1-1, MS-ESS1-4, HS-ESS1-1, HS-ESS1-6 · Crosscutting: scale, proportion and quantity",2:"MS-PS4-1, HS-PS1-1, HS-PS4-1, HS-PS4-3 · Crosscutting: scale, proportion and quantity"}
CH={}
CH[1]={
 'k5':("All the way slow",None,["Start at one second: your heart beats once. Make the stopwatch slower and slower and the world speeds up. The Earth spins in a day. The Moon goes round in a month. A person lives a whole life. The dinosaurs come and go. The Sun circles the galaxy.","Keep going past the age of the universe and into the far future, when the last stars fade out. Every click makes the window ten times longer. Count the clicks."]),
 'g8':("Powers of ten, forward",None,["Each click multiplies the window by ten. A day is 86,400 seconds, about 10⁵. A year is about 3 × 10⁷. A human life is about 2.5 × 10⁹, and the age of the universe is 4.4 × 10¹⁷ seconds. So you live for about 10⁻⁸ of cosmic history, one hundred-millionth.","Past today the clicks keep going. The smallest stars will burn for about ten trillion years, and after that the universe goes dark for a stretch of time so long that the whole past is a blink by comparison."]),
 'hs':("Reading time in exponents",None,["Write a duration as a × 10ⁿ seconds and compare exponents: a year (3.2 × 10⁷ s) and a human life (2.5 × 10⁹ s) differ by two, the age of the Earth (1.4 × 10¹⁷ s) and of the universe (4.4 × 10¹⁷ s) by half of one. The Earth has existed for a third of cosmic time.","Radioactive decay makes deep time measurable: carbon-14 halves every 5,730 years, uranium-238 every 4.5 billion. Decay is the clock of geology and archaeology, and each isotope is readable across a few powers of ten around its half-life."]),
 'col':("Deep time and the far future",None,["Stellar lifetimes scale roughly as M⁻²·⁵: the Sun lasts about 10¹⁰ years, a 0.1-solar-mass red dwarf about 10¹³. Star formation runs out of gas around 10¹⁴ years, and after that the universe enters a degenerate era of cooling remnants.","Black holes evaporate by Hawking radiation on a time t ∝ M³: about 10⁶⁷ years for a solar mass, of order 10¹⁰⁰ years for the largest. The log axis is the only way to see these eras at all; on a linear axis the entire past is a point."]),
 'max':("Where the clock is set",None,["On the long side, time scales come from gravity: orbital periods go as √(r³/GM), the age of the universe is of order 1/H₀, and stellar lifetimes are set by the ratio of nuclear energy to luminosity. The far-future numbers depend on physics we have not measured, such as proton decay; if the proton lives about 10³⁴ years or more, degenerate matter disappears long before black holes do.","The stopwatch treats these as estimates and says so. What is solid is the ordering, and how the gaps between eras grow as powers of ten."]),
}
CH[2]={
 'k5':("All the way fast",None,["Now make the stopwatch faster and faster, and the world slows down. A blink takes forever. A fly's wings flap slowly enough to watch. A computer takes one tiny step. Light, the fastest thing there is, goes only a foot.","Keep going and you watch molecules wobble, then light crawl across an atom. Then there is a long stretch where nothing we know of happens, and at the very bottom, the tiniest bit of time there is. Poke it and see."]),
 'g8':("Powers of ten, backward",None,["Below a second the units come in steps of a thousand: milliseconds (10⁻³), microseconds (10⁻⁶), nanoseconds (10⁻⁹), picoseconds (10⁻¹²), femtoseconds (10⁻¹⁵), attoseconds (10⁻¹⁸), zeptoseconds (10⁻²¹) and yoctoseconds (10⁻²⁴). Each has its own world: wingbeats, computer ticks, molecules, electrons.","The shortest time ever measured is 247 zeptoseconds, light crossing a hydrogen molecule. The Planck time, 5 × 10⁻⁴⁴ seconds, is twenty powers of ten shorter still, and nobody has measured anything there."]),
 'hs':("Frequency and period",None,["A period T and a frequency f are the same fact: f = 1/T. The 440 Hz note A has T = 2.3 ms; a 3 GHz processor ticks every 0.33 ns; green light oscillates at 5.6 × 10¹⁴ Hz, a period of 1.8 fs. To film something you need a flash shorter than what you are filming, which is why chemistry needed femtosecond lasers and electrons needed attosecond ones (Nobel Prize, 2023).","Particle lifetimes are the other short clocks: a muon lives 2.2 µs, a Higgs boson about 10⁻²² s, a top quark about 5 × 10⁻²⁵ s."]),
 'col':("Energy sets the time",None,["Short times go with high energies: Δt ≈ ħ/ΔE. Visible light (about 2 eV) gives femtoseconds, atomic binding (about 10 eV) gives tens of attoseconds, and the W and Z bosons, whose energy is smeared over about 2 GeV, live about 3 × 10⁻²⁵ s. That is why each field of science has its own home on the axis.","Below the electroweak scale there is a desert: no known process between about 10⁻²⁵ s and the inflation epoch, and nothing at all we can reach down at the Planck time."]),
 'max':("The Planck time",None,["t_P = √(ħG/c⁵) ≈ 5.4 × 10⁻⁴⁴ s, the time for light to cross a Planck length. At that scale the energy needed to probe it would make a black hole of the same size, so quantum mechanics and general relativity both claim the territory and neither gives a sensible answer.","Whether spacetime is discrete there, emergent, or smooth all the way down is open. The stopwatch leaves it as a flicker you can poke, because that is the honest state of knowledge."]),
}
GROWN={
 1:"Let kids count clicks out loud. The number that matters is not any one duration but how many tens separate two things: a day and a human life are four clicks apart, a human life and the universe eight.",
 2:"The empty stretch near the bottom is deliberate. If a child asks what happens there, the honest answer is that nobody knows, and poking the Planck time is a good way to say so.",
}
UNITS=[('s','seconds'),('min','minutes'),('h','hours'),('d','days'),('yr','years'),('ms','milliseconds'),('ns','nanoseconds'),('fs','femtoseconds'),('Gyr','billion years'),('km','kilometres'),('n','a plain number or count')]
UNIT_WHY={'s':'seconds measure a time','min':'minutes measure a time: 60 seconds','h':'hours measure a time: 3,600 seconds','d':'days measure a time: 86,400 seconds','yr':'years measure a time','ms':'milliseconds measure a time: a thousandth of a second','ns':'nanoseconds measure a time: a billionth of a second','fs':'femtoseconds measure a time: a millionth of a billionth of a second','Gyr':'billion years measures a time','km':'kilometres measure a length: how far, not how long','n':'a count or a ratio, no unit'}
CHECK={
 1:{'k5':("There are 60 seconds in a minute and 60 minutes in an hour. How many seconds in an hour?",3600,'s',.02,"60 times 60.","Right. 3,600 seconds."),
    'g8':("A year is about 3 × 10⁷ seconds and the universe is about 4.4 × 10¹⁷ seconds old. How many powers of ten apart are they?",10,'n',.06,"Subtract the exponents.","Right. About ten: ten billion years."),
    'hs':("Carbon-14 halves every 5,730 years. A bone has 25% of its carbon-14 left. How old is it, in years?",11460,'yr',.03,"25% is two halvings.","Right. Two half-lives: 11,460 years."),
    'col':("Hawking evaporation time goes as M³. A black hole 10 times the Sun's mass lasts how many times longer than one of 1 solar mass?",1000,'n',.02,"Cube the mass ratio.","Right. A thousand times longer."),
    'max':("The universe is 13.8 billion years old. Hubble time 1/H₀ with H₀ = 70 km/s/Mpc (1 Mpc = 3.086 × 10¹⁹ km), in billions of years?",14,'Gyr',.05,"1/H₀ in seconds, then years; answer in billions.","Right. About 14 billion years, close to the real age.")},
 2:{'k5':("A fly beats its wings 200 times in one second. How many times in 10 seconds?",2000,'n',.02,"200 times 10.","Right. 2,000 flaps."),
    'g8':("Light travels 300,000 km every second. How far does it go in one millisecond?",300,'km',.03,"Divide by a thousand.","Right. 300 km: from New York to Washington, D.C. in a thousandth of a second.")
    ,'hs':("Green light has a frequency of 5.6 × 10¹⁴ Hz. What is its period, in femtoseconds?",1.8,'fs',.05,"T = 1/f, then convert to 10⁻¹⁵ s.","Right. 1.8 fs."),
    'col':("Use Δt ≈ ħ/ΔE with ħ = 6.6 × 10⁻¹⁶ eV·s. For ΔE = 13.6 eV (hydrogen), what is Δt in femtoseconds?",.049,'fs',.08,"Divide ħ by the energy.","Right. About 0.05 fs: 50 attoseconds."),
    'max':("The Planck time is √(ħG/c⁵). With ħ = 1.05 × 10⁻³⁴ J·s, G = 6.67 × 10⁻¹¹ and c = 3 × 10⁸ m/s, how many seconds? (answer in s)",5.4e-44,'s',.08,"Multiply ħ by G, divide by c⁵, take the square root.","Right. About 5.4 × 10⁻⁴⁴ s.")},
}
FIG={
 1:'''<div class="panel"><canvas id="cv-slow" aria-label="A round stopwatch lens with a digital stopwatch strip above it. Drag, roll the wheel or use the arrow buttons to make the window of time longer, from one second to trillions of years; events play at their true speed."></canvas></div>
    <details class="bench"><summary>Jump to</summary><div class="controls"><label class="slider">Window <input type="range" id="sl-e" min="-43.4" max="108" step="0.05" value="0"><span class="val" id="sl-e-val"></span></label><button class="btn" data-slstop="0">One second</button><button class="btn" data-slstop="4.94">Day</button><button class="btn" data-slstop="7.5">Year</button><button class="btn" data-slstop="9.4">Human life</button><button class="btn" data-slstop="15.32">Dinosaurs</button><button class="btn" data-slstop="17.64">Universe</button><button class="btn" data-slstop="21.5">Last stars</button><button class="btn" data-slstop="107.48">The very end</button></div></details>
    <figcaption><b>Try this:</b> start at one heartbeat and make the window longer, one click at a time, until the Earth spins, then until a whole life fits, then past the age of the universe.</figcaption>''',
 2:'''<div class="panel"><canvas id="cv-fast" aria-label="A round stopwatch lens with a digital stopwatch strip above it. Drag, roll the wheel or use the arrow buttons to make the window of time shorter, from one second down to the Planck time; events play in slow motion at their true speed."></canvas></div>
    <details class="bench"><summary>Jump to</summary><div class="controls"><label class="slider">Window <input type="range" id="fa-e" min="-43.4" max="108" step="0.05" value="0"><span class="val" id="fa-e-val"></span></label><button class="btn" data-fastop="0">One second</button><button class="btn" data-fastop="-2.3">Wingbeat</button><button class="btn" data-fastop="-9">Nanosecond</button><button class="btn" data-fastop="-13.96">Molecule</button><button class="btn" data-fastop="-18.61">Shortest measured</button><button class="btn" data-fastop="-23.25">Proton</button><button class="btn" data-fastop="-43.27">Planck time</button></div></details>
    <figcaption><b>Try this:</b> slow time down until a fly's wing flaps gently, then until a molecule wobbles, then until light crawls across a molecule. Then cross the empty stretch to the Planck time and press A to poke it.</figcaption>''',
}
ALL=['k5','g8','hs','col','max']
MISSIONS=[
 ('t1','ch1',ALL,"Make the window long enough to watch the Earth spin."),
 ('t1b','ch1',ALL,"Watch the Earth go once round the Sun."),
 ('t1c','ch1',ALL,"Reach the age of the universe."),
 ('t1d','ch1',['g8','hs','col','max'],"Go past the day the last stars go out."),
 ('t1e','ch1',ALL,"Bet on when people show up if Earth's history were one day."),
 ('t2','ch2',ALL,"Slow time down enough to watch a fly beat its wings."),
 ('t2b','ch2',ALL,"Watch a molecule vibrate."),
 ('t2c','ch2',['g8','hs','col','max'],"Find the shortest time anyone has ever measured."),
 ('t2d','ch2',ALL,"Reach the Planck time."),
 ('t2e','ch2',ALL,"Poke the Planck time."),
 ('t2f','ch2',ALL,"Bet on attoseconds against the age of the universe."),
]+[(f'tb{n}',f'ch{n}',ALL,"Teach it back: answer the check question below with the right unit.") for n in range(1,3)]
CLOSING=("About 150 powers of ten, and you live in the middle.","From the Planck time to the last black hole, everything that happens sits on one stopwatch. Read the exponent and you know what kind of world you are in.")

from bets import bet
FIG[1]=bet('sl-bet',"Squeeze the whole 4.5-billion-year history of the Earth into one day. When do people like us show up?",[('hours','A few hours before midnight'),('minutes','A few minutes before midnight'),('seconds','A few seconds before midnight')])+FIG[1]
FIG[2]=bet('fa-bet',"Which is bigger: the number of attoseconds in one second, or the number of seconds since the Big Bang?",[('as','Attoseconds in one second'),('bb','Seconds since the Big Bang'),('same','About the same')])+FIG[2]
