KEY='life'
TITLE='How Life Changes'
FAVICON='🧬'
DESC="Heredity and evolution as six games: copy a DNA recipe and count the mistakes, hunt moths as the bird, flip peas with Mendel, race bacteria against antibiotics, drift on a small island, and rebuild the tree of life from shared differences. Every game is scored by the real probability."
EYEBROW="Heredity and evolution, K to 12"
TRAIL=[('top','Start'),('ch1','1 · Copy me'),('ch2','2 · The moth game'),('ch3','3 · Pea flips'),('ch4','4 · The bacteria race'),('ch5','5 · Drift island'),('ch6','6 · The tree of life')]
HERO={
 'k5':"Every living thing is a recipe that gets copied. Copies have tiny mistakes. Some mistakes help, and the helpful ones get copied more. That is the whole trick, and it made everything alive, from moss to you. Six games let you run the trick yourself.",
 'g8':"Living things copy their instructions, and no copy is perfect. Which copies get made again depends on the world they land in. Run that loop long enough and you get eyes, wings, and antibiotic-proof germs. Six games, one for each piece of the loop: copy, select, inherit, multiply, drift, and branch.",
 'hs':"Heredity and evolution as six experiments: mutation as copying error, natural selection with you as the predator, Mendelian ratios from real random draws, exponential growth and the rise of resistance, genetic drift in small populations, and phylogenetic trees rebuilt from shared differences. Each is scored by the real probability.",
 'col':"Mutation rates and proofreading, selection coefficients and the change in allele frequency they produce, Hardy–Weinberg and chi-square, logistic growth with mutation, selection and combination therapy, Wright–Fisher drift and effective population size, distance-based tree building with a Jukes–Cantor correction. Every model states its assumptions.",
 'max':"The same six games read as population genetics: the error threshold, the breeder's equation and stabilizing selection, Mendel's ratios as the evidence for particulate inheritance, Luria and Delbrück on the randomness of mutation, coalescent time scales, and the combinatorial size of tree space. Where the textbook picture stops is marked in each chapter.",
}
STANDARDS={1:"MS-LS3-1, HS-LS1-1, HS-LS3-2",2:"3-LS4-3, MS-LS4-4, MS-LS4-6, HS-LS4-2, HS-LS4-4",3:"3-LS3-1, MS-LS3-2, HS-LS3-3",4:"MS-LS2-1, MS-LS4-6, HS-LS4-3, HS-LS4-4",5:"MS-LS4-6, HS-LS4-3, HS-LS4-5",6:"3-LS4-1, MS-LS4-1, MS-LS4-2, HS-LS4-1"}
CH={}
CH[1]={
 'k5':("Copy me",None,["Inside every living thing is a recipe written in four letters: A, T, C and G. When a cell splits in two, it copies the whole recipe. Copiers make mistakes. A mistake in the recipe is called a <em>mutation</em>.","Most mistakes do nothing. Some break the recipe. Once in a while one makes it better. Copy the recipe here and count the mistakes. Then turn on proofreading and see what a careful copier can do."]),
 'g8':("Every copy has mistakes",None,["DNA is a chain of four letters, and a cell copies all of it before it divides: about three billion letters in each of your cells. The copying machine gets roughly one letter in a hundred million wrong, after checking its own work. That sounds small, but three billion letters times a tiny error rate still leaves you with about sixty letters your parents did not have.","Mutations are the raw material. They are random with respect to what would be useful: the copier does not know what the organism needs. Most land in stretches that do not matter, some do harm, and a very few help. The next chapter is about what happens to those."]),
 'hs':("Mutation is copying error",None,["Mutation is a change in the DNA sequence. Point mutations swap one base; insertions and deletions shift the reading frame; larger events copy or lose whole stretches. The per-base rate per generation is about 10⁻⁸ in humans and about 10⁻¹⁰ per base per division in bacteria, but bacteria divide so often, and there are so many of them, that new resistance mutations appear inside a single infected patient.","In the lab, the expected number of differences after g copies of an L-letter sequence at error rate e is e·L·g, as long as the differences are few. When they are many, the same letter can change twice and the count saturates; the lab shows that too."]),
 'col':("Mutation rates and proofreading",None,["DNA polymerase alone mis-pairs about 1 in 10⁵ bases. Its 3′→5′ exonuclease proofreading removes about 99% of those, and post-replication mismatch repair another 99%, giving the observed 10⁻⁹ to 10⁻¹⁰ per base per division. Mutator strains that lose one layer have rates a hundred times higher, and they turn up in chronic infections and in tumours, where a high mutation supply is temporarily an advantage.","Mutation is not uniform along the sequence: transitions outnumber transversions about two to one, CpG sites mutate an order of magnitude faster through deamination of methylcytosine, and replication timing and chromatin state modulate the rate. The lab's uniform error rate is the first approximation."]),
 'max':("The error threshold",None,["Eigen's error threshold: a replicator of length L with per-base error e keeps its information only if e·L ≲ ln σ, where σ is the selective advantage of the master sequence. Above that, the population melts into a cloud of mutants and the best sequence is lost. RNA viruses with L ≈ 10⁴ live near e ≈ 10⁻⁴, right at the edge, which is why mutagenic drugs such as favipiravir and molnupiravir can push them over it.","Mutation rate itself evolves. The drift-barrier hypothesis holds that selection lowers it until the marginal benefit is smaller than 1/N_e, which is why large-population microbes have lower per-base rates than large animals, and why per-genome-per-generation rates are surprisingly similar across life."]),
}
CH[2]={
 'k5':("The moth game",None,["Moths rest on tree bark all day. Birds eat the ones they can see. A moth that matches the bark is hard to spot, so it lives, and has babies that look like it.","You are the bird. Eat as many moths as you can before the time runs out. Then watch what the next generation looks like. Then make the bark sooty and play again."]),
 'g8':("The bird chooses",None,["In England in the 1800s, factory smoke blackened the trees, and within fifty years the peppered moths near the cities were almost all dark. When the air was cleaned up, the pale ones came back. Nobody changed the moths. Birds ate the easy-to-see ones, and the survivors bred.","That is natural selection: variation, inheritance, and a difference in who survives. It needs no plan and no goal. The bird is not trying to make the moths dark. It is just hungry."]),
 'hs':("Natural selection",None,["Natural selection needs three things: variation in a trait, heritability of that trait, and a difference in survival or reproduction linked to it. In the lab the trait is shade, offspring inherit their parent's shade with a little noise, and you (or the automatic bird) remove the ones you can see. The population mean tracks the bark within a handful of generations.","Kettlewell's experiments on <em>Biston betularia</em> in the 1950s, and Majerus's seven-year replication published in 2012, measured exactly this: predation by birds, differing by background, strong enough to explain the historical change."]),
 'col':("Selection coefficients",None,["Write the survival of the two types as w_dark and w_pale and the frequency of dark as p. After one round of selection, p′ = p·w_dark ÷ (p·w_dark + q·w_pale). With relative fitnesses 1 and 1 − s, the change per generation is Δp ≈ s·p·q for small s: fastest at intermediate frequency and slow at both ends, which is the S-shaped curve the lab plots.","For a continuous trait like shade, the response to selection is the breeder's equation R = h²·S: the shift in the next generation equals the heritability times the difference between the survivors' mean and the population mean. The lab's inheritance rule sets h² near one; real traits are lower, and the lab reports both S and R so you can read h² off."]),
 'max':("Stabilizing selection",None,["The moth story is directional selection. Set the bark to grey and the same machinery becomes stabilizing: extremes are eaten, the mean stays put, and the variance shrinks each generation until mutation replenishes it. Most selection in nature is of this kind, which is why populations look stable while selection is strong.","The genetics behind the moth is known: the dark morph is a single transposable-element insertion in the <em>cortex</em> gene, dated to about 1819, that reached 98% frequency near Manchester by 1895. A selection coefficient near 0.2 fits both the rise and the decline."]),
}
CH[3]={
 'k5':("Pea flips",None,["Every pea plant carries two copies of the 'how tall' instruction, one from each parent. A baby gets one copy from each. Some copies say tall (T) and some say short (t). If a plant has even one tall copy, it grows tall.","Pick the parents and grow the babies. Count tall and short. Grow more and see what number the count keeps landing near."]),
 'g8':("Two copies of every instruction",None,["Gregor Mendel counted thousands of pea plants in the 1860s and found that traits do not blend: they come in units, now called genes, and each plant carries two copies, called alleles. A tall parent with copies T and t passes on T or t with equal chance, like a coin flip. Cross two Tt parents and you get TT, Tt, tT and tt in equal numbers: three tall for every one short.","The Punnett square in the lab is just the four coin-flip outcomes. The lab draws real random babies, so the count wobbles: grow a hundred and it lands near 3 to 1; grow four and it might not."]),
 'hs':("Mendel's ratios",None,["Mendel's law of segregation: the two alleles separate into gametes with equal probability. Independent assortment: alleles at different genes segregate independently when they sit on different chromosomes. A dihybrid TtRr × TtRr therefore gives 9 : 3 : 3 : 1. Dominance is not the rule but a common case; many alleles are codominant or incompletely dominant, and most traits involve many genes.","Statistics matter here. A 3 : 1 ratio from 4 plants is weak evidence; from 400 it is strong. The lab reports the deviation from expectation as the sample grows."]),
 'col':("Hardy–Weinberg",None,["Scale up from a cross to a population. If alleles T and t have frequencies p and q with no selection, mutation, migration or drift, and mating is random, genotype frequencies are p², 2pq and q², and they stay there: the Hardy–Weinberg equilibrium. It is the null model of population genetics; departures from it are how selection, inbreeding and population structure are detected.","A recessive trait seen in 4% of a population implies q = 0.2 and carriers 2pq = 32%. That arithmetic is the basis of genetic counselling, and of the observation that rare recessive alleles hide in heterozygotes where selection can barely touch them."]),
 'max':("Why the ratios mattered",None,["Mendel's ratios were the first hard evidence that inheritance is particulate rather than blending, which removes the strongest objection to Darwin: that variation would be halved every generation. Fisher showed in 1918 that many Mendelian loci of small effect produce exactly the continuous, normally distributed traits and parent–offspring correlations the biometricians had measured. That reconciliation is the modern synthesis.","Fisher also noted that Mendel's counts fit expectation too well, with an improbably small χ²; the debate continues. The lab's honest random draws show what real sampling noise looks like."]),
}
CH[4]={
 'k5':("The bacteria race",None,["A germ splits into two. Then those two split. Then four, eight, sixteen. In a few hours one germ becomes millions. Medicine kills germs, but if a single germ happens to be tough enough to survive, it keeps splitting, and soon every germ is the tough kind.","Fill the dish, then clear it with medicine. Then try stopping the medicine early and see what grows back."]),
 'g8':("Doubling and resistance",None,["Bacteria double about every 20 minutes when they are fed. Ten cells become ten thousand in a little over three hours. Among ten thousand copies, the copying mistakes from chapter 1 mean a few cells are different by chance, and once in a while one is different in a way that shrugs off an antibiotic.","The antibiotic kills the ordinary cells and leaves that one. It now has the whole dish to itself. That is why doctors say to finish the course: stopping early is exactly the experiment that breeds resistance, and it is the same natural selection as the moths, with the drug as the bird."]),
 'hs':("Exponential growth and selection",None,["Unlimited growth is N = N₀·2^(t/T) with doubling time T; with a resource limit K it bends into the logistic curve. Resistance mutations arise at a rate μ per division, so a culture that has undergone D divisions has had about μ·D chances, whether or not the drug was present. Add the drug and the sensitive cells die exponentially while the resistant ones keep growing: a selective sweep in real time.","Resistance usually costs something, so without the drug the sensitive strain can outgrow it again. The lab gives resistant cells a 10% slower doubling; watch what happens when you stop dosing after resistance has won."]),
 'col':("Mutation, growth and combination therapy",None,["Two independent resistance mutations at 10⁻⁶ each arise together at 10⁻¹², so a culture of 10⁹ cells almost surely contains single mutants and almost surely no double mutants. Give two drugs at once and no cell can escape; give them one after the other and each sweep produces the next mutant's population. That is the logic of combination therapy for tuberculosis and HIV. Try to clear a dish that resistance has already taken over.","The model is deterministic in growth and stochastic in mutation: births per step are r·N·dt, and mutant cells appear as Poisson events with mean μ times births. The lab's μ is deliberately high, about 7 × 10⁻⁵ per division, so that a dish of ten thousand breeds a resistant mutant about half the time."]),
 'max':("Luria and Delbrück",None,["Luria and Delbrück asked in 1943 whether mutations arise in response to the drug or before it. If induced, every culture gives about the same number of resistant colonies: Poisson, variance about equal to the mean. If spontaneous, a mutation early in growth is inherited by a large clone, and cultures vary wildly, with variance far above the mean. They found the jackpots. Run the fluctuation test here and read the variance.","The same distribution now underlies estimates of mutation rates, the timing of pre-existing resistance in tumours before chemotherapy, and the question of how many independent origins a resistance allele has."]),
}
CH[5]={
 'k5':("Drift island",None,["On a small island, colour does not matter to anyone. Every baby copies a random parent. That is all. Yet after a while one colour is gone, just by luck. The fewer animals, the faster it happens.","Run a tiny island and a big one. Then press the storm button that leaves only five survivors, and see what luck does to the colours."]),
 'g8':("Luck in small numbers",None,["Selection is not the only thing that changes a population. Chance does too. If only ten animals breed, the next generation is a small sample, and small samples wobble: flip ten coins and you often get seven heads. Over many generations the wobble adds up until one version wins for no reason at all. That is genetic drift.","Drift is strongest in small populations, after a disaster (a bottleneck), or when a few animals found a new colony. It is why island species and endangered ones lose variety, and why not every difference between species is an adaptation."]),
 'hs':("Genetic drift",None,["With N gene copies and a colour at frequency p, the next generation's frequency is a random draw with variance p(1 − p)/N. Given enough generations the frequency hits 0 or 1 and stays: fixation. A neutral version's chance of eventually fixing equals its current frequency, so most new neutral mutations are lost within a few generations, and the ones that do fix take on the order of N generations to do it.","Bottlenecks and founder events shrink N for a while, which is enough. The northern elephant seal, hunted to about twenty animals in the 1890s, has almost no genetic variation today although there are two hundred thousand of them."]),
 'col':("Wright–Fisher and effective size",None,["The lab is the Wright–Fisher model: non-overlapping generations, constant N, and the next generation sampled with replacement from the parents. Heterozygosity decays by a factor (1 − 1/N) per generation for N gene copies. Real populations have unequal sex ratios, variable family sizes and fluctuating size; the effective population size N_e is the Wright–Fisher N that would give the same decay, and it is usually far below the census count. For humans it is about 10⁴ despite eight billion of us.","Drift and selection compete: a version with selection coefficient s behaves nearly neutrally when |s| is smaller than about 1/N_e. In small populations harmful versions can fix and beneficial ones can be lost, which is the basis of the nearly neutral theory."]),
 'max':("Coalescent time",None,["Run the same process backwards and you get the coalescent: any two gene copies in a population of N copies share an ancestor on average N generations ago, and a whole sample coalesces in about 2N. This is the machine behind every 'most recent common ancestor' date, from mitochondrial Eve at roughly 150,000 years to the dating of SARS-CoV-2 lineages, and its assumptions, constant size and no selection, are exactly the ones the lab lets you break.","Bottlenecks compress coalescence times, which is why the expansion out of Africa shows up as a loss of diversity with distance from Africa, and why a recovering population keeps the genetic signature of its worst year for tens of thousands of years."]),
}
CH[6]={
 'k5':("Cousins",None,["Every living thing has a recipe, and cousins have recipes that look alike, because they copied from the same grandparent. The more the recipes match, the closer the cousins. That is how we know a whale is closer to a hippo than to a shark.","Five creatures. Compare their stripes. Find the two closest cousins, then keep joining until you have the whole family tree."]),
 'g8':("Shared mistakes make a family tree",None,["In the history board you saw that copies sharing the same mistake come from the same earlier copy. DNA works the same way. Two species that share a copying mistake got it from a shared ancestor, and the number of differences between them counts the time since they split. Line up the letters, count the differences, join the closest pair, repeat.","This is how the tree of life is built. It is why we can say that birds are dinosaurs, that fungi are closer to us than to plants, and that every living thing shares one ancestor from about four billion years ago."]),
 'hs':("Building a phylogeny",None,["A phylogeny is a hypothesis about ancestry. The simplest method is the one in the lab: compute a distance between every pair of sequences, join the closest pair, average their distances to everything else, and repeat. That is UPGMA, and it assumes a clock: changes accumulate at the same rate on every branch. More careful methods (neighbour joining, maximum likelihood, Bayesian inference) drop that assumption and use a model of how letters change.","The signal is shared derived characters. Shared ancestral ones say nothing about who is closer, and convergence, the same feature evolving twice, can mislead. Sequences reduce but do not eliminate this."]),
 'col':("Distances and the molecular clock",None,["Observed differences under-count real changes because a site can change twice. The Jukes–Cantor correction, d = −¾·ln(1 − 4p/3), inverts the simplest model of substitution; p saturates at 0.75 and the corrected distance goes to infinity, which is why deep splits are hard to date from fast-evolving sequences. A molecular clock calibrates d against fossils: a rate r per lineage gives a split age of d ÷ 2r.","Rates vary among lineages, genes and sites. Relaxed-clock models let each branch draw its own rate from a distribution, and mixing genes with different rates, slow ribosomal RNA for deep splits and fast mitochondrial DNA for recent ones, is standard practice."]),
 'max':("The size of tree space",None,["The number of rooted binary trees on n leaves is (2n − 3)!!: 105 for five species, about 3 × 10⁷⁴ for fifty. No method can examine them all, so tree search is heuristic, and the honest output is a posterior distribution over trees rather than one answer. Gene trees also disagree with each other through incomplete lineage sorting and horizontal transfer, so 'the' tree of life is a statistical summary, and near its root, where transfer dominated, a network.","This is the manuscript stemma of the history board made rigorous: characters shared by descent, a substitution model, and a likelihood over trees."]),
}
GROWN={
 1:"Kids may worry that mistakes are bad. Say it plainly: most do nothing, a few are bad, a very few are good, and the good ones are how we got here.",
 2:"Let them play several rounds before you explain anything. The population changing colour without anyone deciding it is the discovery.",
 3:"Two coins per parent make a physical version of this: heads is T, tails is t. Flip, record, repeat.",
 4:"The 'finish the course' message is real and lives in this game. Let a child stop the medicine early on purpose and see what grows back.",
 5:"Beads in a bag reproduce this exactly: draw ten with replacement to make the next generation.",
 6:"Younger kids can stay with 'more matching stripes means closer cousins'. The tree itself is optional at K to 5.",
}
UNITS=[('n','a plain number or count'),('%','percent'),('gen','generations'),('min','minutes'),('h','hours'),('/h','per hour'),('cells','cells'),('Myr','million years')]
UNIT_WHY={'n':'a count or a ratio, no unit','%':'percent is a share out of a hundred','gen':'generations count rounds of copying','min':'minutes measure a time','h':'hours measure a time','/h':'per hour is a rate: how much change each hour','cells':'cells count the germs','Myr':'million years measures a time since a split'}
CHECK={
 1:{'k5':("A recipe has 100 letters. The copier gets 1 in every 100 wrong. After one copy, how many letters are wrong?",1,'n',.02,"1 out of every 100, and there are 100.","Right. About 1 wrong letter."),
    'g8':("A gene is 1,000 letters long and the error rate is 1 in 10,000 per letter per copy. Copy it 50 times. Expected mistakes?",5,'n',.02,"letters × rate × copies.","Right. 1,000 × 0.0001 × 50 = 5."),
    'hs':("Error rate 2% per letter per copy. What percent of a letter's copies are still correct after 10 copies? (0.98¹⁰)",81.7,'%',.03,"Multiply 0.98 by itself ten times.","Right. About 82%: after ten copies nearly one letter in five has changed."),
    'col':("About 10⁻⁸ mutations per base per generation, and 6 × 10⁹ bases in a diploid genome. New mutations per child?",60,'n',.05,"Rate × bases.","Right. About 60, and sequencing of families finds about that many."),
    'max':("Polymerase errs once per 10⁵ bases; proofreading removes 99 of 100 errors; mismatch repair removes 99 of 100 of what is left. Errors per 10⁹ bases?",1,'n',.05,"10⁻⁵ × 10⁻² × 10⁻² per base.","Right. 10⁻⁹ per base, so about 1 per billion.")},
 2:{'k5':("50 pale moths and 50 dark moths sit on sooty bark. The bird eats 30 pale and 5 dark. How many pale moths are left?",20,'n',.02,"50 take away 30.","Right. 20 pale moths, and 45 dark ones."),
    'g8':("Of 50 pale moths, 30 were eaten. What percent of the pale moths survived?",40,'%',.02,"20 survived out of 50.","Right. 40%."),
    'hs':("Pale moths survive 40% of the time, dark 90%. Start with 50 of each. After one round, what percent of the survivors are dark?",69.2,'%',.03,"20 pale and 45 dark survive.","Right. 45 out of 65 is about 69%."),
    'col':("Relative fitness of pale is 0.44 and of dark is 1. Dark is at frequency 0.3. New dark frequency after selection? p′ = p·w_dark ÷ (p·w_dark + q·w_pale)",49.3,'%',.03,"0.3 ÷ (0.3 + 0.7 × 0.44).","Right. About 49%: from 30% to nearly half in one generation."),
    'max':("Selection coefficient s = 0.1 per generation, haploid. Generations for the favoured type to go from 1% to 50%? (ln(p/q) changes by s each generation)",46,'gen',.05,"ln(99) ÷ 0.1.","Right. About 46 generations.")},
 3:{'k5':("Two Tt pea plants have 4 babies. How many do you expect to be tall?",3,'n',.02,"Three out of every four.","Right. 3 tall, 1 short, on average."),
    'g8':("Tt × Tt gives 400 plants. Expected short plants?",100,'n',.02,"One in four is tt.","Right. 100 short."),
    'hs':("TtRr × TtRr gives 160 plants. Expected tall-and-round (the 9 in 9 : 3 : 3 : 1)?",90,'n',.02,"9 out of 16.","Right. 90."),
    'col':("A recessive trait appears in 4% of a population in Hardy–Weinberg equilibrium. What percent are carriers (2pq)?",32,'%',.02,"q² = 0.04 so q = 0.2 and p = 0.8.","Right. 32%: eight times as many carriers as affected."),
    'max':("Tt × Tt gives 290 tall and 110 short out of 400. Expected 300 and 100. χ² = ?",1.333,'n',.05,"Σ (observed − expected)² ÷ expected.","Right. 0.33 + 1 = 1.33, well under the 3.84 needed to doubt the ratio.")},
 4:{'k5':("One germ splits into 2 every 20 minutes. Start with 1. How many after 1 hour?",8,'cells',.02,"Three doublings.","Right. 1, 2, 4, 8."),
    'g8':("Doubling every 20 minutes, starting with 10 cells. How many after 2 hours?",640,'cells',.02,"Six doublings: 10 × 2⁶.","Right. 640."),
    'hs':("Doubling time 30 minutes. How long to go from 1 cell to about a million (2²⁰)?",10,'h',.03,"20 doublings × 30 minutes.","Right. 600 minutes is 10 hours."),
    'col':("Doubling time 20 minutes. Growth rate r = ln 2 ÷ T, in per hour?",2.08,'/h',.03,"T is a third of an hour.","Right. About 2.08 per hour."),
    'max':("Mutation to resistance at 10⁻⁷ per cell division. A culture grows from 1 to 10⁸ cells. Expected number of mutation events?",10,'n',.05,"About 10⁸ divisions × 10⁻⁷.","Right. About 10, so resistance was there before the drug.")},
 5:{'k5':("An island has 20 animals: 5 red and 15 blue. What percent are red?",25,'%',.02,"5 out of 20.","Right. 25%."),
    'g8':("Ten animals: 3 red, 7 blue. Each baby copies a random parent's colour. Expected red among 10 babies?",3,'n',.02,"Same share as the parents, on average.","Right. 3, but real draws wobble around it."),
    'hs':("A neutral colour is carried by 1 animal out of 50. Chance it eventually takes over the whole island?",2,'%',.02,"Its current frequency.","Right. 2%, and a 98% chance it is lost."),
    'col':("100 gene copies (50 diploid animals), p = 0.5. Standard deviation of next generation's frequency, √(pq ÷ 100), in percent?",5,'%',.03,"√(0.25 ÷ 100).","Right. 5 points per generation, and it adds up."),
    'max':("Heterozygosity decays by (1 − 1/2N) per generation. N = 10 diploid. What percent remains after 20 generations?",35.8,'%',.03,"0.95²⁰.","Right. About 36%: two-thirds of the variation gone in twenty generations.")},
 6:{'k5':("Cat and lion have 1 difference out of 10. Cat and fish have 8. How many more differences does the fish have?",7,'n',.02,"8 take away 1.","Right. 7 more: the lion is the closer cousin."),
    'g8':("Two species differ at 12 of 100 letters. Changes come at 1 letter per million years on each line. How long ago did they split?",6,'Myr',.03,"Each line collected half the differences.","Right. 6 million years, 6 changes on each side."),
    'hs':("Species A and B differ at 20 letters. The clock ticks at 2 letters per million years per lineage. Split age?",5,'Myr',.03,"20 ÷ (2 × 2).","Right. 5 million years."),
    'col':("Observed fraction of differing sites p = 0.30. Jukes–Cantor corrected distance d = −¾·ln(1 − 4p/3)?",0.383,'n',.03,"ln(0.6) is about −0.51.","Right. About 0.38, more than the 0.30 you see, because some sites changed twice."),
    'max':("Five species. How many rooted binary trees are possible? ((2n − 3)!!)",105,'n',.02,"7 × 5 × 3 × 1.","Right. 105. For twenty species it is 8 × 10²¹.")},
}
FIG={
 1:'''<div class="panel"><canvas id="cv-copy" aria-label="A DNA recipe of 24 letters copied generation after generation, with copying mistakes highlighted."></canvas></div>
    <div class="controls"><button class="btn primary" id="cp-copy">Copy it</button><button class="btn" id="cp-ten">Copy ×10</button><button class="btn" id="cp-proof" aria-pressed="false">Proofreading: off</button><label class="slider">Error rate <input type="range" id="cp-err" min="0.5" max="10" step="0.5" value="3"><span class="val" id="cp-err-val">3% per letter</span></label><button class="btn" id="cp-reset">New recipe</button></div>
    <figcaption><b>Try this:</b> copy the recipe ten times and count the mistakes. Then turn the error rate up and copy until half the letters are wrong. Then turn proofreading on and try again.</figcaption>''',
 2:'''<div class="panel"><canvas id="cv-moth" aria-label="Moths of many shades resting on bark. You are the bird: click the ones you can see before the time runs out. Survivors breed."></canvas></div>
    <div class="controls"><button class="btn primary" id="mo-go">Start a round</button><button class="btn" id="mo-auto" aria-pressed="false">Automatic bird: off</button><button class="btn" id="mo-run">Run 20 generations</button><label class="slider">Bark soot <input type="range" id="mo-soot" min="0" max="1" step="0.05" value="0.1"><span class="val" id="mo-soot-val">10%</span></label><button class="btn" id="mo-reset">Reset</button></div>
    <figcaption><b>Try this:</b> hunt for a few rounds on clean bark. Then soot the bark and hunt again, and watch the average darkness climb. Then clean it. <span data-lv="col max">Then set the bark to grey and let the automatic bird run: stabilizing selection.</span></figcaption>''',
 3:'''<div class="panel"><canvas id="cv-pea" aria-label="Two parent pea plants, a Punnett square, and a growing tally of tall and short offspring drawn at random."></canvas></div>
    <div class="controls"><span class="lbl">Parent 1</span><button class="btn" data-p1="TT">TT</button><button class="btn is-on" data-p1="Tt">Tt</button><button class="btn" data-p1="tt">tt</button><span class="lbl">Parent 2</span><button class="btn" data-p2="TT">TT</button><button class="btn is-on" data-p2="Tt">Tt</button><button class="btn" data-p2="tt">tt</button><button class="btn primary" id="pe-1">Grow 1</button><button class="btn" id="pe-10">Grow 10</button><button class="btn" id="pe-100">Grow 100</button><button class="btn" id="pe-reset">Clear</button></div>
    <figcaption><b>Try this:</b> grow four plants from Tt × Tt, then a hundred. Watch the count settle near three tall to one short. Then find the crosses that give half and half, and all tall.</figcaption>''',
 4:'''<div class="panel"><canvas id="cv-germ" aria-label="A dish of bacteria doubling over time, with a growth curve. Antibiotic buttons kill sensitive cells; resistant mutants survive."></canvas></div>
    <div class="controls"><button class="btn primary" id="bc-run" aria-pressed="false">Run</button><button class="btn" id="bc-a" aria-pressed="false">Antibiotic A: off</button><button class="btn" id="bc-b" data-lv="hs col max" aria-pressed="false">Antibiotic B: off</button><label class="slider">Doubling time <input type="range" id="bc-T" min="10" max="60" step="5" value="20"><span class="val" id="bc-T-val">20 min</span></label><button class="btn" id="bc-fluct" data-lv="col max">Fluctuation test</button><button class="btn" id="bc-reset">New dish</button></div>
    <figcaption><b>Try this:</b> run until the dish is full, then dose with A until it is empty. Then fill a new dish, dose for a while, stop early, and watch what grows back. <span data-lv="hs col max">Then use A and B together.</span></figcaption>''',
 5:'''<div class="panel"><canvas id="cv-drift" aria-label="An island of red and blue animals. Each generation every animal copies a random parent's colour. A graph tracks the red fraction."></canvas></div>
    <div class="controls"><button class="btn primary" id="dr-step">Next generation</button><button class="btn" id="dr-run" aria-pressed="false">Run: off</button><button class="btn" id="dr-storm">Storm: 5 survive</button><label class="slider">Animals <input type="range" id="dr-n" min="10" max="200" step="10" value="10"><span class="val" id="dr-n-val">10</span></label><button class="btn" id="dr-ten" data-lv="col max">Run 10 islands</button><button class="btn" id="dr-reset">Reset</button></div>
    <figcaption><b>Try this:</b> run ten animals until one colour is gone. Then two hundred. Then hit the storm and watch the mix jump.</figcaption>''',
 6:'''<div class="panel"><canvas id="cv-tree" aria-label="Five creatures with their DNA shown as coloured stripes. Click two to say they are the closest cousins; correct joins build the family tree."></canvas></div>
    <div class="controls"><button class="btn primary" id="tr-new">New puzzle</button><button class="btn" id="tr-show">Show the answer</button><label class="slider" data-lv="hs col max">Clock rate <input type="range" id="tr-rate" min="1" max="4" step="1" value="2"><span class="val" id="tr-rate-val">2 changes per Myr</span></label></div>
    <figcaption><b>Try this:</b> click the two creatures whose stripes match best. If you are right they join. Keep joining until one tree holds all five. <span data-lv="hs col max">Read the split ages off the scale.</span></figcaption>''',
}
ALL=['k5','g8','hs','col','max']
MISSIONS=[
 ('lf1','ch1',ALL,"Make 10 copies in a row."),
 ('lf1b','ch1',['g8','hs','col','max'],"With proofreading off and a high error rate, copy until half the letters are wrong."),
 ('lf1c','ch1',ALL,"Turn proofreading on and make 10 copies with no mistakes at all."),
 ('lf2','ch2',ALL,"Play a round as the bird: eat 10 moths before the time runs out."),
 ('lf2b','ch2',ALL,"Soot the bark and keep hunting until the moths are mostly dark (average darkness above 70%)."),
 ('lf2c','ch2',['g8','hs','col','max'],"Clean the bark again and bring them back to mostly pale (below 30%)."),
 ('lf2d','ch2',['col','max'],"Set the bark to grey and run 20 generations with the automatic bird: the moths settle at grey and stay."),
 ('lf3','ch3',ALL,"Cross Tt with Tt and grow at least 40 plants."),
 ('lf3b','ch3',['g8','hs','col','max'],"Grow 100 or more from Tt × Tt and land within 5 points of three-quarters tall."),
 ('lf3c','ch3',['g8','hs','col','max'],"Find a cross that gives half tall, half short, and grow 40."),
 ('lf3d','ch3',['hs','col','max'],"Find a cross that gives only tall plants without using TT × TT, and grow 20."),
 ('lf4','ch4',ALL,"Let the dish fill: ten cells to ten thousand."),
 ('lf4b','ch4',ALL,"Clear the dish with antibiotic A and keep dosing until nothing is left."),
 ('lf4c','ch4',['g8','hs','col','max'],"Stop the dose early and watch resistance take over the whole dish."),
 ('lf4d','ch4',['hs','col','max'],"Clear a dish that resistance to A has already taken over."),
 ('lf4e','ch4',['max'],"Run the fluctuation test: 10 dishes, and read a variance bigger than the mean."),
 ('lf5','ch5',ALL,"With 10 animals, run until one colour is gone."),
 ('lf5b','ch5',['g8','hs','col','max'],"With 200 animals, run 50 generations and keep both colours."),
 ('lf5c','ch5',['hs','col','max'],"Hit the storm and watch the red fraction jump by 20 points or more in one generation."),
 ('lf5d','ch5',['col','max'],"Run 10 islands of 10 and count how often red wins."),
 ('lf6','ch6',ALL,"Find the two closest cousins."),
 ('lf6b','ch6',['g8','hs','col','max'],"Build the whole tree with no mistakes."),
 ('lf6c','ch6',['hs','col','max'],"Solve three puzzles in a row with no mistakes."),
]+[(f'tb{n}',f'ch{n}',ALL,"Teach it back: answer the check question below with the right unit.") for n in range(1,7)]
CLOSING=("Copy, with mistakes. Keep what works. Repeat.","That is the whole recipe for the recipe. It has no plan, no goal and no author, and in four billion years of copying it wrote every living thing, including the one reading this.")
