KEY='infinity'
TITLE='Bigger than Infinity'
FAVICON='♾️'
DESC="Cantor's proof that some infinities are bigger than others, with games at five reading levels from kindergarten to graduate school."
EYEBROW="Georg Cantor's dangerous idea"
TRAIL=[('top','Start'),('ch1','1 · Counting by matching'),('ch2',"2 · Hilbert's Hotel"),('ch3','3 · More fractions?'),('ch4','4 · The diagonal trick'),('ch5','5 · The ladder')]
HERO={
 'k5':"Is infinity the biggest number? In 1874 Georg Cantor found out that some infinities are <em>bigger</em> than others. It made people so angry they tried to stop him. Here is how he did it, with games you can play.",
 'g8':"In 1874 Georg Cantor proved that there are different sizes of infinity. Some mathematicians called it a disease. Today it is the foundation of mathematics. This page walks through his argument step by step, with games that let you check each step yourself.",
 'hs':"Cantor's proof that the real numbers cannot be listed is one of the shortest deep proofs in mathematics. This page builds it from counting by matching, through Hilbert's Hotel and the zigzag through the fractions, to the diagonal argument and the question that turned out to have no answer.",
 'col':"Cardinality by bijection, countability of ℚ, uncountability of ℝ by diagonalization, Cantor's theorem for power sets, the aleph hierarchy, and the independence of the continuum hypothesis from ZFC. Each step has an interactive check.",
 'max':"From Cantor's 1874 and 1891 arguments to Gödel's constructible universe and Cohen's forcing: what is provable, what is independent, and why the continuum problem, first on Hilbert's list, remains open in the sense that matters.",
}
CH={}
CH[1]={
 'k5':("Counting by matching",None,["How do you know two piles have the same amount without counting? <em>Pair them up.</em> One apple, one cup. If nothing is left over, the piles are the same size. You never needed numbers at all.","Cantor's big idea: use pairing for infinite piles too, where counting would never finish."]),
 'g8':("Counting by matching",None,["A pairing where every item on each side has exactly one partner is called a one-to-one match. Two collections have the same size exactly when such a match exists.","This definition works for finite piles, and it is the only definition that still makes sense for infinite ones. Try the uneven piles: one item is left over, so no match exists, so the sizes differ."]),
 'hs':("Bijections",None,["A bijection between sets A and B is a function that is one-to-one and onto. Cantor defined |A| = |B| to mean that a bijection exists. For finite sets this agrees with counting; for infinite sets it <em>is</em> the definition.","|A| ≤ |B| means an injection A → B exists. The Cantor–Schröder–Bernstein theorem says that injections both ways give a bijection, so ≤ behaves like an order."]),
 'col':("Cardinality as an equivalence relation",None,["Cardinality is the equivalence relation on sets defined by bijections; ≤ is defined by injections; Cantor–Schröder–Bernstein shows ≤ is antisymmetric, and with the axiom of choice it is total, so any two sets are comparable. Without choice, comparability can fail.","Note what the definition does not say: same size is not same shape. ℕ and ℤ are in bijection but not order-isomorphic. Cardinality forgets everything except matching."]),
 'max':("Cardinality without choice",None,["Hartogs' theorem gives, for any set X, an ordinal that does not inject into X, choice-free; comparability of all cardinals is equivalent to AC (Hartogs 1915). In ZF alone there are Dedekind-finite infinite sets: infinite, but with no countable subset and no bijection with a proper subset, so 'infinite' splits into inequivalent notions.","Cardinal arithmetic begins here: κ ≤ λ iff an injection exists, and κ² = κ for all infinite κ is itself equivalent to AC (Tarski 1924)."]),
}
CH[2]={
 'k5':("Hilbert's Hotel","David Hilbert, 1924",["Imagine a hotel with rooms numbered 1, 2, 3 and so on <em>forever</em>, and every room is full. A new guest arrives. No problem: everyone moves up one room, and room 1 is free.","A bus with infinitely many people arrives. Still no problem: everyone moves to double their room number, and all the odd rooms are free. A full hotel with room for more. That is what infinity is like."]),
 'g8':("Hilbert's Hotel","David Hilbert, 1924",["David Hilbert used this hotel to show something strange: an infinite set can be matched one-to-one with <em>part of itself</em>. The guests in all the rooms match perfectly with the guests in only the even rooms. For finite piles that is impossible.","In fact that strangeness became the definition: a set is infinite exactly when it can be paired with a part of itself."]),
 'hs':("Countable infinity","David Hilbert, 1924",["The whole numbers ℕ, the even numbers, the integers ℤ, and even ℕ × ℕ all have the same cardinality, written ℵ₀ (aleph-null). A set that can be paired with ℕ is called countable.","Dedekind turned the hotel trick into a definition: a set is infinite if it is in bijection with a proper subset of itself. The bus is the map n ↦ 2n; the infinitely many buses need a pairing of ℕ × ℕ with ℕ."]),
 'col':("ℵ₀ and its arithmetic","David Hilbert, 1924",["Countable unions of countable sets are countable (using countable choice), which is the infinitely-many-buses case: send passenger m of bus n to room 2ⁿ3ᵐ, or use the pairing function (n, m) ↦ (n + m)(n + m + 1)/2 + m.","So ℵ₀ + ℵ₀ = ℵ₀ · ℵ₀ = ℵ₀. Infinite cardinal arithmetic is degenerate: with choice, κ + λ = κ · λ = max(κ, λ)."]),
 'max':("Where choice hides","David Hilbert, 1924",["The infinitely-many-buses step silently uses countable choice: to enumerate a countable union you must choose an enumeration of each set. In ZF alone, ℝ can be a countable union of countable sets (the Feferman–Levy model).","Dedekind-infinite versus infinite, and the dependence of cardinal arithmetic on AC, are the fault lines. The hotel is a theorem about ω; the buses are a theorem about choice."]),
}
CH[3]={
 'k5':("More fractions than whole numbers?","Cantor, 1874",["Between any two whole numbers there are endless fractions. So there must be more fractions than whole numbers, right?","Cantor said: let's try to pair them. Write every fraction in a giant grid and walk through it in a zigzag. Every fraction gets a number on the way. So there are exactly as many fractions as whole numbers. Surprise."]),
 'g8':("More fractions than whole numbers?","Cantor, 1874",["The zigzag visits every fraction eventually, so it gives each one a label: 1st, 2nd, 3rd. That is a one-to-one match between fractions and counting numbers. The fractions are <em>countable</em>.","Being densely packed does not make a set bigger than the counting numbers. Density and size are different things."]),
 'hs':("ℚ is countable","Cantor, 1874",["List positive fractions p/q in a grid indexed by (p, q), walk the diagonals p + q = 2, 3, 4, ..., skip repeats like 2/4, and interleave negatives. Every rational appears at a finite step.","So |ℚ| = ℵ₀, despite ℚ being dense in ℝ. The same trick shows the set of all finite strings over a finite alphabet is countable, so there are only countably many computer programs."]),
 'col':("Countable sets everywhere","Cantor, 1874",["The algebraic numbers are countable (Cantor 1874): each is a root of a polynomial with integer coefficients, there are countably many such polynomials, and each has finitely many roots.","That was Cantor's first route to transcendental numbers, before the diagonal argument: ℝ is uncountable, the algebraic numbers are countable, so transcendentals exist, and in fact almost all reals are transcendental, without exhibiting a single one."]),
 'max':("The 1874 proof","Cantor, 1874",["Cantor's 1874 paper proves uncountability of ℝ by nested intervals, not diagonalization: given any sequence (xₙ), build nested closed intervals avoiding each xₙ; their intersection is nonempty by completeness. The 1891 diagonal argument is the one that generalized, to power sets, Gödel's incompleteness, the halting problem, and Russell's paradox.","The countability of the algebraic numbers is the enumeration half of the first non-constructive existence proof for transcendentals, five years after Hermite's constructive proof for e."]),
}
CH[4]={
 'k5':("The diagonal trick","Cantor, 1891",["Now try the same trick with all the numbers between 0 and 1, written as endless strings of digits. Suppose you had a list of all of them.","Cantor makes a new number: look at the first digit of the first number and change it. Then the second digit of the second number, and change it. And so on down the diagonal. The new number is different from <em>every</em> number on the list. So the list was never complete. No list can ever be. These numbers are a bigger infinity."]),
 'g8':("The diagonal trick","Cantor, 1891",["Here is why the new number cannot be on the list. Is it the 1st number? No, its first digit is different. The 2nd? No, its second digit is different. It differs from the nth number at the nth digit, for every n.","Any list you write leaves something out, so the numbers between 0 and 1 cannot be paired with 1, 2, 3, .... They form a bigger infinity than the counting numbers."]),
 'hs':("The diagonal argument","Cantor, 1891",["Suppose f: ℕ → {0,1}^ℕ lists every infinite binary sequence, with f(n) = (aₙ₁, aₙ₂, ...). Define b by bₙ = 1 − aₙₙ. Then b differs from f(n) in position n, for every n, so b is not on the list. Contradiction.","Hence the infinite binary sequences are uncountable, and so is ℝ (via binary expansions, taking care with dual representations such as 0.0111... = 0.1000...). The cardinality of ℝ is written 𝔠, or 2^ℵ₀."]),
 'col':("Cantor's theorem",  "Cantor, 1891",["The argument generalizes: for any set X there is no surjection X → 𝒫(X). Given g: X → 𝒫(X), let D = {x : x ∉ g(x)}; if D = g(d) then d ∈ D ⟺ d ∉ D.","The same shape appears in Russell's paradox, in Gödel's incompleteness theorem (a sentence saying 'I am unprovable'), in Turing's halting problem, and in the Y combinator. Lawvere's fixed-point theorem (1969) states the common form: in a cartesian closed category, a point-surjective map A → Y^A forces every endomorphism of Y to have a fixed point."]),
 'max':("Diagonalization as a fixed-point theorem","Cantor, 1891",["Lawvere's theorem shows Cantor, Russell, Gödel, Tarski and Turing are one theorem in different categories; Yanofsky (2003) gives the uniform treatment. Constructively the argument is fine: it proves that no surjection exists, an intuitionistically valid negative statement.","What needs more is the classical corollary that ℝ has a definite aleph as its size: in models of ZF without choice ℝ can fail to be well-orderable, so 𝔠 need not be an aleph at all."]),
}
CH[5]={
 'k5':("The ladder, and the question nobody could answer",None,["Is there a biggest infinity? No. Cantor showed how to always make a bigger one: take all the different groups you can make from a set. That collection is always bigger than the set you started with. So the infinities climb a ladder that never ends.","Then he asked: is there an infinity in between the counting numbers and the numbers on the line? He couldn't answer it. He spent years on it. The answer, found seventy years later, was the strangest of all: <em>the question has no answer</em>. Both yes and no fit all the rules of mathematics."]),
 'g8':("The ladder, and the question nobody could answer",None,["A set with 3 things has 8 subsets. With 4 things, 16. In general 2ⁿ. Cantor proved the same holds for infinite sets: the subsets of a set always make a bigger infinity. So the infinities go up like a ladder: ℵ₀, then bigger, then bigger.","Cantor's question, the continuum hypothesis: is the infinity of the number line the very next rung after ℵ₀? In 1940 Kurt Gödel showed you cannot prove it false. In 1963 Paul Cohen showed you cannot prove it true. The usual rules of mathematics simply do not decide it."]),
 'hs':("Cantor's ladder and the continuum hypothesis",None,["Cantor's theorem: |X| < |𝒫(X)| for every set X, so ℵ₀ < 2^ℵ₀ < 2^(2^ℵ₀) < .... The continuum hypothesis (CH) says 2^ℵ₀ = ℵ₁, the first uncountable cardinal: there is no set strictly between ℕ and ℝ in size.","Gödel (1940) proved CH is consistent with the standard axioms, ZFC. Cohen (1963) proved its negation is consistent too. CH is independent of ZFC. Hilbert had put it first on his 1900 list of problems."]),
 'col':("Independence",None,["Gödel built the constructible universe L, in which every set is definable from earlier stages; L satisfies ZFC + GCH, so CH cannot be refuted. Cohen invented forcing: adjoin ℵ₂ generic reals to a model of ZFC without collapsing cardinals, giving a model where 2^ℵ₀ = ℵ₂.","Easton's theorem shows 2^κ for regular κ can be almost anything consistent with König's theorem (cf(2^κ) > κ). ZFC says remarkably little about the continuum."]),
 'max':("After independence",None,["Independence was not the end. Woodin's Ω-logic program argued for ¬CH (2^ℵ₀ = ℵ₂) from forcing axioms and the structure of H(ω₂); his later Ultimate-L program points toward CH. Forcing axioms such as PFA and MM imply 2^ℵ₀ = ℵ₂. Large cardinals settle projective statements but not CH (Levy–Solovay).","Whether CH has a determinate truth value is a live question in the philosophy of mathematics: the multiverse view (Hamkins) against the universe view (Gödel's realism, Woodin). Set-theoretic geology and the modal logic of forcing are the modern tools."]),
}
GROWN={
 1:"The pairing idea is the whole foundation. Everything that follows is 'pair it up, and see whether anything is left over.'",
 2:"The hotel is a picture of the fact that the even numbers are 'as many' as all the whole numbers. Kids often find this outrageous. That is the right reaction; Cantor's contemporaries had it too.",
 3:"The zigzag is a real proof, not a trick. The point for children is that 'more crowded' and 'more of them' are different ideas.",
 4:"This is the proof that made Cantor famous and hated. The key sentence for a child: the new number is different from every number on the list, so the list was never complete.",
 5:"Kids like the ending: the greatest mathematicians could not answer the question, and eventually proved that it cannot be answered from the usual rules. 'No answer' is itself a discovery.",
}
FIG={
 1:'''<div class="panel"><canvas id="cv-match" aria-label="Apples on the left, cups on the right. Drag from an apple to a cup to pair them."></canvas></div>
    <div class="controls"><button class="btn" id="match-reset">Start over</button></div>
    <figcaption><b>Try this:</b> drag from each apple to a cup. <span data-lv="k5">If nothing is left over, the piles are the same size.</span><span data-lv="g8 hs col max">Above the Kids level the piles are uneven: find what is left over.</span></figcaption>''',
 2:'''<div class="panel"><canvas id="cv-hotel" aria-label="A row of numbered hotel rooms with a guest in each. Buttons bring a new guest or an infinite bus."></canvas></div>
    <div class="controls"><button class="btn" id="hotel-guest">A new guest arrives</button><button class="btn blue" id="hotel-bus">An infinite bus arrives</button><button class="btn" id="hotel-reset">Fill the hotel again</button></div>
    <figcaption><b>Try this:</b> the hotel is full. Make room for one more, then for a whole busload. <span data-lv="hs col max">The bus is the map n ↦ 2n.</span></figcaption>''',
 3:'''<div class="panel"><canvas id="cv-zigzag" aria-label="A grid of fractions with a zigzag path numbering them one by one."></canvas></div>
    <div class="controls"><button class="btn" id="zig-next">Next fraction</button><button class="btn" id="zig-auto" aria-pressed="false">Auto</button><button class="btn" id="zig-reset">Start over</button></div>
    <figcaption><b>Try this:</b> step the zigzag and watch every fraction get a whole number. <span data-lv="hs col max">Repeats such as 2/4 are skipped, since 1/2 already has a number.</span></figcaption>''',
 4:'''<div class="panel"><canvas id="cv-diag" aria-label="A list of rows of binary digits. Flip the diagonal to build a row that is not on the list."></canvas></div>
    <div class="controls"><button class="btn" id="diag-flip">Flip the diagonal</button><button class="btn blue" id="diag-add">Add it to the list</button><button class="btn" id="diag-reset">New list</button></div>
    <figcaption><b>Try this:</b> flip the diagonal to build a new number, then add it to the list and flip again. The list can never catch up.</figcaption>''',
 5:'''<div class="panel"><canvas id="cv-ladder" aria-label="All subsets of a small set, and a ladder of ever larger infinities."></canvas></div>
    <div class="controls"><label class="slider">Things in the set <input type="range" id="ladder-n" min="1" max="5" step="1" value="3"><span class="val" id="ladder-n-val">3</span></label><button class="btn" id="ladder-ch" data-lv="hs col max" aria-pressed="true">Continuum hypothesis: true</button></div>
    <figcaption><b>Try this:</b> count the subsets as the set grows. <span data-lv="hs col max">Then flip the continuum hypothesis and watch nothing break. Both answers are consistent with the rules.</span></figcaption>''',
}
ALL=['k5','g8','hs','col','max']
MISSIONS=[
 ('inf1','ch1',ALL,"Pair every apple with a cup."),
 ('inf1b','ch1',['g8','hs','col','max'],"Pair as many as you can and find the one left over."),
 ('inf2','ch2',ALL,"Make room for the new guest."),
 ('inf2b','ch2',ALL,"Make room for the whole bus."),
 ('inf3','ch3',ALL,"Number 20 fractions with the zigzag."),
 ('inf3b','ch3',['hs','col','max'],"Number 30 fractions and watch the repeats get skipped."),
 ('inf4','ch4',ALL,"Flip the diagonal to make a number that is not on the list."),
 ('inf4b','ch4',['g8','hs','col','max'],"Add the new number to the list, then flip again."),
 ('inf5','ch5',ALL,"Show all 16 subsets of a four-thing set."),
 ('inf5b','ch5',['hs','col','max'],"Flip the continuum hypothesis both ways."),
]
CLOSING=("Cantor's ladder has no top.","Cantor spent his last years in and out of hospital, sure he was right and mostly alone. He was right. The next rung is still waiting for someone to say what it looks like.")
