KEY='launch'
TITLE='Launch Lab'
FAVICON='🚀'
DESC="Forces and motion as six minigames: push a car into a box, drop a hammer and a feather on four worlds, launch a car off a ramp at moving targets, crash carts, fire Newton's cannon into orbit, and stage a rocket. Every game scores with the real equations."
EYEBROW="Forces and motion, K to 12"
TRAIL=[('top','Start'),('ch1','1 · Pushes and pulls'),('ch2','2 · Everything falls the same'),('ch3','3 · The launch'),('ch4','4 · The crash lab'),('ch5','5 · Round and round'),('ch6','6 · Rockets')]
HERO={
 'k5':"Push it. Drop it. Launch it off a ramp. Crash it. Fling it into orbit. Every game here is scored by the real rules of moving things, and the rules never change. Find them, then push them as far as they will go.",
 'g8':"Six games, one set of rules. Newton wrote them down in 1687 and nothing you can build breaks them: a push changes motion, everything falls the same way, and what one thing pushes on pushes back. Each game hides one rule. Find it, use it, then beat your own distance.",
 'hs':"Newton's laws, projectile motion, momentum conservation, circular motion and the rocket equation, each as a game whose score is computed from the physics. Predict before you launch; the lab tells you how close you were.",
 'col':"Kinematics and dynamics with friction and drag, energy methods for the launcher, one-dimensional collisions in the lab and centre-of-mass frames, Newton's cannon as the bridge from projectiles to orbits, and the Tsiolkovsky equation with staging. Every model here states its assumptions.",
 'max':"The same six games read at the level of frames and invariants: Galilean invariance, the equivalence principle, conserved quantities from symmetry, the vis-viva equation, and the exponential cost of Δv. The place where the school picture stops and the real one starts is marked in each chapter.",
}
STANDARDS={1:"K-PS2-1, K-PS2-2, 3-PS2-1, MS-PS2-2, HS-PS2-1",2:"5-PS2-1, MS-PS2-4, HS-PS2-4",3:"3-PS2-1, MS-PS2-2, MS-PS3-1, MS-PS3-2, HS-PS2-1, HS-PS3-1",4:"MS-PS2-1, HS-PS2-2, HS-PS2-3",5:"MS-ESS1-2, HS-PS2-4, HS-ESS1-4",6:"MS-PS2-1, HS-PS2-2, HS-ETS1-2"}
CH={}
CH[1]={
 'k5':("Pushes and pulls",None,["A car does not move by itself. It needs a <em>push</em> or a <em>pull</em>. A bigger push makes it go faster. A rough floor slows it down sooner.","Push from behind, pull from in front, and try to stop the car inside the box. Too hard and it flies past. Too soft and it never gets there."]),
 'g8':("Force changes motion",None,["A force is a push or a pull. Forces change how something moves: they speed it up, slow it down, or turn it. When the pushes on a thing balance out, its motion does not change at all: a parked car stays parked, and a sliding puck on smooth ice keeps sliding.","Friction is the force that slows the car. Rougher floor, more friction, shorter slide. The harder you push and the longer you push, the faster it goes. That is Newton's second law in words: force changes speed, and heavier things change speed more slowly."]),
 'hs':("Newton's first and second laws",None,["F = ma: net force equals mass times acceleration. While you push, the net force is your push minus friction; after you let go, only friction acts, so the car decelerates at μg regardless of its mass. Friction on a flat floor is f = μN = μmg.","Newton's first law is the special case F = 0: no net force, no change in velocity. Try a very smooth floor and a short push: the car keeps going. Motion does not need a force; changing motion does."]),
 'col':("Friction models",None,["The lab uses Coulomb friction: f = μN, independent of speed and contact area, opposing motion, with static friction up to μₛN holding the car still until the push exceeds it. Real contact is rougher: static friction usually exceeds kinetic, and lubricated or rolling contact is velocity dependent.","Work-energy gives the stopping distance directly: ½mv² = μmgd, so d = v²/(2μg), again independent of mass. The mass cancels because both the kinetic energy and the friction force scale with it."]),
 'max':("Frames and invariance",None,["Newton's laws hold in inertial frames and are Galilean invariant: a push of 50 N produces the same acceleration whether you measure from the floor or from a train passing at constant speed. Fictitious forces appear only in accelerating frames, and the lab's floor is assumed inertial.","The deeper statement is that F = ma is a definition of force paired with an empirical claim that forces from identifiable sources (contact, gravity, springs) add as vectors. The content is in the force laws, not in F = ma itself."]),
}
CH[2]={
 'k5':("Everything falls the same",None,["Drop a hammer and a feather. The feather floats down slowly, right? Only because of the air. Take the air away and they land <em>together</em>. Astronaut David Scott did exactly this on the Moon in 1971 and they hit the ground at the same moment.","Try it here. Then try it on the Moon, on Mars, and on Jupiter."]),
 'g8':("Gravity pulls everything equally",None,["Gravity speeds up every falling thing by the same amount each second: on Earth, about 9.8 metres per second, every second. Heavy or light does not matter. What makes a feather slow is air pushing back on it, and the air pushes back harder the faster it goes until it stops speeding up.","On the Moon there is no air and gravity is a sixth of Earth's, so things fall slowly but together. On Jupiter they would fall two and a half times faster than here."]),
 'hs':("Free fall and drag",None,["Without air, h = ½gt², so the fall time from height h is t = √(2h/g). With air, drag grows with speed, F = ½ρC_dAv², until it balances weight at the terminal velocity v_t = √(2mg/(ρC_dA)). A feather reaches its terminal velocity in a fraction of a second; a hammer would need to fall for many seconds.","Mass cancels in free fall because gravitational force is proportional to mass and so is inertia. That equality is not obvious; it is one of the most precisely tested facts in physics."]),
 'col':("The equivalence principle",None,["The equality of gravitational and inertial mass has been tested to better than one part in 10¹⁴ (MICROSCOPE, 2022). Einstein promoted it to a principle: in free fall you cannot detect gravity locally. That single idea is the doorway to general relativity, which the One Rule board takes up in chapter 2.","The drag model here is quadratic, appropriate at the Reynolds numbers of a falling hammer; a dust grain would need the linear (Stokes) regime instead."]),
 'max':("Why mass cancels",None,["In Newtonian terms the cancellation is a coincidence between two different masses. In general relativity it is not a coincidence: free fall is geodesic motion, and geodesics do not depend on what is following them. Test bodies of any composition trace the same curve, which is why the feather and hammer land together.","Composition-dependent violations would signal a fifth force; torsion-balance and atom-interferometry experiments continue to look, and the Moon's own free fall toward the Sun (lunar laser ranging) tests the principle for gravitational binding energy itself."]),
}
CH[3]={
 'k5':("The launch",None,["Roll a car down a ramp and off the end. How far does it fly? Higher ramp, faster car, longer flight. Tilt the lip up and it flies higher and farther, until you tilt too much and it just goes up.","There is a box to land in. Hit it and the box moves farther away. Keep hitting it. How far can you go?"]),
 'g8':("Speed from height, distance from speed",None,["Rolling down the ramp turns height into speed. Double the height and the speed goes up by about one and a half times (it is the square root, not double). Once the car leaves the lip, two things happen at once and do not interfere: it keeps moving sideways at the same speed, and gravity pulls it down faster and faster.","Notice something strange: the mass slider does nothing, unless you turn the air on. A heavy car and a light car fly exactly the same path. Galileo figured that out with ramps four hundred years ago."]),
 'hs':("Projectile motion",None,["Energy on the ramp: mgh = ½mv², so v = √(2gh) less whatever friction takes. In flight, x = v cos θ · t and y = h₀ + v sin θ · t − ½gt². Solve y = 0 for the flight time and the range follows. On flat ground the range is v² sin(2θ)/g, greatest at 45°; with a launch height it is a little less than 45°.","Predict before you launch. The lab will tell you the error. Being within 5% consistently is the real skill."]),
 'col':("Energy methods and drag",None,["The ramp is best handled by energy, not forces: friction removes μ mg cos α per unit length along the incline, so v² = 2g(h − h₀) − 2μg L cos α. In flight with quadratic drag the equations couple and have no closed form; the lab integrates them numerically, which is why mass matters once air is on: heavier bodies have more momentum per unit drag.","The optimum angle with drag is below 45° and depends on the ballistic coefficient m/(C_dA). Real artillery tables were computed this way by hand before computers existed."]),
 'max':("Where the simple model stops",None,["Rolling versus sliding: a rolling wheel carries rotational kinetic energy ½Iω², so a solid cylinder leaves the ramp at √(4gh/3) rather than √(2gh). The lab treats the car as sliding. Air resistance, spin (Magnus force), and the Coriolis effect matter at scale; long-range artillery corrects for Earth's rotation.","Trajectory prediction under uncertainty is a control problem: small errors in launch speed propagate as δR ≈ 2Rδv/v, which is why the game rewards consistency, not one lucky hit."]),
}
CH[4]={
 'k5':("The crash lab",None,["Two carts on a track. One rolls into the other. What happens depends on how heavy they are and whether they bounce or stick. A light cart hitting a heavy one bounces back. Equal carts that bounce swap: the mover stops dead and the other takes off.","Try to make the moving cart stop completely."]),
 'g8':("Momentum",None,["Momentum is mass times speed, and in a crash the total momentum before equals the total after, always. Sticky crashes share it out: 5 kg at 2 m/s hitting 5 kg at rest gives 10 kg moving at 1 m/s. Bouncy crashes keep the total too, but the carts separate.","Bouncy crashes also keep the energy of motion. Sticky ones turn some of it into heat, sound and dented plastic. That is why cars have crumple zones: a longer, softer crash means a smaller force on you."]),
 'hs':("Conservation laws in collisions",None,["Momentum p = mv is conserved in every collision because the forces between the carts are equal and opposite (Newton's third law) and act for the same time. Kinetic energy is conserved only in elastic collisions. For two carts in one dimension: m₁u₁ + m₂u₂ = m₁v₁ + m₂v₂, plus either energy conservation (elastic) or v₁ = v₂ (perfectly inelastic).","Elastic, equal masses, one at rest: they exchange velocities. That is the billiard-ball result, and it is why a neutron slows best on hydrogen, whose nucleus has almost the same mass."]),
 'col':("The centre-of-mass frame",None,["Every one-dimensional collision is simplest in the frame moving with the centre of mass: total momentum is zero there, so an elastic collision just reverses each velocity and a perfectly inelastic one brings both to rest. Transform back and the lab-frame results follow. The coefficient of restitution e = (v₂ − v₁)/(u₁ − u₂) interpolates between e = 1 (elastic) and e = 0 (sticky).","Kinetic energy lost in a perfectly inelastic collision is ½μu² with μ the reduced mass m₁m₂/(m₁ + m₂): all the energy of relative motion, none of the centre-of-mass motion."]),
 'max':("Symmetry and conservation",None,["Momentum conservation is not an extra law; it is what translation symmetry of space implies (Noether). Energy conservation follows from time symmetry. In a collision the kinetic energy 'lost' is not lost but moved into internal degrees of freedom, and the accounting is exact only when those are included.","At relativistic speeds momentum is γmv and the same conservation holds; particle physics is the crash lab at 10¹² times the energy, with the same two laws doing the work."]),
}
CH[5]={
 'k5':("Round and round",None,["Newton imagined a cannon on a very tall mountain. Fire it gently and the ball falls to the ground nearby. Fire it harder and it lands farther away. Fire it hard enough and it falls all the way around the Earth and comes back. That is an <em>orbit</em>: falling forever and always missing.","Find the speed that makes the cannonball come back to the mountain."]),
 'g8':("Falling around the Earth",None,["An orbiting satellite is not floating. It is falling, at the same rate any dropped thing falls, but moving sideways so fast that the ground curves away beneath it as fast as it drops. Near Earth's surface that speed is about 7.9 kilometres per second, or 28,000 km/h.","Too slow and it comes down. Fast enough, about 11.2 km/s, and it never comes back at all: that is escape speed. The Moon is in the same kind of orbit, just far away and slow."]),
 'hs':("Circular motion and gravity",None,["A circular orbit needs a centripetal acceleration v²/r, supplied by gravity GM/r². Set them equal: v = √(GM/r), which at Earth's surface (r = 6,371 km) is 7.9 km/s. The period is 2πr/v ≈ 84 minutes at the surface, 90 minutes for the space station a few hundred kilometres up.","Escape speed comes from energy: ½v² = GM/r gives v = √(2GM/r) = √2 times circular speed. Between those two speeds the orbit is an ellipse; above escape, a hyperbola."]),
 'col':("Kepler from Newton",None,["The lab integrates Newton's law numerically; the exact solutions are conic sections. The vis-viva equation, v² = GM(2/r − 1/a), gives the speed anywhere on an orbit of semi-major axis a; circular orbits are a = r, escape is a → ∞. Kepler's third law, T² = 4π²a³/GM, follows and lets a period measure a mass.","Transfer between orbits uses the same equation twice: the Hohmann transfer is the ellipse tangent to both circles, and its two burns are the cheapest way to move between them."]),
 'max':("Orbits as geometry",None,["The inverse-square law is the only power law besides the harmonic oscillator with closed orbits (Bertrand), which is why planets retrace their paths and why the Rule Lab on the One Rule board matters here. The hidden Laplace–Runge–Lenz vector is the conserved quantity behind that closure.","Perturbations break it: Earth's oblateness precesses satellite orbits (used deliberately for Sun-synchronous orbits), the Moon raises tides that slow Earth's spin, and general relativity adds the 43″ per century of Mercury that the One Rule board simulates."]),
}
CH[6]={
 'k5':("Rockets",None,["A rocket does not push on the air. It throws gas out the back as hard as it can, and the gas pushes the rocket forward. That works in empty space too, which is why rockets are the only way to get there.","Reach 1,000 metres with the fuel you have. Then try for more."]),
 'g8':("Action and reaction",None,["Newton's third law: every push has an equal push back. The rocket pushes gas down; the gas pushes the rocket up. Thrust is how much gas per second times how fast it leaves. As fuel burns the rocket gets lighter, so it speeds up faster and faster.","Most of a rocket is fuel, and most of that fuel is spent lifting the rest of the fuel. Dropping empty tanks (staging) is the trick that makes orbit possible."]),
 'hs':("The rocket equation",None,["Thrust F = ṁ v_e: mass flow rate times exhaust speed. Integrate over the burn and you get Tsiolkovsky's equation, Δv = v_e ln(m₀/m₁): the speed gained depends on the exhaust speed and the logarithm of the mass ratio. Gravity subtracts g per second of burn, so burn fast.","The logarithm is the whole problem of spaceflight. To gain 2v_e you need a mass ratio of e² ≈ 7.4; to gain 3v_e, e³ ≈ 20. Staging resets the ratio by discarding dead mass."]),
 'col':("Optimising the climb",None,["Gravity loss and drag loss make the real Δv to orbit about 9.4 km/s against a 7.8 km/s orbital speed. Two stages with mass ratio e each give 2v_e with a structural fraction that a single stage of ratio e² could not achieve, since tanks and engines do not shrink to zero.","The lab integrates m(t)dv/dt = ṁ v_e − m(t)g with optional staging at burnout; try the same fuel in one stage and two, and compare altitude."]),
 'max':("Exponential cost",None,["Because Δv enters the mass ratio exponentially, every additional kilometre per second roughly doubles the vehicle. That is why chemical rockets top out near 4.5 km/s exhaust speed (hydrogen–oxygen), why high-Isp electric propulsion accepts tiny thrust, and why the only way past the exponential is to leave the reaction mass behind (tethers, beamed propulsion) or refuel in orbit.","The Oberth effect, gaining more energy per unit fuel when burning at high speed deep in a gravity well, is the rocket equation meeting the vis-viva equation of the previous chapter."]),
}
GROWN={
 1:"The mistake almost everyone makes: thinking motion needs a force. It does not; changing motion does. A push that ends does not stop the car; friction does.",
 2:"The hammer and feather video from Apollo 15 is real and two minutes long. Watch it together afterwards.",
 3:"Let kids fail at the target for a while before giving hints. The discovery that the mass slider does nothing is the point of the chapter.",
 4:"Toy cars or coins on a table reproduce the equal-mass swap. A coin slid into a resting coin stops dead.",
 5:"The idea that an orbit is falling and missing is the single most important sentence on the board.",
 6:"A balloon let go across the room is a rocket. Ask what it is pushing on. It is not the air.",
}
UNITS=[('m','metres'),('cm','centimetres'),('km','kilometres'),('s','seconds'),('min','minutes'),('m/s','metres per second'),('km/s','kilometres per second'),('m/s²','metres per second squared'),('N','newtons'),('kg','kilograms'),('kg·m/s','kilogram-metres per second'),('J','joules'),('n','a plain number')]
UNIT_WHY={'m':'metres measure a distance','cm':'centimetres measure a distance','km':'kilometres measure a distance','s':'seconds measure a time','min':'minutes measure a time','m/s':'metres per second is a speed','km/s':'kilometres per second is a speed','m/s²':'metres per second squared is how fast speed changes','N':'newtons measure a force, a push or pull','kg':'kilograms measure mass','kg·m/s':'kilogram-metres per second is momentum: mass times speed','J':'joules measure energy','n':'a ratio, no unit'}
CHECK={
 1:{'k5':("You push a wagon with 20 newtons and your friend pulls it the same way with 10 newtons. Total push?",30,'N',.02,"Pushes in the same direction add.","Right. 30 N."),
    'g8':("A 2 kg cart gets a net push of 6 N. How fast does its speed change each second?",3,'m/s²',.02,"Acceleration = force ÷ mass.","Right. 3 m/s², every second."),
    'hs':("A 4 kg cart slides on a floor with μ = 0.25. How big is the friction force? (g = 9.8)",9.8,'N',.03,"f = μ m g.","Right. 0.25 × 4 × 9.8 = 9.8 N."),
    'col':("A cart at 6 m/s slides to a stop on μ = 0.3. Stopping distance? (g = 9.8)",6.12,'m',.04,"d = v²/(2μg).","Right. 36 ÷ (2 × 0.3 × 9.8) ≈ 6.1 m, for any mass."),
    'max':("On a train at a steady 30 m/s, a 2 kg cart is pushed with 10 N. Its acceleration relative to the train?",5,'m/s²',.02,"Galilean invariance: the train's speed does not enter.","Right. 5 m/s², same as on the ground.")},
 2:{'k5':("On the Moon with no air, the hammer takes 2 seconds to fall. How long does the feather take?",2,'s',.02,"They fall the same.","Right. 2 seconds, together."),
    'g8':("Something falls for 3 seconds on Earth with no air. How fast is it going? (9.8 m/s faster each second)",29.4,'m/s',.03,"Speed = 9.8 × seconds.","Right. About 29 m/s."),
    'hs':("Fall time from 20 m with no air? (g = 9.8)",2.02,'s',.03,"t = √(2h/g).","Right. About 2.0 s."),
    'col':("Terminal velocity of a 1 kg object with drag ½ρC_dA = 0.2 kg/m? (g = 9.8)",7,'m/s',.03,"v_t = √(mg / 0.2).","Right. √49 = 7 m/s."),
    'max':("Fall time from 20 m on Jupiter, g = 24.8 m/s²?",1.27,'s',.03,"t = √(2h/g).","Right. About 1.3 s.")},
 3:{'k5':("The car leaves the ramp going 5 m/s sideways and flies for 2 seconds. How far from the ramp does it land?",10,'m',.02,"Sideways distance = sideways speed × time.","Right. 10 m."),
    'g8':("A car rolls down from 4.9 m with no friction. Speed at the bottom? (v = √(2gh), g = 9.8)",9.8,'m/s',.03,"2 × 9.8 × 4.9 = 96, and √96 ≈ 9.8.","Right. About 9.8 m/s, whatever the mass."),
    'hs':("Launched at 10 m/s at 45° from ground level. Range? (g = 9.8)",10.2,'m',.03,"R = v² sin(2θ)/g.","Right. 100 ÷ 9.8 ≈ 10.2 m."),
    'col':("Launch height 1 m, 12 m/s at 30°. Flight time? (g = 9.8)",1.37,'s',.05,"Solve 1 + 6t − 4.9t² = 0.","Right. About 1.37 s."),
    'max':("A solid cylinder rolls (not slides) down 3 m without slipping. Speed at the bottom? (v = √(4gh/3))",6.26,'m/s',.03,"Rotational energy takes a third.","Right. About 6.3 m/s, less than √(2gh) = 7.7.")},
 4:{'k5':("A 2 kg cart moves at 3 m/s. Its momentum is mass × speed = ?",6,'kg·m/s',.02,"Multiply.","Right. 6 kg·m/s."),
    'g8':("5 kg at 2 m/s hits 5 kg at rest and they stick. Shared speed?",1,'m/s',.02,"Total momentum 10, total mass 10.","Right. 1 m/s."),
    'hs':("2 kg at 4 m/s sticks to 6 kg at rest. Final speed?",1,'m/s',.02,"8 kg·m/s shared by 8 kg.","Right. 1 m/s."),
    'col':("Elastic collision, equal masses, cart 1 at 3 m/s hits cart 2 at rest. Cart 2's speed after?",3,'m/s',.02,"They exchange velocities.","Right. 3 m/s, and cart 1 stops."),
    'max':("Perfectly inelastic collision of equal masses, one at rest. Fraction of kinetic energy lost?",0.5,'n',.02,"½μu² over ½mu² with μ = m/2.","Right. Half.")},
 5:{'k5':("Read it from the lab: what speed makes the cannonball come all the way round?",7.9,'km/s',.05,"Just under 8 km/s.","Right. About 7.9 km/s: falling and always missing."),
    'g8':("Circular orbit speed at Earth's surface?",7.9,'km/s',.05,"√(gR) with R = 6,371 km.","Right. About 7.9 km/s."),
    'hs':("Escape speed at Earth's surface? (√2 × circular)",11.2,'km/s',.03,"7.9 × 1.414.","Right. About 11.2 km/s."),
    'col':("Orbital period at the surface: 2πR/v with R = 6,371 km, v = 7.9 km/s. In minutes?",84,'min',.04,"40,030 km ÷ 7.9 km/s ÷ 60.","Right. About 84 minutes."),
    'max':("Circular speed at r = 2R? (v ∝ 1/√r)",5.6,'km/s',.04,"7.9 ÷ √2.","Right. About 5.6 km/s.")},
 6:{'k5':("A rocket throws out 2 kg of gas every second at 100 m/s. Its thrust?",200,'N',.02,"Thrust = kilograms per second × speed.","Right. 200 N."),
    'g8':("5 kg/s of gas at 400 m/s. Thrust?",2000,'N',.02,"ṁ × v_e.","Right. 2,000 N."),
    'hs':("Exhaust speed 2,000 m/s and mass ratio m₀/m₁ = e ≈ 2.718. Δv?",2000,'m/s',.02,"ln(e) = 1.","Right. 2,000 m/s: one exhaust speed."),
    'col':("v_e = 3,000 m/s, mass ratio 7.39. Δv?",6000,'m/s',.02,"ln(7.39) = 2.","Right. 6,000 m/s."),
    'max':("Two stages of mass ratio e each versus one stage of ratio e², same v_e. Ratio of the Δv's?",1,'n',.02,"ln adds: 1 + 1 = 2.","Right. Equal in the ideal case; staging wins only because real tanks have mass.")},
}
FIG={
 1:'''<div class="panel"><canvas id="cv-push" aria-label="A car on a floor with a target box. Press and hold behind the car to push it, in front to pull it."></canvas></div>
    <div class="controls"><label class="slider">Push strength <input type="range" id="ps-f" min="10" max="300" step="10" value="80"><span class="val" id="ps-f-val">80 N</span></label><label class="slider">Car mass <input type="range" id="ps-m" min="1" max="20" step="1" value="5"><span class="val" id="ps-m-val">5 kg</span></label><label class="slider">Floor roughness <input type="range" id="ps-mu" min="0.02" max="0.6" step="0.02" value="0.2"><span class="val" id="ps-mu-val">0.20</span></label><button class="btn" id="ps-reset">New box</button></div>
    <figcaption><b>Try this:</b> press and hold on the floor: the car is pushed away from where you press. Stop it inside the box. Then make the floor icy and try again.</figcaption>''',
 2:'''<div class="panel"><canvas id="cv-fall" aria-label="A hammer and a feather dropped from a tower, with air on or off, on a chosen world."></canvas></div>
    <div class="controls"><button class="btn primary" id="fl-drop">Drop</button><button class="btn is-on" id="fl-air" aria-pressed="true">Air: on</button><span class="lbl">World</span><button class="btn is-on" data-g="9.8">Earth</button><button class="btn" data-g="1.62">Moon</button><button class="btn" data-g="3.71">Mars</button><button class="btn" data-g="24.8">Jupiter</button></div>
    <figcaption><b>Try this:</b> drop them with air, then without. Then change worlds and watch the fall times.</figcaption>''',
 3:'''<div class="panel"><canvas id="cv-launch" aria-label="A car rolls down a ramp and flies off the lip toward a target box. Sliders set ramp height, lip angle, mass, and air."></canvas></div>
    <div class="controls"><button class="btn primary" id="ln-go">Launch</button><label class="slider">Ramp height <input type="range" id="ln-h" min="1.5" max="9" step="0.1" value="4"><span class="val" id="ln-h-val">4.0 m</span></label><label class="slider">Lip angle <input type="range" id="ln-a" min="0" max="60" step="1" value="20"><span class="val" id="ln-a-val">20°</span></label><label class="slider">Mass <input type="range" id="ln-m" min="0.2" max="5" step="0.1" value="1"><span class="val" id="ln-m-val">1.0 kg</span></label><button class="btn" id="ln-air" aria-pressed="false">Air: off</button><label class="slider" data-lv="hs col max">Ramp friction <input type="range" id="ln-mu" min="0" max="0.3" step="0.01" value="0"><span class="val" id="ln-mu-val">0.00</span></label><label class="slider" data-lv="hs col max">I predict <input type="number" id="ln-pred" step="0.1" min="0" placeholder="m" style="width:5rem"> m</label><button class="btn" id="ln-newt">New target</button></div>
    <figcaption><b>Try this:</b> hit the box. Each hit moves it farther. Change the mass and notice what does not change. <span data-lv="hs col max">Type a prediction before you launch; the lab scores your error.</span></figcaption>''',
 4:'''<div class="panel"><canvas id="cv-crash" aria-label="Two carts on a track that collide. Sliders set masses and speeds; a toggle sets bouncy or sticky."></canvas></div>
    <div class="controls"><button class="btn primary" id="cr-go">Roll</button><label class="slider">Cart 1 mass <input type="range" id="cr-m1" min="1" max="10" step="0.5" value="2"><span class="val" id="cr-m1-val">2 kg</span></label><label class="slider">Cart 1 speed <input type="range" id="cr-v1" min="0.5" max="6" step="0.5" value="3"><span class="val" id="cr-v1-val">3 m/s</span></label><label class="slider">Cart 2 mass <input type="range" id="cr-m2" min="1" max="10" step="0.5" value="2"><span class="val" id="cr-m2-val">2 kg</span></label><label class="slider">Cart 2 speed <input type="range" id="cr-v2" min="-4" max="4" step="0.5" value="0"><span class="val" id="cr-v2-val">0 m/s</span></label><button class="btn is-on" id="cr-type" aria-pressed="true">Bouncy</button></div>
    <figcaption><b>Try this:</b> make the moving cart stop dead. Then make them stick and read the shared speed. Watch the total momentum before and after.</figcaption>''',
 5:'''<div class="panel"><canvas id="cv-cannon" aria-label="Newton's cannon on a mountain on a small planet. A slider sets the launch speed; shots fall, orbit, or escape."></canvas></div>
    <div class="controls"><button class="btn primary" id="cn-fire">Fire</button><label class="slider">Launch speed <input type="range" id="cn-v" min="1" max="12" step="0.1" value="5"><span class="val" id="cn-v-val">5.0 km/s</span></label><button class="btn" id="cn-clear">Clear shots</button></div>
    <figcaption><b>Try this:</b> fire faster and faster. Find the speed where the ball comes back to the mountain, then the speed where it never comes back.</figcaption>''',
 6:'''<div class="panel"><canvas id="cv-rocket" aria-label="A rocket launch with altitude and speed readouts. Sliders set fuel, exhaust speed, and burn rate; a toggle adds a second stage."></canvas></div>
    <div class="controls"><button class="btn primary" id="rk-go">Launch</button><label class="slider">Fuel <input type="range" id="rk-fuel" min="0.5" max="10" step="0.5" value="3"><span class="val" id="rk-fuel-val">3 kg</span></label><label class="slider">Exhaust speed <input type="range" id="rk-ve" min="100" max="600" step="50" value="300"><span class="val" id="rk-ve-val">300 m/s</span></label><label class="slider">Burn rate <input type="range" id="rk-mdot" min="0.5" max="5" step="0.5" value="1"><span class="val" id="rk-mdot-val">1 kg/s</span></label><button class="btn" id="rk-stage" data-lv="hs col max" aria-pressed="false">Two stages: off</button></div>
    <figcaption><b>Try this:</b> reach 1,000 m. Then find the fastest burn, then the highest flight the fuel allows. <span data-lv="hs col max">Then split the same fuel into two stages and compare.</span></figcaption>''',
}
ALL=['k5','g8','hs','col','max']
MISSIONS=[
 ('l1','ch1',ALL,"Stop the car inside the box."),
 ('l1b','ch1',['g8','hs','col','max'],"Make the floor icy (roughness under 0.05) and stop it in the box anyway."),
 ('l2','ch2',ALL,"Turn the air off and drop both: they land together."),
 ('l2b','ch2',['g8','hs','col','max'],"Drop on the Moon and read the fall time."),
 ('l3','ch3',ALL,"Hit the target."),
 ('l3b','ch3',['g8','hs','col','max'],"Hit three targets in a row."),
 ('l3c','ch3',['hs','col','max'],"Predict the landing spot within 5% before launching."),
 ('l3d','ch3',['col','max'],"Turn the air on and hit a target with a mass of 3 kg or more."),
 ('l4','ch4',ALL,"Make the moving cart stop dead."),
 ('l4b','ch4',['g8','hs','col','max'],"Make the carts stick and read the shared speed."),
 ('l5','ch5',ALL,"Put the cannonball into orbit."),
 ('l5b','ch5',['hs','col','max'],"Fire it fast enough to escape."),
 ('l6','ch6',ALL,"Reach 1,000 m."),
 ('l6b','ch6',['g8','hs','col','max'],"Reach 3,000 m."),
 ('l6c','ch6',['hs','col','max'],"Stage the rocket and beat your best single-stage altitude."),
]+[(f'tb{n}',f'ch{n}',ALL,"Teach it back: answer the check question below with the right unit.") for n in range(1,7)]
CLOSING=("Everything that moves obeys three sentences.","A push changes motion. Everything falls the same. Every push has a push back. Newton wrote them in 1687, and every game on this board is those sentences keeping score.")
