KEY='history'
TITLE='How History Survives'
FAVICON='📜'
DESC="How the past reaches us and how we keep it: scribes and their errors, family trees of manuscripts, decoding a dead script, the carbon clock, rotting bits, and the biased sample that survives."
EYEBROW="The science of keeping the past"
TRAIL=[('top','Start'),('ch1','1 · The copying game'),('ch2','2 · Family trees of books'),('ch3','3 · Reading a dead language'),('ch4','4 · How old is it?'),('ch5','5 · Bits rot too'),('ch6','6 · What survives')]
HERO={
 'k5':"Every old story, every ancient book, every fact about the past had to survive fires, floods, wars, and two thousand years of people copying it by hand. This is how we know what we know, and how you can help keep it.",
 'g8':"Almost everything we know about the past reached us as copies of copies, and most of it did not survive at all. This page shows the tricks that preserve knowledge and the detective work that recovers it: scribes and their errors, family trees of manuscripts, decoding dead scripts, dating the past, and the surprisingly fragile world of digital files.",
 'hs':"Textual transmission, stemmatics, decipherment, radiometric dating, and digital preservation are five different sciences with one goal: getting reliable information across time. Each has a signal, a noise source, and a method for telling them apart. This page treats them that way, with a simulation for each.",
 'col':"Transmission of texts as a noisy channel: error models for scribal copying, Lachmannian stemmatics and its phylogenetic successors, decipherment as constrained cryptanalysis, radiocarbon dating with calibration, digital preservation as an error-correction and format-migration problem, and the selection bias that shapes what survives at all.",
 'max':"Philology met information theory late. This page traces the parallels: Maas's stemmatics as tree reconstruction now handled with phylogenetic methods, Kober and Ventris on Linear B as combinatorial constraint propagation, Libby's radiocarbon method with Bayesian calibration, Hamming and Reed–Solomon codes in archival storage, and the survivorship problem in the historical record.",
}
CH={}
CH[1]={
 'k5':("The copying game",None,["Before printing, every book was copied by hand. Copying is hard. Eyes skip a line, one letter looks like another, a tired hand writes a word twice. Each copy has a few new mistakes, and the next copier copies the mistakes too.","After a hundred years the story has drifted. Press the button and watch a sentence drift."]),
 'g8':("The copying game",None,["Scribal errors have names. Haplography: writing once what should be written twice. Dittography: the opposite. The eye-skip: jumping from one word to the same word later and dropping everything in between.","Because each copy inherits the errors of its parent, mistakes pile up at a fairly steady rate. That steadiness is what lets scholars work backward. Compare two scribes: the mistakes they share must have been in their common parent."]),
 'hs':("Copying as a noisy channel",None,["Model each copy as a channel with an error rate per word. After g generations the expected fraction of altered words grows roughly as 1 − (1 − p)^g. Errors are not uniform: similar letters, repeated words and line ends are hot spots.","The key fact for reconstruction is inheritance: a copy carries its parent's errors plus its own. Two independent lineages share exactly the errors that predate their split, and nothing else, apart from rare coincidences."]),
 'col':("Error models",None,["Textual criticism treats a tradition as a branching process with mutation. Substitution, deletion (haplography, homoeoteleuton), insertion (dittography, gloss intrusion) and transposition have different rates and different detectability. Conjunctive errors, shared innovations, are the informative signal; separative errors distinguish branches.","Contamination, a scribe consulting more than one exemplar, breaks the tree model, which is why real traditions are often networks rather than trees."]),
 'max':("Philology as phylogenetics",None,["The formal analogy is to molecular phylogenetics: witnesses as taxa, variant readings as characters, shared innovations as synapomorphies. Maximum parsimony and Bayesian methods (Barbrook, Howe et al., Nature 1998, on the Canterbury Tales) reconstruct stemmata but must handle horizontal transmission with network methods.","Error models are asymmetric: the principle of lectio difficilior encodes a prior that scribes simplify. Chance coincidence of errors (polygenesis) sets a noise floor for conjunctive evidence."]),
}
CH[2]={
 'k5':("Family trees of books",None,["Suppose you have five old copies of the same story and they don't quite agree. Which one is right?","Trick: look for shared mistakes. If two copies have the same odd mistake, they were probably copied from the same parent. Draw the family tree, and the original is what the oldest branches agree on. Careful: three copies can all be wrong together if they came from one bad parent."]),
 'g8':("Family trees of books",None,["This is called stemmatics, from <em>stemma</em>, Latin for family tree. Scholars compare every copy of a text word by word, note where they differ, and group copies by the errors they share. A mistake shared by two copies almost never happens twice by accident, so it points to a common ancestor.","The tree tells you which readings go back to the lost original. It is branches you count, not manuscripts: three copies of one bad parent are one vote, not three."]),
 'hs':("Lachmann's method","1850s",["Collect all witnesses, collate them, eliminate copies of surviving manuscripts, group the rest by shared errors, and reconstruct the archetype by choosing at each variant the reading supported by independent branches.","Where branches split evenly, weigh the readings: the harder reading is usually original (lectio difficilior), since scribes simplify. The reconstruction is a hypothesis with an error bar, not a photograph of the original."]),
 'col':("Trees, networks, and Bédier's objection",None,["The method assumes a tree; real traditions have contamination. Bédier's 1928 observation that most published stemmata are bifid suggests a bias in the method itself. Modern approaches borrow from phylogenetics: parsimony, maximum likelihood, and split networks such as NeighborNet that display conflicting signal instead of hiding it.","The archetype is the latest common ancestor of the surviving witnesses, not the author's autograph, and may itself be corrupt."]),
 'max':("Open problems in stemmatics",None,["Distinguishing contamination from polygenesis; rooting the tree without an outgroup, where direction of change is inferred from scribal tendencies; and weighting characters when variants are not independent, since a scribe who modernizes spelling does so everywhere.","Bayesian phylogenetic tools with text-critical substitution models are current practice; the Canterbury Tales Project and the Editio Critica Maior of the Greek New Testament, using the Coherence-Based Genealogical Method, are the large-scale cases."]),
}
CH[3]={
 'k5':("Reading a dead language","Champollion, 1822",["For 1,400 years nobody could read Egyptian hieroglyphs. Then in 1799 soldiers found a stone with the same message written three times: in hieroglyphs, in another Egyptian script, and in Greek. People could read Greek.","Kings' names were written inside ovals. Jean-François Champollion matched the name <em>Ptolemy</em> letter by letter. Once you know a few letters, the rest starts to fall out. Try it."]),
 'g8':("Reading a dead language","Champollion, 1822",["The Rosetta Stone (196 BC) carries one decree in three scripts. Champollion used the royal names in cartouches, Ptolemy and Cleopatra, to pin down the sound values of individual signs, then checked them against Coptic, a late descendant of Egyptian still used in church services.","Decipherment is a chain: a known text, a few anchors, then constraints spreading outward until the whole system clicks."]),
 'hs':("Decipherment",None,["Decipherment needs three things: enough text, a way in (a bilingual or known names), and the right guess about what kind of script it is: alphabet, syllabary, or logographic.","Linear B, deciphered by Michael Ventris in 1952 building on Alice Kober's grid analysis, had no bilingual at all. Kober found sign patterns that showed inflection; Ventris's grid of shared consonants and vowels turned out to be Greek. Some scripts remain unread, Linear A, the Indus script, Rongorongo, because one of the three things is missing."]),
 'col':("Constraint propagation",None,["Kober treated the script as a combinatorial object: signs that alternate in the same position across word forms share a consonant or a vowel, which yields a grid independent of any language assumption. Ventris's leap was to test Greek against the grid; place names such as ko-no-so (Knossos) fell out.","Contrast Champollion's use of a bilingual with Ventris's purely internal method, and note that Maya decipherment (Knorozov 1952, later Coe and Stuart) required abandoning the alphabet assumption for a mixed logosyllabic one."]),
 'max':("Why some scripts stay unread",None,["Linear A: a few thousand signs, no bilingual, unknown language. Indus: inscriptions average five signs, too short for statistical structure; the Farmer–Sproat–Witzel argument that it may not encode language at all is contested by entropy analyses (Rao et al. 2009). Rongorongo: a tiny corpus.","Decipherment as cryptanalysis: known-plaintext attacks (bilinguals), frequency analysis, and the unicity distance set a floor on corpus size. Machine decipherment (Snyder, Barzilay and Knight 2010 on Ugaritic) reproduces Ventris-style constraint propagation at scale."]),
}
CH[4]={
 'k5':("How old is it?",None,["How do we know how old something is? Trees add one ring a year, so count the rings.","For bones and wood there is a clock inside: a special kind of carbon that slowly disappears. Every 5,730 years, half of it is gone. Measure how much is left and you can work out how long ago the tree or animal died."]),
 'g8':("How old is it?",None,["Radiocarbon dating: living things take in carbon-14 from the air. When they die, no more comes in and what is there decays with a half-life of 5,730 years. After one half-life, half is left; after two, a quarter. Measure the fraction and read off the age.","It works back to about 50,000 years. Tree rings, ice layers, and layers of lake mud give year-by-year records used to check and correct it."]),
 'hs':("Radiocarbon and calibration",None,["N(t) = N₀ (½)^(t/5730), so t = 5730 · log₂(N₀/N). The trouble is N₀: the amount of ¹⁴C in the air has varied with solar activity and Earth's magnetic field, so raw radiocarbon years are calibrated against tree-ring sequences and other annual records, the IntCal curve, which now reaches back 55,000 years.","A measurement of 25% remaining gives 11,460 radiocarbon years, and calibration turns that into a calendar-year range."]),
 'col':("Clocks and their error bars",None,["Accelerator mass spectrometry counts ¹⁴C atoms directly and needs milligrams rather than grams. Calibration is a Bayesian problem: the likelihood of a measurement given a calendar date, times the curve, gives a posterior that can be multimodal when the curve has plateaus; the Hallstatt plateau, 800 to 400 BC, is nearly undatable by ¹⁴C alone. Ordered sequences of samples sharpen the posterior enormously (OxCal, BCal).","Other clocks: K–Ar and Ar–Ar for volcanic layers, uranium series for cave formations, luminescence for the burial date of sediment, and dendrochronology for absolute years."]),
 'max':("Single-year anchors",None,["The Miyake events (774/775 and 993/994 AD), sharp ¹⁴C spikes from extreme solar particle storms, give single-year anchors: matching a spike in a wood sample to the tree-ring record dates it to the year, which fixed the Norse presence at L'Anse aux Meadows to 1021 AD (Kuitems et al. 2021).","Reservoir effects, marine and freshwater, bias dates by centuries and must be corrected. IntCal20 integrates tree rings, speleothems and marine records with a Bayesian spline, and its uncertainty structure propagates into every archaeological chronology built on it."]),
}
CH[5]={
 'k5':("Bits rot too",None,["You might think computer files last forever. They don't. Discs wear out, tiny errors creep in, and old files stop opening because nobody has the program any more.","The fix is the scribes' trick: make copies, keep them in different places, and check them against each other. Turn on the copies and watch the picture heal."]),
 'g8':("Bits rot too",None,["Digital files fail in two ways. Bit rot: individual bits flip over time. Format death: the file is fine but nothing can read it (try opening a 1990 word-processor file). Libraries fight both with copies (Lots Of Copies Keep Stuff Safe is a real program called LOCKSS), checksums that reveal when a copy has changed, and migrating files to new formats before the old ones die."]),
 'hs':("Redundancy and error correction",None,["Redundancy fixes errors only if you can tell which copy is right. Three copies with majority voting fix any single flip. Error-correcting codes do better: a Hamming code adds a few check bits to a block and can locate and fix one flipped bit in it. Checksums detect corruption; codes correct it.","Archival practice: at least three copies, two media types, one off-site, and fixity checks on a schedule."]),
 'col':("Storage as a noisy channel",None,["Shannon's theorem says reliable storage is possible up to the channel's capacity with suitable codes. Reed–Solomon codes correct bursts (CDs, QR codes, RAID 6); LDPC codes approach capacity in modern SSDs. The harder problems are semantic: formats, dependencies, and context.","The Digital Dark Age argument: the 1086 Domesday Book is readable; the 1986 BBC Domesday Project on laserdisc needed an emulation rescue by 2002. Preservation means preserving the ability to interpret bits, not the bits alone."]),
 'max':("Open engineering questions",None,["Media longevity (tape around 30 years, optical archival discs claiming centuries, DNA storage with error-correcting encodings), format obsolescence handled by emulation versus migration (the Rothenberg–Bearman debate), and provenance (PREMIS metadata, the OAIS reference model).","The selection problem dominates: the Internet Archive captures a sample, not the web. What is not crawled, not copied, or not funded is gone. Same as papyrus, faster."]),
}
CH[6]={
 'k5':("What survives, and who decides",None,["Here is the strangest part. What we know about the past is mostly what people bothered to copy. Kings' laws and holy books were copied many times, so they survived. Shopping lists, jokes, and letters from ordinary people usually were not. So the past looks more serious than it was.","Sometimes we get lucky. A rubbish dump in Egypt, kept dry by the desert, gave us thousands of ordinary letters, school homework, and a complaint about a bad delivery of fish."]),
 'g8':("What survives, and who decides",None,["This is survivorship bias. The record is not a sample of the past; it is a sample of what got copied, stored in dry places, or written on durable material. The Oxyrhynchus rubbish heaps, excavated from 1896, preserved half a million papyrus fragments of everyday life. The Cairo Geniza preserved a thousand years of a Jewish community's letters because they did not throw away paper with God's name on it.","Historians correct for bias by asking: what would have been written, and why would it be gone?"]),
 'hs':("Survivorship bias",None,["Of roughly 800 known ancient Greek authors, substantial texts survive from fewer than 150, and the losses at Alexandria were gradual, budget cuts, fires and neglect, rather than one dramatic burning. Survival depends on copying demand (school texts survive), material (papyrus rots except in deserts), and institutional continuity (monasteries).","The simulation gives each kind of document a survival probability per century that rises with how often it is copied, and shows the resulting skew."]),
 'col':("Estimating what is missing",None,["The surviving record is a biased sample whose inclusion probability depends on the very attributes historians study: genre, language, class of author. Corrections resemble capture–recapture and unseen-species estimation. Kestemont et al. (Science 2022) applied unseen-species models to medieval chivalric romances and estimated that about 9% of manuscripts and 32% of works survive, with strong regional differences.","Geniza and rubbish-dump finds act as approximately random samples against which to calibrate the biased ones."]),
 'max':("The bias of the future's past",None,["The survivorship problem links Collingwood's inference from evidence to the statistics of unseen species (Good–Turing, Chao1). Digital archives invert the bias: the record is vast but shallow, and the decisive filters are crawling policy, platform death, and link rot; about half the URLs cited in US Supreme Court opinions are dead.","The preservation frontier is choosing what to keep under budget constraints and documenting that choice, so future historians can model our bias as we model the monks'."]),
}
GROWN={
 1:"The 'telephone game' is the right mental model, with one difference: written copies keep the errors permanently, so they add up instead of resetting.",
 2:"The lesson children find surprising is that the majority can be wrong: three copies of one bad parent are still one bad parent.",
 3:"The puzzle is a substitution cipher with a known name as the key, which is genuinely how Champollion started. The Kids level allows hints.",
 4:"Half-life is the idea to land: after each 5,730 years, half of what is left disappears, so 'how much is left' tells you 'how long'.",
 5:"Kids assume digital means permanent. The picture healing when copies are switched on is the point; the reasons files die of old age are for later.",
 6:"The rubbish dump is real: Oxyrhynchus, Egypt. Ordinary life survived there precisely because nobody thought it was worth keeping.",
}
FIG={
 1:'''<div class="panel"><canvas id="cv-copy" aria-label="A sentence copied by hand again and again, with mistakes piling up."></canvas></div>
    <div class="controls"><button class="btn" id="copy-again">Copy it again</button><button class="btn blue" id="copy-two" data-lv="g8 hs col max" aria-pressed="false">Two scribes</button><button class="btn" id="copy-reset">Start over</button></div>
    <figcaption><b>Try this:</b> copy the line again and again and watch the words drift. <span data-lv="g8 hs col max">Switch on two scribes: a mistake they share was already in their parent copy.</span></figcaption>''',
 2:'''<div class="panel"><canvas id="cv-stemma" aria-label="A family tree of five manuscripts. Tap each to read it, then decide which reading is original."></canvas></div>
    <div class="controls"><span class="lbl">cows or crows?</span><button class="btn" data-st="q1" data-ans="crows">crows</button><button class="btn" data-st="q1" data-ans="cows">cows</button><span class="sep"></span><span class="lbl">temple or tempel?</span><button class="btn" data-st="q2" data-ans="tempel">tempel</button><button class="btn" data-st="q2" data-ans="temple">temple</button></div>
    <figcaption><b>Try this:</b> tap each manuscript to read it. Then decide which reading is original. Count branches, not copies.</figcaption>''',
 3:'''<div class="panel"><canvas id="cv-decode" aria-label="An inscription in unknown symbols with a royal name in a box. Tap a symbol, then a letter, to decode it."></canvas></div>
    <div class="controls"><button class="btn" id="dec-name">Use the king's name</button><button class="btn" id="dec-hint" data-lv="k5 g8">Give me a letter</button><button class="btn" id="dec-reset">Start over</button></div>
    <div class="keys" id="dec-keys"></div>
    <figcaption><b>Try this:</b> the name in the box is PTOLEMY. Tap a symbol, then the letter you think it is. <span data-lv="hs col max">No hints at this level: the name alone is enough.</span></figcaption>''',
 4:'''<div class="panel"><canvas id="cv-date" aria-label="A decay curve for carbon-14 with a slider for how much is left, and a tree cross-section with rings to count."></canvas></div>
    <div class="controls"><label class="slider">Carbon-14 left <input type="range" id="c14" min="1" max="100" step="1" value="50"><span class="val" id="c14-val">50%</span></label><span class="sep"></span><label class="slider" data-lv="g8 hs col max">Rings you counted <input type="number" id="rings" min="1" max="60" value="10" style="width:4.5rem"></label><button class="btn" id="rings-check" data-lv="g8 hs col max">Check</button></div>
    <figcaption><b>Try this:</b> slide the carbon-14 down and read the age. <span data-lv="g8 hs col max">Then count the rings on the trunk and check your answer.</span></figcaption>''',
 5:'''<div class="panel"><canvas id="cv-bits" aria-label="A pixel picture kept in storage for many years, with protection toggles for copies and an error-correcting code."></canvas></div>
    <div class="controls"><label class="slider">Years in storage <input type="range" id="bits-years" min="0" max="200" step="1" value="0"><span class="val" id="bits-years-val">0</span></label><button class="btn" id="bits-copies" aria-pressed="false">Three copies + voting: off</button><button class="btn" id="bits-ecc" data-lv="hs col max" aria-pressed="false">Error-correcting code: off</button><button class="btn" id="bits-migrate">Migrate the format</button></div>
    <figcaption><b>Try this:</b> run the years forward and watch the picture rot. Turn on copies with voting and it heals. <span data-lv="g8 hs col max">At year 120 the format dies: migrate it or lose the file.</span></figcaption>''',
 6:'''<div class="panel"><canvas id="cv-survive" aria-label="Two hundred documents of different kinds surviving or vanishing over twenty centuries."></canvas></div>
    <div class="controls"><label class="slider">Centuries <input type="range" id="surv-c" min="0" max="20" step="1" value="0"><span class="val" id="surv-c-val">0</span></label><button class="btn" id="surv-dig">Dig up the rubbish dump</button><button class="btn" id="surv-reset">New archive</button></div>
    <figcaption><b>Try this:</b> run the centuries and watch which kinds of writing survive. Then dig up the dump.</figcaption>''',
}
ALL=['k5','g8','hs','col','max']
MISSIONS=[
 ('h1','ch1',ALL,"Copy the line at least 10 times and find the first word that changed."),
 ('h1b','ch1',['g8','hs','col','max'],"Switch on two scribes and find a mistake they share."),
 ('h2','ch2',ALL,"Pick the original reading in both cases using the family tree."),
 ('h3','ch3',ALL,"Decode the whole inscription."),
 ('h3b','ch3',['hs','col','max'],"Decode it from the king's name alone, with no extra hints."),
 ('h4','ch4',ALL,"Find the age of a sample with 25% of its carbon-14 left."),
 ('h4b','ch4',['g8','hs','col','max'],"Count the tree rings correctly."),
 ('h5','ch5',ALL,"Reach 200 years with fewer than 3 bad pixels."),
 ('h5b','ch5',['hs','col','max'],"Run 200 years with only the code on and note how many bad pixels get through."),
 ('h5c','ch5',['g8','hs','col','max'],"Migrate the format before the file dies at year 120."),
 ('h6','ch6',ALL,"Run 20 centuries and see which kind of writing survives."),
 ('h6b','ch6',ALL,"Dig up the rubbish dump."),
]
CLOSING=("The past is not stored. It is re-copied.","Every generation decides, mostly by accident, what the next one gets to know. Copy something today.")
