KEY='heat'
TITLE='Hot Side, Cold Side'
FAVICON='🔥'
DESC="Heat differences into electricity: heat flowing between blocks, boiling a pot, stoking a wood stove, pulling a temperature difference off anything from a campfire to your hand, the Carnot limit, matching the load, and building a whole heat-power system."
EYEBROW="Thermoelectric power, K to 12"
TRAIL=[('top','Start'),('ch1','1 · Heat flows downhill'),('ch2','2 · Boiling water'),('ch3','3 · The wood fire'),('ch4','4 · Hot side, cold side'),('ch5','5 · Why only five percent'),('ch6','6 · Match the load'),('ch7','7 · Build a heat-power system'),('ch8','8 · Blackout')]
HERO={
 'k5':"A fire is warm. A snowbank is cold. Put something between them that likes a difference, and you get electricity, with no moving parts at all. This board is about that trick: where heat goes, what it takes to boil a pot, how to keep a fire just right, and how to squeeze watts out of a hot side and a cold side.",
 'g8':"Heat always flows from hot to cold. A thermoelectric module is a slab that turns some of that flow into electricity while it passes through, which is why a wood stove, a camp fire, a pot of water, or even your hand can power something. Seven games: from heat flowing between two blocks to a full system that charges a phone from a stove and warms your water with the leftover.",
 'hs':"Conduction, specific and latent heat, combustion power, the Seebeck effect, the Carnot limit and the thermoelectric figure of merit ZT, maximum power transfer, and a system design that budgets watts, temperatures and time. Every game is scored by the real equations, and every number comes with its unit.",
 'col':"Thermal resistance networks from source to sink, energy balances on stoves and pots, the coupled Seebeck–Fourier description of a module, efficiency as Carnot times a ZT-dependent factor, impedance matching to a load and to a boost converter, and combined heat and power as a design problem rather than a gadget.",
 'max':"Thermoelectrics as coupled transport: Onsager symmetry between the Seebeck and Peltier coefficients, ZT as the single dimensionless number that bounds efficiency, why ZT ≈ 1 has been the wall for seventy years, and what the phonon-glass electron-crystal idea does about it. Plus the engineering that decides real output: interface resistance, sink design, and cold-side runaway.",
}
STANDARDS={1:"K-PS3-1, 4-PS3-2, MS-PS3-4, HS-PS3-4",2:"4-PS3-2, MS-PS3-4, HS-PS3-1",3:"MS-PS1-6, MS-PS3-3, HS-PS1-4",4:"4-PS3-4, MS-PS3-3, HS-PS3-3",5:"MS-PS3-5, HS-PS3-4",6:"HS-PS3-3, HS-ETS1-3",7:"4-PS3-4, MS-ETS1-2, HS-ETS1-2, HS-ETS1-3",8:"4-PS3-4, MS-PS3-3, MS-ETS1-4, HS-PS3-3, HS-ETS1-3"}
CH={}
CH[1]={
 'k5':("Heat flows downhill",None,["Touch a hot cup and your hand warms up. Heat moves from the hot thing to the cold thing, always, until they match. Hot and cold together is what a difference looks like, and a difference never lasts on its own.","Join a hot block and a cold block with a bar and watch them meet in the middle. Then keep one side hot and the other cold and watch the difference stay."]),
 'g8':("Heat moves from hot to cold",None,["Heat is energy on the move, and it moves one way: from the hotter thing to the colder one. How fast depends on the difference, the material (copper carries heat fast, wood barely at all), and the shape of the path. A thick, short copper bar moves heat quickly; a thin, long wooden one hardly moves it.","Left alone, the two blocks end up at the same temperature and the flow stops. To keep heat flowing you must keep the hot side hot and the cold side cold, which is the whole job of a stove on one side and water or fins on the other."]),
 'hs':("Conduction",None,["Fourier's law: the rate of heat flow through a bar is Q̇ = kA(T_hot − T_cold)/L, with k the thermal conductivity (copper 400, steel 50, wood 0.15 W/m·K), A the cross-section and L the length. Each block changes temperature at a rate dT/dt = ±Q̇/(mc), where c is its specific heat.","Without a source and a sink the difference decays exponentially. The time constant is the product of the bar's thermal resistance and the blocks' heat capacity, the same form as an RC circuit."]),
 'col':("Thermal resistance networks",None,["Everything on this board is a series of thermal resistances, R = L/(kA) in K/W, between a source and a sink. A temperature difference divides across them like voltage across resistors in series, and the heat flow is the current. A thermoelectric module is one resistor in that chain, and it only sees the share of the difference that falls across it.","Contact resistance at every interface is usually the largest term and the least advertised: a dry, rough joint can cost more difference than the module itself."]),
 'max':("The heat equation and its limits",None,["Fourier's law is the linear-response, local-equilibrium limit of transport; it fails at nanoscale (ballistic phonons, Kapitza resistance at interfaces) and at very short times (hyperbolic corrections). For a stove and a slab it is exact enough, and the lumped model here is its one-node discretisation.","Entropy production in conduction is Q̇(1/T_c − 1/T_h): the difference is being spent whether or not anything useful is extracted. A thermoelectric module intercepts part of that spending, which is the second-law view of chapter 4."]),
}
CH[2]={
 'k5':("Boiling water",None,["To make water hot you have to give it energy, and a lot of it. Warming a litre of water by one degree takes about as much energy as lifting a bag of sugar up to the roof of a house. Boiling it takes a hundred of those. Turning it into steam takes five hundred more.","Put a pot on the fire and watch the numbers. A bigger fire boils it faster. More water takes longer."]),
 'g8':("Specific heat and boiling",None,["Every kilogram of water needs 4,186 joules to warm by one degree. Warming 1 kg from 20 °C to 100 °C takes 80 × 4,186 ≈ 335,000 J. A 500 W fire delivers 500 J every second, so that is about 670 seconds, eleven minutes, if every joule reaches the water.","Then it boils, and the temperature stops rising. All the fire's energy now goes into turning water into steam, 2,260,000 J per kilogram, which is why a pot boils dry slowly and why steam burns are so bad."]),
 'hs':("Q = mcΔT, then latent heat",None,["Sensible heating: Q = m c ΔT with c = 4,186 J/(kg·K). Boiling: Q = m L with L = 2.26 MJ/kg. Time at power P is t = Q/P, and a real fire under a real pot delivers only 20 to 40% of its heat to the water; the rest warms the air.","Predict before you boil: 1 L from 20 °C at 800 W of delivered power is 335 kJ ÷ 800 W = 419 s, seven minutes. Then check your error."]),
 'col':("Energy balance on a pot",None,["The pot is a control volume: P_in − losses = mc dT/dt below boiling and P_in − losses = L dm/dt at the boil. Losses grow with temperature (convection and radiation from the pot and the free surface), so the last ten degrees take longer than the first ten. A lid cuts evaporative loss, which dominates near the boil.","Efficiency of heat transfer from flame to water is the ratio of the water's energy gain to the fuel's energy release; for an open fire it is often below 10%, for a good stove 30%, for a kettle element over 90%."]),
 'max':("Phase change as a heat sink",None,["At the boil the water is an isothermal reservoir: it absorbs energy at 100 °C without changing temperature, which is exactly what a thermoelectric cold side wants. Boiling-water cooling of the cold face is one of the oldest camp-stove generator designs, and a thermosiphon with a phase-change loop needs no pump.","The latent heat of vaporisation falls to zero at the critical point (374 °C, 22 MPa); near it, small heat inputs produce large volume changes, the operating regime of supercritical steam plants."]),
}
CH[3]={
 'k5':("The wood fire",None,["A log is stored sunshine. Burn it and the energy comes out as heat: a lot of heat, more than a thousand light bulbs' worth from one log while it burns. The trick with a stove is not making it hot but keeping it <em>just right</em>: hot enough to be useful, not so hot that things break.","Feed the stove. Keep the top in the green zone. Too many logs and it runs away."]),
 'g8':("Fuel energy and burn rate",None,["Dry wood holds about 16 million joules per kilogram. Burn a kilogram in an hour and the fire is running at 16,000,000 ÷ 3,600 ≈ 4,400 W of heat. A hot camp fire can burn ten times that. A thermoelectric module on top can only use a tiny part of it, and it must not get above about 170 °C or it is damaged.","So a stove for making electricity is throttled: enough fire to hold the surface in a band, with the rest of the heat going into the room or into water."]),
 'hs':("A stove as a thermal system",None,["Heat release P_fire = ṁ_fuel × H, with H ≈ 16 MJ/kg for dry wood. The stove's surface temperature settles where heat in equals heat out: losses to the room, to the flue, and into whatever sits on top. The lab models the stove as one thermal mass with a loss rate proportional to (T − T_room).","Hold the top between 150 and 170 °C, the sweet spot for a bismuth-telluride module. Overshoot and the module's solder and semiconductor degrade; undershoot and the output falls with the square of the difference."]),
 'col':("Combustion and control",None,["Wood burns in stages: drying, pyrolysis (volatiles), char oxidation. Real heating value depends on moisture: 20% moisture wood delivers about 20% less than dry, since water must be boiled off first. Excess air, flue temperature and draft set how much of the release reaches the stove body rather than the chimney.","Holding a temperature band with a fuel that arrives in lumps is a control problem with delay; the lab's stove has a time constant of minutes, so stoking is a matter of anticipation, not reaction."]),
 'max':("Exergy of a fire",None,["A flame at 900 °C carries high-exergy heat; spending it to hold a 170 °C plate is a large irreversibility before any electricity is made. Combined heat and power is a rational answer: take the small electric share at the top of the temperature ladder and use the large remainder for space or water heating that would have been needed anyway.","That is the design logic of the commercial kits this board is built around: a controlled hot side, a water-cooled cold side, and the water going on to a heating loop."]),
}
CH[4]={
 'k5':("Hot side, cold side",None,["A thermoelectric module is a flat square. Make one face hot and the other cold and it makes electricity. Bigger difference, more electricity. No difference, nothing at all.","Put it on a stove, a camp fire, a cup of coffee, a sunny rock, or your own hand. Cool the other side with air, a fan, water, or ice. Find the biggest difference you can."]),
 'g8':("The Seebeck effect",None,["Inside the module are dozens of tiny pairs of two different materials. When one end of a pair is hotter than the other, electrons drift toward the cold end and a voltage appears. Stack a hundred pairs in a row and you get a few volts from a difference of a hundred degrees. This is the Seebeck effect, found in 1821.","The difference across the module is never the difference between the source and the sink. The hot side has to get heat in and the cold side has to get heat out, and every joint costs some degrees. A good water-cooled cold side is worth more than a hotter fire."]),
 'hs':("V = S·ΔT and P ∝ ΔT²",None,["Open-circuit voltage V = S ΔT, where S for a typical 40 mm module is about 0.04 V per degree. Into a matched load the power is P = V²/(4r) with r the internal resistance, about 2.5 Ω, so P ≈ 1.6 × 10⁻⁴ ΔT² W: 1.6 W at 100 °C of difference, 3.6 W at 150 °C. Power goes with the square of the difference.","The lab computes the module's share of the source-to-sink difference through a chain of thermal resistances, hot-side coupling, module, cold-side sink, so you can see why a fan or a water block changes the watts more than a hotter fire."]),
 'col':("The thermal circuit of a module",None,["ΔT_module = (T_source − T_sink) × R_m/(R_h + R_m + R_c), with R_m ≈ 1.5 K/W for a 40 mm Bi₂Te₃ module, R_h from 0.2 K/W (a clamped stove plate) to 10 K/W (a hand), and R_c from 0.05 K/W (ice bath) to 2 K/W (fins in still air). The heat through the module is that difference over R_m, and the electrical output is a few percent of it.","Everything scales together: a source that is hotter than the module's limit needs a spacer, which adds R_h; a sink that warms up loses its difference. The lab enforces the 170 °C hot-face limit that manufacturers quote for this class of module."]),
 'max':("Coupled transport",None,["The module obeys Q̇_h = S T_h I − ½I²r + K ΔT and Q̇_c = S T_c I + ½I²r + K ΔT: Peltier heat carried by the current, Joule heating split both ways, and Fourier conduction K ΔT that does no work. The Onsager relation ties the Peltier coefficient to the Seebeck coefficient, Π = S T, so the same material property governs both directions.","Interface resistances (electrical and thermal contact) and the temperature dependence of S, ρ and κ set real output below the textbook curve; the 0.04 V/K and 2.5 Ω used here are typical measured module values, not material constants."]),
}
CH[5]={
 'k5':("Why only five percent",None,["A fire makes a great deal of heat, but a module turns only a tiny slice of it into electricity, about one part in twenty. The rest goes straight through as heat. That is not a mistake in the module. It is a rule about heat itself: you can only ever turn part of it into work, and the part depends on how big the difference is.","The good news: heat that goes through is still heat. Use it to warm water and nothing is wasted."]),
 'g8':("The Carnot limit",None,["No machine can turn heat into work at better than a certain fraction, and the fraction depends only on the temperatures: 1 − T_cold/T_hot with both measured from absolute zero (add 273 to degrees Celsius). For a 170 °C hot side and a 0 °C cold side that limit is 1 − 273/443 = 38%. A thermoelectric module gets about a fifth of that, around 5 to 7%.","Why so far below the limit? Because the same material has to carry electricity well and heat badly, and almost nothing does both. That trade-off has a number, called ZT, and for the best everyday materials it is about 1."]),
 'hs':("Carnot times a ZT factor",None,["Carnot: η_C = 1 − T_c/T_h. A thermoelectric generator at its best reaches η = η_C · (√(1+ZT) − 1)/(√(1+ZT) + T_c/T_h), where ZT = S²T/(ρκ) is the figure of merit. With ZT = 1, T_h = 443 K and T_c = 273 K: η_C = 0.38, the factor is 0.20, so η ≈ 7.8% ideal, and real modules land near 5%.","Move the sliders: a hotter hot side helps, a colder cold side helps more per degree, and ZT is the only lever that changes the factor."]),
 'col':("The figure of merit",None,["ZT = S²σT/κ bundles the three properties in tension: high Seebeck coefficient, high electrical conductivity, low thermal conductivity. Metals have high σ but tiny S; insulators the reverse; heavily doped semiconductors sit at the optimum. Bi₂Te₃ alloys reach ZT ≈ 1 near room temperature; skutterudites, half-Heuslers and PbTe-based alloys reach 1 to 1.5 at higher temperatures.","Combined heat and power changes the accounting: the exergy efficiency of electricity plus useful hot water can exceed 80% even though the electric share is 5%."]),
 'max':("Seventy years at ZT ≈ 1",None,["Ioffe's 1950s analysis set the framework; the wall has held because S, σ and κ_electronic are linked by the Wiedemann–Franz law and the Mott relation. Progress comes from cutting lattice thermal conductivity without hurting electrons: the phonon-glass electron-crystal idea (Slack), nanostructuring, hierarchical scattering, and band convergence, giving reported ZT of 2 to 2.5 in SnSe and PbTe systems at high temperature.","Module ZT lags material ZT because of contacts and the temperature spread across the legs; segmented legs and cascaded stages recover some of the difference at a cost in complexity."]),
}
CH[6]={
 'k5':("Match the load",None,["The module makes electricity, but how much you get out depends on what you plug into it. Plug in something that lets too much through and the voltage collapses. Plug in something that lets too little through and hardly any flows. There is a sweet spot in the middle.","Slide the load until the watts peak. Then let the little box turn it into steady USB power."]),
 'g8':("Maximum power transfer",None,["A module behaves like a battery with a resistor hidden inside, about 2.5 ohms. The most power comes out when the thing you connect has the same resistance as the hidden one. Bigger and the current starves; smaller and the voltage sags. Either way you lose.","Real devices do not want 3 volts that wobble. A boost converter takes whatever the module gives, holds the module at its sweet spot, and puts out a steady 5 V for USB, at the cost of a small slice of the power."]),
 'hs':("R_load = r",None,["With open-circuit voltage V and internal resistance r, a load R draws current I = V/(R + r) and receives P = I²R = V²R/(R + r)². Differentiate and the maximum is at R = r, where P = V²/(4r) and the module's terminal voltage is exactly half of V. That is the number quoted in chapter 4.","A maximum-power-point tracker is a converter that adjusts its effective input resistance to stay at R = r as the temperature difference drifts. Modules in series add voltage; in parallel they add current; a kit rated 18 to 20 V under load is a series string."]),
 'col':("Converters and tracking",None,["A boost converter with efficiency η delivers P_out = η P_in at a fixed output voltage; its input impedance is set by duty cycle, which is the control variable for MPPT (perturb-and-observe or fractional open-circuit voltage, since V_mpp = V_oc/2 for a resistive source). Converter losses at low input voltage are the usual reason a 3 W module yields 2 W at USB.","Series strings are sensitive to one cold module: a module with a smaller ΔT limits the string's current, the same weak-cell problem as in battery packs."]),
 'max':("Impedance matching as thermodynamics",None,["Maximum power and maximum efficiency are different operating points: efficiency peaks at R/r = √(1+ZT) > 1, power at R/r = 1. A generator sized by fuel cost runs near maximum efficiency; one sized by module cost runs near maximum power. The lab lets you see both.","Electrical loading also changes the thermal circuit: drawing current moves Peltier heat across the module, lowering ΔT slightly, which is why the open-circuit ΔT overestimates the working one."]),
}
CH[7]={
 'k5':("Build a heat-power system",None,["Pick a fire, pick how many modules, pick how to keep the cold side cold, and see what you can run: a phone, a light, a radio. The leftover heat warms a tank of water, so nothing is thrown away.","Then try the candle and see why it cannot charge a phone. And watch the water: if it gets hot, the difference disappears."]),
 'g8':("From stove to phone",None,["The sequence: what is the hot side temperature, what is the cold side, how many modules, what does each make, subtract the converter's slice, subtract the pump if there is one, and compare with the load. A phone charge is about 10 Wh; a 5 W USB output fills it in two hours. A power bank is 74 Wh.","The cold side is the whole game. Water carries heat away fast, but a small tank warms up; the difference shrinks and the watts fall. A bigger tank, or a loop that dumps the heat into a room, keeps it going. A commercial kit does exactly this and calls it combined heat and power."]),
 'hs':("Sizing the system",None,["Per module P = 1.6 × 10⁻⁴ ΔT_module². Series string voltage is N × 0.02 × ΔT at the maximum power point. Converter efficiency ~85%, pump draw 1 to 3 W. Water tank heating: the module passes roughly 20 × its electrical output as heat, so 40 W electric means about 800 W into the water, warming 20 L by 34 °C per hour and collapsing the difference unless the heat is moved on.","The manufacturer rating this board uses as a worked example: 40 W peak with a 0 °C cold side and a 170 °C hot side, 18 to 20 V under load, active water cooling required. Reproduce that operating point in the lab and then see what a 20 °C cold side does to it."]),
 'col':("Combined heat and power",None,["Write the energy balance: fire → stove → module hot face (limit 170 °C) → module → cold block → water → tank or heating loop. Electric output is a few percent of the flow; the loop must reject the other 95% at a temperature useful for heating but low enough to keep the module's ΔT. A thermosiphon loop removes the pump's parasitic draw at the cost of flow control.","Warnings the lab raises are the real failure modes: hot face over limit, cold water over 60 °C, converter input below its start-up voltage, and a load larger than the output."]),
 'max':("Where the numbers break",None,["Peak ratings assume an ice-water cold side and a fully coupled hot side; a typical stove-top installation with fins and room air yields a third of nameplate. Long-term, thermal cycling fatigues solder joints and diffuses contacts; the tens-of-thousands-of-hours lifetime claims hold under steady thermal management, not repeated overshoot.","The honest design envelope: a well-built stove system delivers 10 to 40 W of electricity and hundreds of watts of hot water. That is enough for lights, radios, sensors and phones through a winter, and not enough for a refrigerator. The system checker on the Electricity board takes it from here."]),
}
CH[8]={
 'k5':("Blackout",None,["The power goes out. It is winter, it is night, and you have a stove, a pile of logs, a battery, and one long night to get through. Keep the lamp on. Charge the phone. Keep the room warm. Don't run out of wood.","Everything you learned is in this room. Cut the grid and see how you do."]),
 'g8':("Blackout: the whole system, live",None,["When the grid is on, the wall charges the battery and the furnace warms the room. Cut it and the stove has to do both jobs. The plate must stay in its band for the modules to make watts, the water must stay cool for the difference to hold, and the battery must never hit empty or everything on the shelf goes dark.","Wood is limited. So is time. Decide what to run and when: the lamp all night, the phone before midnight, the radio for the morning news. Try the fridge and learn why nobody runs one on a stove."]),
 'hs':("Blackout: budgets and priorities",None,["The numbers: eight modules make about 13 W usable at a 100 K difference, less the 2 W pump. The battery holds 200 Wh. The lamp is 5 W, 40 Wh for an eight-hour night; the phone needs 10 Wh; the radio 3 W; the fridge 60 W, which is 480 Wh a night and far beyond a stove. Each log is a kilogram, 16 MJ, about an hour of fire at a good burn.","The room is a second energy balance: the cabin loses about 100 W per degree above the outside air, and the stove gives it most of the fire. Play it twice: once to survive, once to finish with logs to spare."]),
 'col':("Blackout as a scheduling problem",None,["Two coupled balances, electrical and thermal, with one controllable input (fuel rate) and a set of switchable loads. The electrical side is a small storage system with a variable source; the thermal side has a fast state (the plate), a medium one (the tank) and a slow one (the room). The plate's 170 °C limit and the tank's 60 °C limit are constraints; wood is the budget.","Good play looks like good control: anticipate the plate's lag, stoke before it falls out of band, open the loop before the tank runs away, and shift loads to when the source is strong. Priority ordering under a fixed budget is the whole discipline of off-grid operation."]),
 'max':("What a real winter setup needs",None,["Storage sized for autonomy days rather than one night; a source that does not depend on someone awake to stoke it, which is why real installations pair a thermoelectric CHP unit with solar and a larger bank; telemetry loads that are small but never off; and protection against the failure modes this game exposes, plate overtemperature and cold-side runaway, as automatic interlocks rather than player attention.","At high latitude in midwinter, solar delivers a fraction of its summer output while heating demand peaks; a stove that yields tens of watts of electricity from heat you were making anyway is the rare resource that is strongest exactly when it is needed."]),
}
GROWN={
 1:"The one-sentence version: heat is a difference being spent. Everything on the board is about making that difference and keeping it.",
 2:"Time a real kettle with a stopwatch and a measuring jug; the lab's numbers should be within a minute of it.",
 3:"If you have a wood stove, an infrared thermometer on the top plate makes this chapter real. 150 to 170 °C is the band.",
 4:"A single module on a candle can light an LED. The hand as a heat source gives about a tenth of a watt with a good sink, which is enough for a watch.",
 5:"Kids accept the 5% readily; the surprising part is that it is a law, not a flaw. Carnot is the first equation most people meet that is a limit rather than a recipe.",
 6:"The sweet spot exists for solar panels and batteries too. The idea transfers.",
 8:"Let a child run the night alone before you say anything. The lesson arrives when the battery hits empty at 3 a.m.",
 7:"Try the candle first. Watching a phone need three days to charge is a better lesson than any sentence.",
}
UNITS=[('°C','degrees Celsius'),('K','kelvin, a temperature or a difference'),('W','watts'),('kW','kilowatts'),('Wh','watt-hours'),('J','joules'),('kJ','kilojoules'),('MJ','megajoules'),('V','volts'),('A','amps'),('Ω','ohms'),('s','seconds'),('min','minutes'),('h','hours'),('kg','kilograms'),('L','litres'),('%','percent'),('n','a plain number')]
UNIT_WHY={'°C':'degrees measure a temperature','K':'kelvin measures a temperature or a difference between two','W':'watts are a rate: energy per second','kW':'kilowatts are a rate: energy per second','Wh':'watt-hours are an amount of energy','J':'joules are an amount of energy','kJ':'kilojoules are an amount of energy','MJ':'megajoules are an amount of energy','V':'volts measure the push','A':'amps measure the flow','Ω':'ohms measure opposition','s':'seconds measure a time','min':'minutes measure a time','h':'hours measure a time','kg':'kilograms measure mass','L':'litres measure volume','%':'percent is a share, no unit','n':'a ratio, no unit'}
CHECK={
 8:{'k5':("The battery holds 200 Wh. The lamp uses 5 W. If nothing else is on and nothing charges it, how many hours does the lamp last?",40,'h',.02,"Amount ÷ rate.","Right. 40 hours, so the lamp is never the problem."),
    'g8':("The modules make 12 W. The lamp and the phone together use 10 W. Net power into the battery?",2,'W',.02,"In minus out.","Right. 2 W: it charges, slowly."),
    'hs':("An 8-hour night with the lamp (5 W) and the radio (3 W) on the whole time. Energy needed?",64,'Wh',.02,"8 W × 8 h.","Right. 64 Wh, a third of the battery."),
    'col':("A 60 W fridge for 24 hours. Energy?",1440,'Wh',.02,"60 × 24.","Right. 1,440 Wh, more than a hundred stove-nights of surplus."),
    'max':("Output is 13 W at ΔT = 100 K. The tank warms and ΔT drops to 70 K. Output, with P ∝ ΔT²?",6.4,'W',.04,"(70/100)² × 13.","Right. About 6.4 W: half the power for 30% less difference.")},
 1:{'k5':("One block is 100 °C and the other 20 °C. When they finish sharing, roughly what temperature are they both?",60,'°C',.05,"Halfway between.","Right. About 60 °C, and the flow stops."),
    'g8':("Hot block 100 °C, cold block 20 °C. What is the temperature difference?",80,'K',.02,"Subtract. A difference is measured in kelvin (or degrees).","Right. 80 K of difference, and that is what drives the flow."),
    'hs':("A copper bar, k = 400 W/m·K, A = 0.0004 m², L = 0.1 m, with 80 K across it. Heat flow?",128,'W',.03,"Q̇ = kAΔT/L.","Right. 400 × 0.0004 × 80 ÷ 0.1 = 128 W."),
    'col':("Thermal resistance of that bar, L/(kA)?",0.625,'K/W'.replace('K/W','n'),.03,"0.1 ÷ (400 × 0.0004). Enter the number only.","Right. 0.625 K per watt."),
    'max':("Entropy production rate for 100 W flowing from 400 K to 300 K, in W/K? Enter the number.",0.083,'n',.05,"Q̇(1/T_c − 1/T_h).","Right. About 0.083 W/K, spent whether or not you harvest any of it.")},
 2:{'k5':("A fire gives the pot 500 joules every second. In 10 seconds, how many joules?",5000,'J',.02,"Rate × time.","Right. 5,000 J."),
    'g8':("Warm 1 kg of water from 20 °C to 100 °C: 80 × 4,186 joules. How many kilojoules?",335,'kJ',.03,"Multiply, then divide by 1,000.","Right. About 335 kJ."),
    'hs':("335 kJ delivered at 800 W. How many seconds?",419,'s',.03,"t = Q/P.","Right. About 419 s, seven minutes."),
    'col':("Boil away 0.5 kg of water at 100 °C (L = 2.26 MJ/kg). Energy?",1.13,'MJ',.03,"Q = mL.","Right. 1.13 MJ, three times what it took to heat it."),
    'max':("A 1,500 W element with 92% transfer heats 1.5 L from 15 °C to 100 °C. Minutes?",6.4,'min',.05,"Q = 1.5 × 4,186 × 85; t = Q/(0.92 × 1,500).","Right. About 6.4 minutes.")},
 3:{'k5':("One log makes 16 million joules. Two logs?",32,'MJ',.02,"Double it.","Right. 32 MJ."),
    'g8':("Burn 1 kg of wood (16 MJ) in one hour. Average heat power?",4444,'W',.03,"16,000,000 ÷ 3,600.","Right. About 4,400 W."),
    'hs':("A stove burns 0.5 kg/h of wood at 16 MJ/kg. Heat release in kW?",2.22,'kW',.03,"ṁ × H, then per second.","Right. About 2.2 kW."),
    'col':("Wood at 20% moisture, 16 MJ/kg dry basis. Roughly how much less energy per kg of wet wood, as a percent?",20,'%',.15,"The water is dead weight plus a boiling cost.","Right. About 20% less, a bit more once you count boiling the water off."),
    'max':("Flame at 900 °C (1,173 K), room at 300 K. Carnot fraction of that heat that could ever become work?",74,'%',.03,"1 − 300/1,173.","Right. About 74%, almost all of it thrown away when you only need a 170 °C plate.")},
 4:{'k5':("The hot side is 150 °C and the cold side is 50 °C. What is the difference?",100,'K',.02,"Subtract.","Right. 100 degrees of difference."),
    'g8':("A module makes 0.04 V for every degree of difference. At 100 degrees, volts?",4,'V',.02,"0.04 × 100.","Right. 4 V, open circuit."),
    'hs':("P = 1.6 × 10⁻⁴ × ΔT². Power at ΔT = 150 K?",3.6,'W',.03,"150² = 22,500.","Right. 3.6 W into a matched load."),
    'col':("Source 170 °C, sink 20 °C, R_h = 0.2, R_m = 1.5, R_c = 0.3 K/W. ΔT across the module?",112.5,'K',.03,"150 × 1.5 ÷ 2.0.","Right. 112.5 K: the couplings ate a quarter of the difference."),
    'max':("Same chain but a passive sink, R_c = 2.0 K/W. ΔT across the module?",60.8,'K',.03,"150 × 1.5 ÷ 3.7.","Right. About 61 K, and power falls by a factor of 3.4.")},
 5:{'k5':("A fire makes 100 watts of heat. The module turns 5 percent into electricity. Watts of electricity?",5,'W',.02,"5% of 100.","Right. 5 W. The other 95 W is still heat."),
    'g8':("Hot side 170 °C, cold side 0 °C. Carnot limit = 1 − 273/443, as a percent?",38,'%',.04,"Add 273 to each, then divide.","Right. About 38%: no machine can beat it."),
    'hs':("Same temperatures, ZT = 1. Ideal thermoelectric efficiency, percent?",7.8,'%',.06,"0.384 × (1.414 − 1)/(1.414 + 0.616).","Right. About 7.8% ideal; real modules near 5%."),
    'col':("Hot 500 K, cold 300 K, ZT = 2. Ideal efficiency, percent?",13.1,'%',.06,"η_C = 0.4; factor = (√3 − 1)/(√3 + 0.6).","Right. About 13%."),
    'max':("Material with S = 200 μV/K, σ = 10⁵ S/m, κ = 1.5 W/m·K at 300 K. ZT?",0.8,'n',.06,"S²σT/κ = (2e-4)² × 1e5 × 300 ÷ 1.5.","Right. 0.8, a respectable everyday thermoelectric.")},
 6:{'k5':("The module pushes with 4 volts. Into the best load, only half shows up at the plug. Volts at the plug?",2,'V',.02,"Half of 4.","Right. 2 V at maximum power."),
    'g8':("Module: 4 V, 2.5 Ω inside. Best load resistance?",2.5,'Ω',.02,"Match the hidden resistance.","Right. 2.5 Ω."),
    'hs':("V = 4 V, r = 2.5 Ω, matched load. Power?",1.6,'W',.03,"V²/(4r).","Right. 16 ÷ 10 = 1.6 W."),
    'col':("8 modules in series at 2 V each (matched). String voltage?",16,'V',.02,"Series adds volts.","Right. 16 V, the range a kit quotes under load."),
    'max':("ZT = 1. Load ratio R/r for maximum efficiency?",1.41,'n',.03,"√(1 + ZT).","Right. About 1.41, above the maximum-power point at 1.")},
 7:{'k5':("A phone needs 10 watt-hours. The stove makes 5 watts for the phone. Hours to charge?",2,'h',.02,"Amount ÷ rate.","Right. 2 hours."),
    'g8':("A candle gives the module 0.1 W. Hours to charge the same 10 Wh phone?",100,'h',.03,"10 ÷ 0.1.","Right. 100 hours, four days. Candles are for light."),
    'hs':("40 W electric at 5% efficiency. How much heat is passing into the water?",760,'W',.05,"Heat through = electric × (1 − 0.05)/0.05.","Right. About 760 W, which is why the water warms fast."),
    'col':("760 W into a 20 L tank, no loop. Temperature rise per hour? (c = 4,186 J/kg·K)",32.7,'K',.05,"760 × 3,600 ÷ (20 × 4,186).","Right. About 33 K per hour; the difference collapses within two hours."),
    'max':("Nameplate 40 W at 0 °C cold side (ΔT 170). Same hot side, cold side 20 °C. Output, assuming P ∝ ΔT²?",31,'W',.05,"(150/170)² × 40.","Right. About 31 W, and less again once the sink warms.")},
}
FIG={
 1:'''<div class="panel"><canvas id="cv-flow" aria-label="A hot block and a cold block joined by a bar. Heat flows until they match, unless a source and a sink keep them apart."></canvas></div>
    <div class="controls"><span class="lbl">Bar</span><button class="btn is-on" data-mat="400">copper</button><button class="btn" data-mat="50">steel</button><button class="btn" data-mat="0.15">wood</button><button class="btn" id="fw-src" aria-pressed="false">Heater under hot block: off</button><button class="btn" id="fw-sink" aria-pressed="false">Water on cold block: off</button><button class="btn" id="fw-reset">Reset blocks</button></div>
    <figcaption><b>Try this:</b> watch the two temperatures meet. Then switch on the heater and the water and watch the difference hold.</figcaption>''',
 2:'''<div class="panel"><canvas id="cv-boil" aria-label="A pot of water on a fire. Sliders set fire power and water amount; the temperature climbs and then boils."></canvas></div>
    <div class="controls"><button class="btn primary" id="bl-go">Light the fire</button><label class="slider">Heat into the pot <input type="range" id="bl-p" min="100" max="3000" step="100" value="800"><span class="val" id="bl-p-val">800 W</span></label><label class="slider">Water <input type="range" id="bl-m" min="0.25" max="3" step="0.25" value="1"><span class="val" id="bl-m-val">1 L</span></label><label class="slider" data-lv="hs col max">I predict <input type="number" id="bl-pred" step="1" min="0" placeholder="s" style="width:5rem"> s to boil</label></div>
    <figcaption><b>Try this:</b> boil a litre. Double the fire and see what happens to the time. <span data-lv="hs col max">Predict the seconds to the boil first; the lab scores you.</span></figcaption>''',
 3:'''<div class="panel"><canvas id="cv-stove" aria-label="A wood stove with a temperature gauge on its top plate. Add logs to hold the plate in the green band without overshooting."></canvas></div>
    <div class="controls"><button class="btn primary" id="st-log">Add a log</button><label class="slider">Air (burn rate) <input type="range" id="st-air" min="0.2" max="1.5" step="0.1" value="0.6"><span class="val" id="st-air-val">0.6 kg/h</span></label><button class="btn" id="st-reset">Cold stove</button></div>
    <figcaption><b>Try this:</b> hold the top plate between 150 and 170 °C for half a minute. Then find out what too many logs does.</figcaption>''',
 4:'''<div class="panel"><canvas id="cv-teg" aria-label="A thermoelectric module between a chosen heat source and a chosen cold sink, with the temperature difference and watts shown."></canvas></div>
    <div class="controls"><span class="lbl">Hot side</span><select id="tg-src"><option value="stove">stove top 170 °C</option><option value="fire">camp fire 400 °C</option><option value="exhaust">exhaust pipe 220 °C</option><option value="coffee">cup of coffee 70 °C</option><option value="rock">sun-warmed rock 45 °C</option><option value="hand">your hand 33 °C</option><option value="candle">candle 250 °C, tiny</option></select><span class="lbl">Cold side</span><select id="tg-sink"><option value="air">bare in still air</option><option value="fins">fins in still air</option><option value="fan">fins and a fan</option><option value="water" selected>water block, pumped</option><option value="ice">ice water</option></select><button class="btn" id="tg-spacer" data-lv="g8 hs col max" aria-pressed="false">Spacer: off</button></div>
    <figcaption><b>Try this:</b> try every hot side with every cold side. Find the biggest watts. <span data-lv="g8 hs col max">The camp fire is too hot for the module: add the spacer and watch what it costs.</span></figcaption>''',
 5:'''<div class="panel"><canvas id="cv-carnot" aria-label="Sliders for hot and cold temperature and ZT, with the Carnot limit and the thermoelectric efficiency drawn as a bar of heat in, electricity out, heat through."></canvas></div>
    <div class="controls"><label class="slider">Hot side <input type="range" id="cn-th" min="40" max="600" step="5" value="170"><span class="val" id="cn-th-val">170 °C</span></label><label class="slider">Cold side <input type="range" id="cn-tc" min="-20" max="100" step="5" value="0"><span class="val" id="cn-tc-val">0 °C</span></label><label class="slider" data-lv="g8 hs col max">ZT <input type="range" id="cn-zt" min="0.2" max="3" step="0.1" value="1"><span class="val" id="cn-zt-val">1.0</span></label></div>
    <figcaption><b>Try this:</b> set 170 °C over 0 °C and read the limit. Then try to reach 10% real efficiency. <span data-lv="g8 hs col max">Only ZT moves the factor; temperatures only move the Carnot limit.</span></figcaption>''',
 6:'''<div class="panel"><canvas id="cv-load" aria-label="A module with a hidden internal resistance feeding an adjustable load. The power curve and the sweet spot are drawn."></canvas></div>
    <div class="controls"><label class="slider">Load resistance <input type="range" id="ld-r" min="0.2" max="12" step="0.1" value="6"><span class="val" id="ld-r-val">6.0 Ω</span></label><label class="slider">Difference <input type="range" id="ld-dt" min="20" max="170" step="5" value="120"><span class="val" id="ld-dt-val">120 K</span></label><label class="slider" data-lv="hs col max">Modules in series <input type="range" id="ld-n" min="1" max="8" step="1" value="1"><span class="val" id="ld-n-val">1</span></label><button class="btn" id="ld-boost" aria-pressed="false">Boost to 5 V USB: off</button></div>
    <figcaption><b>Try this:</b> slide the load until the watts peak. Switch on the converter and read the USB watts.</figcaption>''',
 7:'''<div class="panel"><canvas id="cv-sys" class="short" aria-label="A report for a heat-power system: source, sink, modules, watts, charge times, water temperature over time, warnings."></canvas></div>
    <div class="controls"><span class="lbl">Fire</span><select id="sy-src"><option value="candle">candle</option><option value="camp">camp stove</option><option value="wood" selected>wood stove</option><option value="propane">propane burner</option></select><label class="slider">Modules <input type="range" id="sy-n" min="1" max="16" step="1" value="8"><span class="val" id="sy-n-val">8</span></label><span class="lbl">Cooling</span><select id="sy-cool"><option value="fins">fins, no fan</option><option value="fan">fins and fan</option><option value="tank" selected>water, 20 L tank</option><option value="loop">water loop to a radiator</option></select><span class="lbl">Run</span><select id="sy-load"><option value="phone" selected>phone (10 Wh)</option><option value="bank">power bank (74 Wh)</option><option value="led">5 W lamp all night</option><option value="fridge">fridge (60 W)</option></select><button class="btn primary" id="sy-run">Run for 3 hours</button></div>
    <figcaption><b>Try this:</b> charge a phone from the wood stove. Then try the candle. Then watch the 20 L tank warm up and the watts fall, and fix it with the loop.</figcaption>''',
 8:'''<div class="panel"><canvas id="cv-blackout" aria-label="A cabin at night with a wood stove, thermoelectric modules, a water tank, a battery, and a shelf of devices. Cut the grid and get through the night."></canvas></div>
    <div class="controls"><button class="btn primary" id="bo-cut">Cut the grid</button><button class="btn" id="bo-log">Add a log</button><label class="slider">Air <input type="range" id="bo-air" min="0.3" max="2" step="0.1" value="0.8"><span class="val" id="bo-air-val">0.8 kg/h</span></label><button class="btn is-on" id="bo-pump" aria-pressed="true">Pump: on</button><button class="btn" id="bo-loop" aria-pressed="false">Loop to radiator: off</button><span class="sep"></span><button class="btn is-on" id="bo-lamp" aria-pressed="true">Lamp: on</button><button class="btn is-on" id="bo-phone" aria-pressed="true">Phone: charging</button><button class="btn" id="bo-radio" aria-pressed="false">Radio: off</button><button class="btn" id="bo-fridge" aria-pressed="false">Fridge: off</button><button class="btn" id="bo-reset">Restart the night</button></div>
    <figcaption><b>Try this:</b> cut the grid at 10 p.m. Feed the stove, keep the plate in the band, keep the water cool, and get to 6 a.m. with the lamp on and the phone charged. Three real seconds are ten minutes of night.</figcaption>''',
}
ALL=['k5','g8','hs','col','max']
MISSIONS=[
 ('ht1','ch1',ALL,"Watch the two blocks reach the same temperature."),
 ('ht1b','ch1',['g8','hs','col','max'],"Hold a difference of at least 50 degrees for 30 seconds using the heater and the water."),
 ('ht2','ch2',ALL,"Boil one litre."),
 ('ht2b','ch2',['hs','col','max'],"Predict the seconds to the boil within 10%."),
 ('ht3','ch3',ALL,"Hold the stove top between 150 and 170 °C for 30 seconds."),
 ('ht3b','ch3',['g8','hs','col','max'],"Overshoot 170 °C on purpose and read the warning."),
 ('ht4','ch4',ALL,"Make one watt."),
 ('ht4b','ch4',ALL,"Make three watts from one module without going over 170 °C."),
 ('ht4c','ch4',['g8','hs','col','max'],"Use your hand as the heat source and read how little you get."),
 ('ht5','ch5',ALL,"Set 170 °C over 0 °C and read the Carnot limit."),
 ('ht5b','ch5',['hs','col','max'],"Reach 10% real efficiency."),
 ('ht6','ch6',ALL,"Find the load that gives the most watts."),
 ('ht6b','ch6',['hs','col','max'],"Get at least 2 W out of the USB converter."),
 ('ht7','ch7',ALL,"Charge the phone in under 4 hours."),
 ('ht7b','ch7',['g8','hs','col','max'],"Try the candle and read how long the phone would take."),
 ('ht7c','ch7',['hs','col','max'],"Run three hours on the water tank without the water passing 60 °C."),
 ('bo1','ch8',ALL,"Cut the grid and reach 6 a.m. with the lamp still on."),
 ('bo2','ch8',ALL,"Charge the phone before midnight."),
 ('bo3','ch8',['g8','hs','col','max'],"Finish the night with the room above 10 °C."),
 ('bo4','ch8',['hs','col','max'],"Never let the plate pass 170 °C."),
 ('bo5','ch8',['hs','col','max'],"Finish with at least two logs to spare."),
 ('bo6','ch8',['g8','hs','col','max'],"Switch on the fridge and watch what it does to the battery."),
]+[(f'tb{n}',f'ch{n}',ALL,"Teach it back: answer the check question below with the right unit.") for n in range(1,9)]
CLOSING=("Heat is a difference being spent.","Make the difference, keep the difference, and take a small slice on the way through. Everything else is plumbing.")
