KEY='electricity'
TITLE='Electricity From Zero'
FAVICON='⚡'
DESC="Electricity from watts and watt-hours to fields and the Poynting vector, one concept at a time, with experiments, unit-checked teach-backs, and a system checker at five reading levels."
EYEBROW="From zero to deep understanding"
TRAIL=[('top','Start'),('ch1','1 · Watts and watt-hours'),('ch2','2 · Push, flow, opposition'),('ch3','3 · Power and voltage'),('ch4','4 · Real batteries'),('ch5','5 · Series and parallel'),('ch6','6 · Kirchhoff'),('ch7','7 · AC'),('ch8','8 · Power factor'),('ch9','9 · What actually moves'),('ch10','10 · The system checker')]
HERO={
 'k5':"Electricity is not magic and it is not hard. It is a push, a flow, and a bucket of energy, and you can count all three. This board teaches one idea at a time, with a small experiment and a question to answer before you move on. The first idea is the most important: how <em>fast</em> is not how <em>much</em>.",
 'g8':"Build the picture first, then add the math when it explains something you already understand. The foundation is one distinction: watts are a rate, watt-hours are an amount. Every chapter here adds one idea, shows it with real objects (bulbs, batteries, panels, inverters, outlets, motors), and asks you to teach it back before you go on. Units are corrected every time.",
 'hs':"A working understanding of electricity built in order: energy and power, then Ohm's law, then P = VI and why voltage matters, batteries as they really are, series and parallel, Kirchhoff's laws, AC and RMS, reactive power, and finally what actually moves in a wire. Every formula is translated into plain English, and every chapter ends with a problem that checks your units.",
 'col':"From definitions (1 A = 1 C/s, 1 V = 1 J/C, 1 W = 1 J/s) to Thévenin equivalents, nodal analysis, phasors and complex power, battery models with internal resistance, and the Poynting picture of energy flow. The last chapter turns the practical analysis sequence into a tool: voltage, power, current, energy, run time, charge time, losses, surge, and constraints.",
 'max':"A first-principles route through circuit theory as the lumped limit of Maxwell's equations: drift velocity and surface charge, R = ρL/A, impedance Z = R + jX, field energy densities, the Poynting vector as the rigorous account of where the power goes, plus the engineering constraints that decide real systems: BMS limits, ampacity, fault current, and efficiency curves.",
}
CH={}
CH[1]={
 'k5':("How fast, and how much",None,["A light bulb uses energy. <em>Watts</em> tell you how fast it is using energy right now, like how fast water pours from a tap. <em>Watt-hours</em> tell you how much energy was used altogether, like how much water is in the bucket.","A battery is a bucket of watt-hours. A bulb is a tap that pours watts. If the tap pours 250 watts and the bucket holds 2,500 watt-hours, the bucket lasts 10 hours, because 2,500 ÷ 250 = 10."]),
 'g8':("Watts are a rate. Watt-hours are an amount.",None,["Wh = W × h. In words: energy equals how fast, times how long. A 250 W solar panel charging a 2,500 Wh battery takes 2,500 ÷ 250 = 10 ideal hours. Two panels make 500 W and take 5 hours. One 125 W panel takes 20 hours.","Your electricity bill charges by the kilowatt-hour: 1 kWh = 1,000 Wh, about the energy of running a 100 W bulb for 10 hours. When someone says a battery is '5 kilowatts', ask: kilowatts, or kilowatt-hours? Rate, or amount?"]),
 'hs':("Energy is the integral of power",None,["Power is the rate of energy transfer; energy is power accumulated over time. For constant power, E = P × t. Units: W for power, Wh or J for energy, with 1 Wh = 3,600 J.","The ideal-time formula t = E / P assumes constant power and no losses. Real answers need efficiency and source variability, since a panel rarely makes its rated watts. Chapter 4 adds those."]),
 'col':("Bookkeeping with joules",None,["1 W = 1 J/s. A battery's stored energy is the integral of P over the discharge; manufacturers quote Wh at a specified rate and temperature. The kWh is the utility's unit because the meter integrates instantaneous power.","Estimate first: 2,500 Wh ÷ 250 W = 10 h. Then refine with efficiency, depth-of-discharge limits, and rate effects. An estimate with the right units beats an exact answer with the wrong ones."]),
 'max':("Power and energy as one flux",None,["Power and energy are two descriptions of the same flow. The Poynting vector S = E × H is power per unit area crossing a surface; its surface integral is the watts, and the time integral of that is the watt-hours.","Everything on this board reduces to bookkeeping of that flux: sources push it into the field, loads pull it out, and losses convert it to heat on the way. Chapter 9 makes the picture explicit."]),
}
CH[2]={
 'k5':("Push, flow, and opposition",None,["<em>Voltage</em> is the push. <em>Current</em> is the flow. <em>Resistance</em> is how hard it is to flow. Push harder and you get more flow. Squeeze the hose and you get less.","A battery pushes. A wire lets the flow through. A bulb resists, and the resisting is what makes it glow."]),
 'g8':("Volts, amps, and ohms",None,["Volts (V) measure push, amps (A) measure flow, ohms (Ω) measure opposition. Flow = push ÷ opposition, or I = V ÷ R. Twelve volts pushing through six ohms gives two amps.","Double the push and you double the flow. Double the opposition and you halve the flow. Every electrical question starts by naming which of the three you are talking about."]),
 'hs':("Ohm's law",None,["V = I × R: the voltage across a resistor equals the current through it times its resistance. It is a property of materials, metals at a fixed temperature in particular, not a law of nature. A bulb filament's resistance rises as it heats, and a diode does not obey it at all.","Combine with P = V × I from the next chapter and you get P = V²/R = I²R, the two forms you will use most."]),
 'col':("What the units mean",None,["1 A = 1 C/s, one coulomb of charge per second. 1 V = 1 J/C, one joule of energy per coulomb pushed. So volts × amps = joules per second = watts, which is why P = VI is a definition rather than a discovery.","Resistance R = ρL/A: longer wire, more resistance; thicker wire, less. Copper's ρ ≈ 1.7 × 10⁻⁸ Ω·m. Ohm's law is the linear response of a conductor, J = σE."]),
 'max':("Potential difference and the Drude picture",None,["Voltage is a potential difference, the line integral of E between two points. It is path-independent in electrostatics but not when magnetic flux changes (Faraday), which is why 'the voltage across' a loop near a transformer is ambiguous.","J = σE is the constitutive relation; the Drude model gives σ = ne²τ/m and a drift velocity v = J/(ne) of a fraction of a millimetre per second for ordinary currents. Chapter 9 returns to this."]),
}
CH[3]={
 'k5':("Power, and why the push matters",None,["How fast energy moves depends on both push and flow: watts = volts × amps. A big push with a small flow can move energy just as fast as a small push with a big flow.","But big flows make wires hot, so they need thick wires. For the same job, more volts means fewer amps, thinner wires, and less heat. That is why the wires on tall towers carry a huge push."]),
 'g8':("P = V × I",None,["Power = push × flow. To deliver 1,200 W at 12 V you need 100 A, a huge current that needs thick, expensive cable. At 48 V you need 25 A; at 120 V, 10 A.","That is why home solar systems moved from 12 V to 48 V and why the grid uses hundreds of thousands of volts on long lines. Same watts, far fewer amps."]),
 'hs':("Wire heating: I²R",None,["Loss in a wire is P = I²R. Halve the current and you quarter the loss in the same wire. Deliver 1,200 W through a cable of 0.05 Ω: at 12 V (100 A) the loss is 500 W, almost half the power. At 48 V (25 A) it is 31 W.","Voltage drop along the cable is V = I × R: 5 V lost at 12 V is disastrous; 1.25 V at 48 V is fine. Both effects push real systems toward higher voltage."]),
 'col':("Transmission and ampacity",None,["For fixed delivered power P at voltage V, line loss scales as (P/V)²R. Transformers make AC the practical way to step voltage up and down, which decided the AC-versus-DC war of the 1880s.","Ampacity tables turn I²R heating limits into wire sizes: roughly 30 A for 10 AWG and 85 A for 4 AWG with common insulation, derated for bundling and ambient temperature."]),
 'max':("Where the heat comes from",None,["Joule heating is the work done by the field on the carriers, J·E per unit volume. The power delivered to a load enters through the surrounding field: in a two-wire line the Poynting flux runs parallel to the wires in the space between them, and only a small component turns into the conductors to become I²R heat.","Skin effect raises the effective resistance of large conductors for AC: δ = √(2ρ/ωμ) ≈ 8.5 mm in copper at 60 Hz, which is why large busbars are hollow or laminated."]),
}
CH[4]={
 'k5':("Real batteries",None,["Batteries are labeled two ways. Amp-hours say how much flow for how long. Watt-hours say how much energy. To turn amp-hours into watt-hours, multiply by the volts: a 12 V battery with 100 Ah holds about 1,200 Wh.","Real batteries lose a little. The box that turns battery power into wall power, the inverter, wastes some as heat. So a 10-hour guess is really more like 8 or 9."]),
 'g8':("Ah versus Wh",None,["Wh ≈ V × Ah. A 12.8 V, 100 Ah battery holds 1,280 Wh. Compare batteries in Wh, never in Ah alone: a 100 Ah battery at 12 V holds half as much as a 100 Ah battery at 24 V.","Inverters are 85 to 95% efficient, so real run time = Wh × efficiency ÷ W. And panels rarely produce their rating: a 250 W nameplate might average 150 W over a sunny day."]),
 'hs':("Sag, cutoff, and depth of discharge",None,["Battery voltage is not constant. It sags under load because of internal resistance, and it falls as the battery empties. The BMS (battery management system) cuts off at a minimum voltage and limits current, so usable Wh is less than the nameplate.","Depth of discharge: lithium iron phosphate cells are cycled to 80 to 100%; lead-acid to about 50%. Real run time = usable Wh × inverter efficiency ÷ load W."]),
 'col':("The internal-resistance model",None,["Model a battery as an ideal source V₀ in series with internal resistance r: terminal voltage V = V₀ − I·r. Delivered power peaks at I = V₀/2r with only 50% efficiency, so batteries are run far below that point.","Capacity depends on rate (Peukert's law for lead-acid) and temperature. Charging tapers: constant current until a voltage limit, then constant voltage while current falls, so the last 20% takes about as long as the first 80%."]),
 'max':("State of charge is an inference",None,["Coulomb counting drifts; open-circuit voltage is flat over most of the LiFePO₄ curve; so BMS firmware fuses both, typically with a Kalman filter. Round-trip efficiency has coulombic (≈99%) and voltage (≈95%) components.","Inverter efficiency curves fall sharply at light load: idle draw is often 20 to 50 W, which is why 'small load, big inverter' systems die overnight. Efficiency is a curve, not a number."]),
}
CH[5]={
 'k5':("Series and parallel",None,["Stack batteries end to end (<em>series</em>) and their pushes add up: four 3 V cells make 12 V. Put them side by side (<em>parallel</em>) and they last longer instead: same push, bigger bucket.","Bulbs in a chain share the push. Bulbs side by side each get the whole push."]),
 'g8':("Adding pushes, adding buckets",None,["Series: voltages add, and the same current flows through each part. Parallel: the voltage is the same across each part, and the currents add. Four 3.2 V cells in series make 12.8 V. Two 100 Ah batteries in parallel make 200 Ah at the same voltage.","Resistors: in series they add (R₁ + R₂). In parallel the total is less than the smallest: 1/R = 1/R₁ + 1/R₂."]),
 'hs':("Why the rules work",None,["Series resistances add because the same current suffers each drop in turn. Parallel conductances add because each branch is a separate path: for two, R = R₁R₂/(R₁ + R₂).","A 48 V pack is 16 LiFePO₄ cells in series (16 × 3.2 V = 51.2 V); a large pack is several such strings in parallel, and a BMS keeps the cells balanced."]),
 'col':("Matching and balancing",None,["Series and parallel are the two special cases of Kirchhoff's laws; a general network such as a bridge needs the node or mesh analysis of the next chapter.","Cell matching matters. In a parallel group the lowest-resistance cell takes the most current; in a series string the weakest cell limits capacity and is over-stressed, hence active balancing circuits."]),
 'max':("Thévenin and Norton",None,["Any linear two-terminal network reduces to a source plus one resistance (Thévenin) or a current source plus a conductance (Norton). That is the tool that turns a battery bank with its cabling into the V₀ and r of chapter 4's model.","Nonlinear elements, diodes and the MOSFET switches inside a BMS, break superposition and need piecewise or iterative solutions."]),
}
CH[6]={
 'k5':("Nothing gets lost",None,["Electricity does not leak or pile up. At a fork, the flow in equals the flows out: 3 amps in, 1 amp one way, so 2 amps the other way.","Around any loop, the pushes and the drops cancel exactly: what the battery pushes up, the bulbs use down."]),
 'g8':("Kirchhoff's two laws",None,["KCL: at any junction, current in = current out. KVL: around any closed loop, voltage rises equal voltage drops.","Both are conservation laws. Charge is not created or destroyed, and energy per charge going round a loop comes back where it started."]),
 'hs':("Solving any resistor network",None,["KCL follows from conservation of charge; KVL from the electric field being conservative in circuits without changing magnetic flux. With Ohm's law they solve any resistor network: write KCL at each node in terms of unknown node voltages, then solve the linear system.","A bridge circuit cannot be reduced by series and parallel rules. Kirchhoff handles it."]),
 'col':("Nodal and mesh analysis",None,["Nodal analysis: G·v = i, where G is the conductance matrix; mesh analysis is its dual. The number of independent KVL equations is the cyclomatic number, branches − nodes + 1.","KVL fails as stated when flux through the loop changes: ∮E·dl = −dΦ/dt. That is the origin of induced voltages and of ground loops near transformers."]),
 'max':("The lumped-element limit",None,["Kirchhoff's laws are the lumped limit of Maxwell's equations, valid when the circuit is small compared to a wavelength and fields are confined to elements. KCL is ∇·J = −∂ρ/∂t with no charge accumulation outside capacitors; KVL is Faraday's law with flux assigned to inductors.","Beyond that limit you need transmission-line or full-field models. A 60 Hz grid is lumped over a city block and distributed over a continent."]),
}
CH[7]={
 'k5':("The push that wiggles",None,["Batteries push one way all the time. Wall outlets push back and forth, 60 times a second in the US and 50 in Europe. That is AC, alternating current. Lights do not flicker because it is too fast to see.","AC is used because its push is easy to change up and down with a transformer, which is how power travels across a country."]),
 'g8':("AC and RMS",None,["AC voltage swings like a wave. The 120 V on a US outlet is a kind of average called RMS; the peaks reach 170 V. The frequency is 60 Hz.","An inverter turns a battery's DC into AC so ordinary appliances can use it. Transformers only work with AC, which is why the grid is AC."]),
 'hs':("Root mean square",None,["v(t) = V_peak sin(2πft). RMS is the DC voltage that would deliver the same average power to a resistor: V_rms = V_peak/√2, so 120 V RMS ≈ 170 V peak and 230 V ≈ 325 V peak.","Average power into a resistor is V_rms²/R. Meters read RMS; insulation must withstand the peaks."]),
 'col':("Phasors and three phases",None,["Represent v(t) by a complex amplitude and sinusoidal steady state turns differential equations into algebra. Three-phase power delivers constant instantaneous power over three conductors and drives motors with a rotating field; US residential split-phase gives 120/240 V from a center-tapped transformer.","Inverters synthesize the sine with pulse-width modulation; 'modified sine' inverters are square-ish and upset some loads."]),
 'max':("Why 50 or 60, and why DC came back",None,["The choice of frequency balanced transformer size (∝ 1/f) against line reactance and motor speeds. HVDC is now cheaper than AC beyond a few hundred kilometres because line charging current and reactive losses vanish, so grids are AC islands linked by DC.","Harmonics from switching loads distort the sine, raising RMS current and neutral heating in three-phase systems (the triplen harmonics)."]),
}
CH[8]={
 'k5':("Energy that sloshes",None,["Some parts store energy for a moment and give it back. A capacitor holds a bit of push; a coil holds a bit of flow. In AC that stored energy sloshes back and forth, and the wires carry it even though it does no work.","Real work is the part that stays. The rest just goes to and fro."]),
 'g8':("Power factor",None,["A motor draws current that lags behind the voltage; a capacitor draws current that runs ahead. Only the part of the current in step with the voltage delivers power. Power factor = real watts ÷ apparent volt-amps.","A 1,000 VA motor at power factor 0.8 does 800 W of work, but the wires carry current as if it were 1,000 W. That is why inverters are rated in VA."]),
 'hs':("Capacitors, inductors, reactive power",None,["Capacitance C = Q/V stores energy ½CV² in an electric field; inductance L stores ½LI² in a magnetic field. In AC they shift the current by ±90°.","Reactive power Q = VI sin φ sloshes without doing work; real power P = VI cos φ; apparent power S = VI. Power factor is cos φ. Utilities penalize a low power factor because it wastes wire capacity."]),
 'col':("Impedance",None,["Z = R + jX with X_L = ωL and X_C = −1/(ωC); phasor Ohm's law V = IZ; resonance at ω = 1/√(LC). Complex power S = VI* = P + jQ.","Power-factor correction adds parallel capacitance to cancel inductive Q. Switch-mode loads draw distorted current, so true power factor includes a distortion term: displacement × distortion."]),
 'max':("Field energy",None,["Energy is stored in fields, u = ½εE² + ½μH² per unit volume, and the Poynting flux of reactive power reverses direction twice per cycle, which is what 'sloshing' means precisely.","Transients solve the RLC differential equations; the Laplace transform generalizes phasors to arbitrary waveforms with the same impedance forms in s. Inductive kick, V = L di/dt when a motor is switched off, is why DC contactors need arc suppression."]),
}
CH[9]={
 'k5':("What actually moves",None,["Here is a surprise. The electrons in a wire crawl. When you flip a switch the light comes on at once, but not because electrons rush from the switch to the bulb.","It is like a hose that is already full of water: push at one end and water comes out the other end right away, even though each drop moves slowly. The push travels fast. The stuff travels slow."]),
 'g8':("Slow electrons, fast push",None,["Electrons in a household wire drift at about a tenth of a millimetre per second. The signal to start moving travels near the speed of light, because the push is carried by the electric field, which fills the space around the wire.","The wire is already full of charge; the switch just starts all of it moving at once."]),
 'hs':("Drift velocity",None,["v = I/(nqA). For 1 A in 1 mm² copper, with n ≈ 8.5 × 10²⁸ electrons per m³, v ≈ 0.07 mm/s. The field that pushes them is set up by charges on the wire's surface within nanoseconds.","The energy does not ride on the electrons. It flows in the electromagnetic field around the wires, from the source to the load."]),
 'col':("The Poynting picture",None,["S = E × H points from the battery toward the bulb in the space between the two wires. Integrate it over a surface around the bulb and you get exactly V × I. Inside a resistive wire S points inward, delivering the I²R heat.","This is the field-level meaning of P = VI: the wires guide the energy; they do not carry it."]),
 'max':("Surface charge and the speed of electricity",None,["Surface charge distributions on the conductors establish the field (Sommerfeld; Jackson §7; Galili and Goihbarg 2005). The transient after a switch closes propagates at about c/√ε_r of the surrounding insulation as a transmission-line wave, which is what sets the 'speed of electricity'.","The DC Poynting picture is exact in steady state and is the reason a lossless conductor can deliver energy that never enters it."]),
}
CH[10]={
 'k5':("The system checker",None,["Now you can check any setup with six questions. How much push (volts)? How many watts does the thing use? How much flow is that (watts ÷ volts)? How big is the bucket (watt-hours)? How long will it last (bucket ÷ watts)? What gets wasted?","Try it with the checker."]),
 'g8':("The analysis sequence",None,["1 Identify the voltage. 2 Identify load or source power. 3 Current = P ÷ V. 4 Battery Wh, or V × Ah. 5 Ideal time = Wh ÷ W. 6 Apply efficiency. 7 Check startup surge: motors draw 3 to 7× for a moment. 8 Check wire, fuse, connectors, BMS limits, grounding, and the manufacturer's numbers.","Every number has a unit. Say it out loud."]),
 'hs':("Surge, wire, fuse, ground",None,["A compressor rated 800 W may pull 4,000 W for half a second, so the inverter's surge rating and the BMS discharge limit both matter. Pick wire gauge from current with a margin, then check voltage drop, aiming under 3%.","Fuses are sized for the wire, not the load; they protect the cable from the battery, which can deliver thousands of amps into a short. Ground gives a common reference and a fault path."]),
 'col':("Sizing as a constraint problem",None,["Inverter continuous and surge VA, BMS continuous and peak amps, cable ampacity and voltage drop, breaker curves, battery C-rate (a 100 Ah cell at 1C delivers 100 A), and temperature derating all have to be satisfied at once.","Solar: array watts × sun-hours × system efficiency (≈ 0.75) gives daily Wh; compare with the load's daily Wh, then size storage for the days of autonomy you need."]),
 'max':("Beyond the checklist",None,["Fault current and arc-flash energy in large battery banks, protective-device coordination, the grounding scheme (earthed versus floating DC), EMI from inverter switching, and the thermal model of the enclosure.","Each is a chapter of the electrical code, and each is why the last item on the list is 'manufacturer limits'."]),
}
GROWN={
 1:"The single most useful thing an adult can reinforce: watts is a speed, watt-hours is an amount. Ask 'rate or amount?' every time a number comes up.",
 2:"The water analogy is good for push and flow and breaks for resistance in one way: squeezing a hose slows water everywhere in the hose at once, which is actually correct for circuits too.",
 3:"If a child asks why the big power lines are so high up: the push on them is huge, so they must be far from anything. Same reason the flow is small.",
 4:"Kids can check the label on any battery in the house: it will say Ah or Wh or both. Multiplying Ah by volts to get Wh is the whole lesson.",
 5:"A flashlight with two batteries is series; a TV remote with two side by side is usually series too. Parallel is rarer in toys, which is a good puzzle to pose.",
 6:"Both laws are 'nothing is lost' rules. Children accept them readily; the interesting part is the fork.",
 7:"If there is an old incandescent bulb and a phone camera, filming it in slow motion can sometimes show the 120 Hz flicker.",
 8:"This chapter is hard at any level. The sloshing image is enough for now.",
 9:"Most adults do not know this either. The hose picture is exact enough to keep for life.",
 10:"The checker is real: it is the same sequence an installer runs. Let kids plug in the numbers from a real appliance label.",
}
# ---- units for the teach-back checks ----
UNITS=[('W','watts'),('kW','kilowatts'),('Wh','watt-hours'),('kWh','kilowatt-hours'),('J','joules'),('V','volts'),('A','amps'),('Ah','amp-hours'),('Ω','ohms'),('VA','volt-amps'),('Hz','hertz'),('h','hours'),('mm','millimetres'),('mm/s','millimetres per second'),('×c','times the speed of light'),('n','a plain count')]
UNIT_WHY={'W':'watts are a rate: how fast energy moves','kW':'kilowatts are a rate: how fast energy moves','Wh':'watt-hours are an amount of energy','kWh':'kilowatt-hours are an amount of energy','J':'joules are an amount of energy','V':'volts measure the push','A':'amps measure the flow','Ah':'amp-hours measure flow × time, not energy','Ω':'ohms measure opposition','VA':'volt-amps are apparent power, not real work','Hz':'hertz count cycles per second','h':'hours are a time','mm':'millimetres are a distance','mm/s':'millimetres per second is a speed','×c':'a fraction of the speed of light','n':'a plain count, no unit'}
# CHECK[n][level] = (question, answer, unit, tolerance fraction, hint, ok-text)
CHECK={
 1:{'k5':("A tap pours 250 W. The bucket holds 2,500 Wh. How many hours does it last?",10,'h',.02,"Hours = watt-hours ÷ watts. Bucket ÷ tap.","Right. 2,500 ÷ 250 = 10 hours. Amount ÷ rate = time."),
    'g8':("Two 250 W panels charge a 2,500 Wh battery. How many ideal hours?",5,'h',.02,"Two panels make 500 W. Wh ÷ W.","Right. 500 W together, 2,500 ÷ 500 = 5 hours."),
    'hs':("A 60 W bulb runs for 8 hours. How much energy did it use?",480,'Wh',.02,"Energy = power × time. Watts × hours gives watt-hours.","Right. 60 W × 8 h = 480 Wh, an amount of energy."),
    'col':("How many joules in 1.5 kWh?",5400000,'J',.02,"1 Wh = 3,600 J, and 1.5 kWh = 1,500 Wh.","Right. 1,500 Wh × 3,600 J/Wh = 5.4 MJ."),
    'max':("A load draws 300 W for 90 minutes. Energy in kWh?",0.45,'kWh',.02,"90 minutes is 1.5 hours. 300 W × 1.5 h in Wh, then ÷ 1,000.","Right. 450 Wh = 0.45 kWh.")},
 2:{'k5':("12 volts of push, 6 ohms of opposition. Flow = push ÷ opposition = ?",2,'A',.02,"Divide the volts by the ohms. The answer is a flow.","Right. 12 ÷ 6 = 2 amps of flow."),
    'g8':("24 V across 8 Ω. How many amps?",3,'A',.02,"I = V ÷ R.","Right. 24 ÷ 8 = 3 A."),
    'hs':("2 A flows through 30 Ω. What is the voltage across it?",60,'V',.02,"V = I × R.","Right. 2 A × 30 Ω = 60 V."),
    'col':("Resistance of 10 m of copper wire with 1 mm² cross-section? (ρ = 1.7 × 10⁻⁸ Ω·m)",0.17,'Ω',.06,"R = ρL/A. Convert 1 mm² to 10⁻⁶ m².","Right. 1.7e-8 × 10 ÷ 1e-6 = 0.17 Ω."),
    'max':("Drift speed for 1 A in 1 mm² copper, n = 8.5 × 10²⁸ m⁻³? (mm/s)",0.074,'mm/s',.3,"v = I/(nqA) with q = 1.6 × 10⁻¹⁹ C and A = 10⁻⁶ m².","Right. About 0.07 mm/s: electrons crawl.")},
 3:{'k5':("1,200 W at 12 V. How many amps of flow?",100,'A',.02,"Amps = watts ÷ volts.","Right. 1,200 ÷ 12 = 100 A. That needs a very thick wire."),
    'g8':("1,200 W at 48 V. How many amps?",25,'A',.02,"I = P ÷ V.","Right. 25 A: four times the volts, a quarter of the amps."),
    'hs':("25 A through a 0.05 Ω cable. Power lost as heat?",31.25,'W',.03,"P = I²R.","Right. 625 × 0.05 = 31.25 W lost in the cable."),
    'col':("Line loss is 500 W at 120 V. Same delivered power at 480 V: loss?",31.25,'W',.03,"Loss scales as (P/V)²R: four times the voltage, one-sixteenth the loss.","Right. 500 ÷ 16 = 31.25 W."),
    'max':("Skin depth in copper at 60 Hz, in mm? (ρ = 1.7e-8 Ω·m, μ₀ = 4π × 10⁻⁷)",8.5,'mm',.15,"δ = √(2ρ/(ωμ)) with ω = 2π × 60.","Right. About 8.5 mm, so a 2 cm busbar is not fully used at 60 Hz.")},
 4:{'k5':("A 12 V battery holds 100 Ah. How many watt-hours?",1200,'Wh',.02,"Multiply amp-hours by volts.","Right. 12 × 100 = 1,200 Wh of energy."),
    'g8':("1,280 Wh battery, 90% efficient inverter, 300 W load. Hours?",3.84,'h',.03,"Usable = 1,280 × 0.9. Then ÷ 300.","Right. 1,152 Wh ÷ 300 W = 3.84 h."),
    'hs':("12.8 V battery, 0.02 Ω internal resistance, delivering 50 A. Terminal voltage?",11.8,'V',.02,"V = V₀ − I·r.","Right. 12.8 − 1.0 = 11.8 V: that is voltage sag."),
    'col':("Maximum power from V₀ = 12.8 V with r = 0.02 Ω?",2048,'W',.03,"P_max = V₀²/(4r).","Right. 163.84 ÷ 0.08 = 2,048 W, at 50% efficiency, so never operate there."),
    'max':("An inverter idles at 30 W for 10 hours. Energy wasted in kWh?",0.3,'kWh',.02,"30 W × 10 h = 300 Wh.","Right. 0.3 kWh, a quarter of a small battery, gone overnight.")},
 5:{'k5':("Four 3 V cells in a chain. How many volts?",12,'V',.02,"Pushes add in a chain.","Right. 3 + 3 + 3 + 3 = 12 V."),
    'g8':("Two 100 Ah batteries side by side. Total amp-hours?",200,'Ah',.02,"In parallel the buckets add.","Right. 200 Ah at the same voltage."),
    'hs':("Two 10 Ω resistors in parallel?",5,'Ω',.02,"1/R = 1/10 + 1/10.","Right. 5 Ω: less than either alone."),
    'col':("16 cells × 3.2 V in series, three such strings in parallel, 100 Ah per string. Total energy?",15360,'Wh',.02,"51.2 V × 300 Ah.","Right. 15,360 Wh, about 15 kWh."),
    'max':("Thévenin resistance of two 0.02 Ω cells in parallel?",0.01,'Ω',.02,"Parallel resistances halve when equal.","Right. 0.01 Ω.")},
 6:{'k5':("3 amps flow into a fork. 1 amp goes one way. How much goes the other way?",2,'A',.02,"In equals out.","Right. 3 − 1 = 2 A."),
    'g8':("A 12 V battery drives two bulbs in a loop. One drops 5 V. The other drops?",7,'V',.02,"Rises equal drops around a loop.","Right. 12 − 5 = 7 V."),
    'hs':("4 Ω and 2 Ω in series across 12 V. Voltage across the 4 Ω?",8,'V',.02,"Current is 12 ÷ 6 = 2 A; then V = IR.","Right. 2 A × 4 Ω = 8 V."),
    'col':("A circuit has 6 branches and 4 nodes. Independent KVL equations?",3,'n',.01,"branches − nodes + 1.","Right. 6 − 4 + 1 = 3."),
    'max':("A 1 m² loop with flux changing at 0.1 T/s. Induced EMF?",0.1,'V',.02,"EMF = −dΦ/dt, and Φ = B × A.","Right. 0.1 V around the loop: KVL as stated no longer holds.")},
 7:{'k5':("US outlets wiggle back and forth how many times a second?",60,'Hz',.01,"Sixty in the US, fifty in Europe.","Right. 60 Hz."),
    'g8':("120 V RMS at the outlet. How high are the peaks?",170,'V',.03,"Peak = RMS × 1.414.","Right. About 170 V at the peaks."),
    'hs':("325 V peak. RMS?",230,'V',.02,"RMS = peak ÷ √2.","Right. 230 V: a European outlet."),
    'col':("Average power from 120 V RMS into a 12 Ω heater?",1200,'W',.02,"P = V_rms²/R.","Right. 14,400 ÷ 12 = 1,200 W."),
    'max':("The third harmonic of 60 Hz, which adds in a three-phase neutral?",180,'Hz',.01,"3 × 60.","Right. 180 Hz, a triplen harmonic.")},
 8:{'k5':("A motor uses 1,000 VA at power factor 0.8. Real watts of work?",800,'W',.02,"Real = apparent × power factor.","Right. 800 W does work; the rest sloshes."),
    'g8':("A 600 W motor at power factor 0.75. Apparent power?",800,'VA',.02,"VA = W ÷ power factor.","Right. 800 VA: the inverter must be rated for that."),
    'hs':("Energy stored in a 1,000 µF capacitor at 400 V?",80,'J',.02,"E = ½CV². 1,000 µF = 0.001 F.","Right. 0.5 × 0.001 × 160,000 = 80 J."),
    'col':("Reactance of a 10 mH inductor at 60 Hz?",3.77,'Ω',.03,"X = 2πfL.","Right. 2π × 60 × 0.01 ≈ 3.77 Ω."),
    'max':("Resonant frequency of 10 mH with 100 µF?",159,'Hz',.03,"f = 1/(2π√(LC)).","Right. About 159 Hz.")},
 9:{'k5':("Electrons drift 0.1 mm each second. How far in 10 seconds?",1,'mm',.02,"Speed × time.","Right. 1 mm. That slow."),
    'g8':("At 0.1 mm/s, how far does an electron drift in one minute?",6,'mm',.02,"60 seconds × 0.1 mm.","Right. 6 mm in a minute, while the light came on instantly."),
    'hs':("Drift speed for 2 A in 1 mm² copper? (mm/s)",0.15,'mm/s',.25,"Twice the current of the 1 A case, so twice the speed.","Right. About 0.15 mm/s."),
    'col':("Total Poynting flux through a surface enclosing a 12 V, 5 A bulb?",60,'W',.02,"It equals V × I exactly.","Right. 60 W enters through the field, not the wire."),
    'max':("Signal speed in a cable with ε_r = 2.25, as a fraction of c?",0.667,'×c',.03,"v = c/√ε_r.","Right. Two-thirds of c.")},
 10:{'k5':("A 48 V system runs a 1,200 W load. How many amps?",25,'A',.02,"Watts ÷ volts.","Right. 25 A."),
    'g8':("A 5,120 Wh battery runs a 1,200 W load. Ideal hours?",4.27,'h',.03,"Wh ÷ W.","Right. About 4.3 hours before losses."),
    'hs':("Same, with a 90% efficient inverter. Real hours?",3.84,'h',.03,"Multiply the ideal time by 0.9.","Right. About 3.8 hours."),
    'col':("Surge of 5× on a 1,200 W load at 48 V. Peak amps?",125,'A',.02,"6,000 W ÷ 48 V.","Right. 125 A for a moment: the BMS peak limit must allow it."),
    'max':("A 2,000 W array, 5 sun-hours, 75% system efficiency. Daily Wh?",7500,'Wh',.02,"W × h × efficiency.","Right. 7,500 Wh a day.")},
}
FIG={
 1:'''<div class="panel"><canvas id="cv-energy" aria-label="A battery as a bucket of watt-hours draining into a bulb and filling from solar panels. Sliders set the watts."></canvas></div>
    <div class="controls"><label class="slider">Bulb (watts) <input type="range" id="en-load" min="0" max="1000" step="10" value="250"><span class="val" id="en-load-val">250 W</span></label><label class="slider">Panels (watts) <input type="range" id="en-src" min="0" max="1000" step="25" value="0"><span class="val" id="en-src-val">0 W</span></label><button class="btn" id="en-reset">Refill to 2,500 Wh</button></div>
    <figcaption><b>Try this:</b> set the bulb to 250 W and read how long a 2,500 Wh bucket lasts. Then add panels and watch the net rate.</figcaption>''',
 2:'''<div class="panel"><canvas id="cv-ohm" aria-label="A simple circuit. Sliders set the push in volts and the opposition in ohms; the flow in amps and the bulb brightness follow."></canvas></div>
    <div class="controls"><label class="slider">Push (volts) <input type="range" id="ohm-v" min="1" max="48" step="1" value="12"><span class="val" id="ohm-v-val">12 V</span></label><label class="slider">Opposition (ohms) <input type="range" id="ohm-r" min="1" max="48" step="1" value="6"><span class="val" id="ohm-r-val">6 Ω</span></label></div>
    <figcaption><b>Try this:</b> double the push and watch the flow double. Double the opposition and watch it halve.</figcaption>''',
 3:'''<div class="panel"><canvas id="cv-power" aria-label="Deliver a chosen number of watts through a cable at a chosen system voltage. The cable glows with its losses."></canvas></div>
    <div class="controls"><span class="lbl">System</span><button class="btn is-on" data-sysv="12">12 V</button><button class="btn" data-sysv="24">24 V</button><button class="btn" data-sysv="48">48 V</button><button class="btn" data-sysv="120">120 V</button><button class="btn" data-sysv="240">240 V</button><label class="slider">Load <input type="range" id="pw-load" min="100" max="3000" step="50" value="1200"><span class="val" id="pw-load-val">1,200 W</span></label><label class="slider" data-lv="hs col max">Cable <input type="range" id="pw-r" min="0.01" max="0.2" step="0.01" value="0.05"><span class="val" id="pw-r-val">0.05 Ω</span></label></div>
    <figcaption><b>Try this:</b> deliver 1,200 W at 12 V, then at 48 V. Watch the amps and the cable's glow.</figcaption>''',
 4:'''<div class="panel"><canvas id="cv-battery" aria-label="A battery discharging into a load through an inverter, with voltage sag, cutoff, and real versus ideal run time."></canvas></div>
    <div class="controls"><span class="lbl">Battery</span><button class="btn is-on" data-bv="12.8">12.8 V</button><button class="btn" data-bv="25.6">25.6 V</button><button class="btn" data-bv="51.2">51.2 V</button><label class="slider">Amp-hours <input type="range" id="bt-ah" min="20" max="300" step="10" value="100"><span class="val" id="bt-ah-val">100 Ah</span></label><label class="slider">Load <input type="range" id="bt-load" min="50" max="3000" step="50" value="300"><span class="val" id="bt-load-val">300 W</span></label><label class="slider">Inverter <input type="range" id="bt-eff" min="70" max="100" step="1" value="90"><span class="val" id="bt-eff-val">90%</span></label><button class="btn" id="bt-reset">Recharge</button></div>
    <figcaption><b>Try this:</b> compare the ideal hours with the real hours. <span data-lv="hs col max">Watch the terminal voltage sag under a heavy load and the BMS cut off.</span></figcaption>''',
 5:'''<div class="panel"><canvas id="cv-series" aria-label="Cells arranged in series or parallel, with the total volts and amp-hours shown."></canvas></div>
    <div class="controls"><button class="btn" id="sp-add">Add a cell</button><button class="btn" id="sp-remove">Remove a cell</button><span class="sep"></span><button class="btn is-on" id="sp-series" aria-pressed="true">Series</button><button class="btn" id="sp-parallel" aria-pressed="false">Parallel</button></div>
    <figcaption><b>Try this:</b> build a 12.8 V pack from 3.2 V cells, then flip to parallel and watch what adds instead.</figcaption>''',
 6:'''<div class="panel"><canvas id="cv-kirch" aria-label="A fork where currents split, and a loop where voltage drops add up to the battery voltage."></canvas></div>
    <div class="controls"><label class="slider">Into the fork <input type="range" id="k-in" min="0.5" max="10" step="0.1" value="3"><span class="val" id="k-in-val">3.0 A</span></label><label class="slider">Branch one <input type="range" id="k-r1" min="1" max="20" step="1" value="6"><span class="val" id="k-r1-val">6 Ω</span></label><label class="slider">Branch two <input type="range" id="k-r2" min="1" max="20" step="1" value="6"><span class="val" id="k-r2-val">6 Ω</span></label></div>
    <figcaption><b>Try this:</b> change the branches and watch the two currents always add up to what came in. The loop below shows the drops adding up to the push.</figcaption>''',
 7:'''<div class="panel"><canvas id="cv-ac" aria-label="An alternating voltage wave with its peak and RMS marked, and a bulb that flickers when the wave is slowed down."></canvas></div>
    <div class="controls"><label class="slider">Frequency <input type="range" id="ac-f" min="0.5" max="60" step="0.5" value="60"><span class="val" id="ac-f-val">60 Hz</span></label><span class="lbl">Outlet</span><button class="btn is-on" data-acv="120">120 V</button><button class="btn" data-acv="230">230 V</button></div>
    <figcaption><b>Try this:</b> slow the wave to 1 Hz and watch the bulb flicker. Read the peak and the RMS.</figcaption>''',
 8:'''<div class="panel"><canvas id="cv-pf" aria-label="Voltage and current waves with an adjustable phase shift, the instantaneous power shaded, and real, reactive and apparent power read out."></canvas></div>
    <div class="controls"><label class="slider">Phase shift <input type="range" id="pf-phi" min="-90" max="90" step="1" value="0"><span class="val" id="pf-phi-val">0°</span></label></div>
    <figcaption><b>Try this:</b> shift the current behind the voltage like a motor, then ahead like a capacitor. Watch how much of the power is real.</figcaption>''',
 9:'''<div class="panel"><canvas id="cv-drift" aria-label="A battery, two wires and a bulb. Electrons crawl inside the wires while the signal races along the outside."></canvas></div>
    <div class="controls"><button class="btn" id="dr-switch">Flip the switch</button><label class="slider">Current <input type="range" id="dr-i" min="0" max="10" step="0.5" value="2"><span class="val" id="dr-i-val">2 A</span></label></div>
    <figcaption><b>Try this:</b> flip the switch and watch the signal beat the electrons to the bulb. <span data-lv="col max">The arrows between the wires are the Poynting vector: where the energy actually travels.</span></figcaption>''',
 10:'''<div class="panel"><canvas id="cv-check" class="short" aria-label="A report card for an electrical system: current, run time, charge time, surge, wire size and warnings."></canvas></div>
    <div class="controls"><label class="slider">System V <select id="sc-v"><option>12</option><option>24</option><option selected>48</option><option>120</option></select></label><label class="slider">Load W <input type="number" id="sc-load" value="1200" min="1" style="width:5.5rem"></label><label class="slider">Surge × <input type="number" id="sc-surge" value="3" min="1" max="10" step="0.5" style="width:4.5rem"></label><label class="slider">Battery Wh <input type="number" id="sc-wh" value="5120" min="1" style="width:6rem"></label><label class="slider">Inverter % <input type="number" id="sc-eff" value="90" min="50" max="100" style="width:4.5rem"></label><label class="slider">Source W <input type="number" id="sc-src" value="1500" min="0" style="width:5.5rem"></label><label class="slider">Cable m <input type="number" id="sc-len" value="3" min="0.5" step="0.5" style="width:4.5rem"></label><button class="btn primary" id="sc-run">Run the checker</button></div>
    <figcaption><b>Try this:</b> plug in a real setup and read the report. Change the system voltage and watch the wire size and the warnings change.</figcaption>''',
}
ALL=['k5','g8','hs','col','max']
MISSIONS=[
 ('e1','ch1',ALL,"Set the bulb to 250 W with no panels and read how long the 2,500 Wh bucket lasts."),
 ('e1b','ch1',['g8','hs','col','max'],"Add enough panel watts that the bucket fills instead of empties."),
 ('e2','ch2',ALL,"Make the flow exactly 2 amps."),
 ('e3','ch3',ALL,"Deliver 1,200 W with the cable losing less than 50 W."),
 ('e4','ch4',ALL,"Run a 300 W load on a 12.8 V, 100 Ah battery with a 90% inverter and read the real hours."),
 ('e4b','ch4',['hs','col','max'],"Load the battery hard enough that the BMS cuts it off early."),
 ('e5','ch5',ALL,"Build a 12.8 V pack from 3.2 V cells."),
 ('e5b','ch5',['g8','hs','col','max'],"Flip the same cells to parallel and read the amp-hours."),
 ('e6','ch6',ALL,"Make the two branches carry different currents that still add up to what came in."),
 ('e7','ch7',ALL,"Slow the wave to 1 Hz and watch the bulb flicker."),
 ('e8','ch8',ALL,"Set the phase so the power factor is 0.8."),
 ('e9','ch9',ALL,"Flip the switch and watch the signal beat the electrons."),
 ('e10','ch10',ALL,"Run the checker on a 48 V, 1,200 W load with a 5,120 Wh battery and a 90% inverter."),
]+[(f'tb{n}',f'ch{n}',ALL,"Teach it back: answer the check question below with the right unit.") for n in range(1,11)]
CLOSING=("Rate, amount, push, flow, opposition.","Five words, ten chapters, and you can now read any electrical system from the label to the wire. Go look at one.")
