const {C,rgba,clamp,dist,$,fmt,sup,pct,text,circle,glow,shade,poly,rr,box,marble,readout,arrow,rng,at,makeSim,hook,slide}=Chalk;
const sfx=Chalk.sfx;
/* The Pulse: every floor is something that beats. The screen always beats at the same calm tempo; what changes is how much time one beat is. */
const PS=1.4,HEART=.83,TAU=Math.PI*2;
/* floor: id, name, one pulse (s), unit (one) / units (many), scene, pulse-line shape, colour, what is happening (first look), more (closer and deeper) */
const DOWN=[
 {id:'heart',short:'Heartbeat',name:'Your heartbeat',T:.83,one:'heartbeat',many:'heartbeats',scene:'heart',wave:'ecg',col:C.pink,k5:'This is your heart. Everything has a heartbeat. It just depends how far you look.',more:'About 72 beats a minute at rest: three billion in a lifetime.'},
 {id:'bird',short:'Hummingbird',name:'A hummingbird’s wings',T:.02,one:'wingbeat',many:'hummingbird wingbeats',scene:'bird',wave:'sine',col:C.green,k5:'A hummingbird’s wings beat so fast they hum. That is where its name comes from.',more:'About 50 beats a second, fast enough to hover in one place like a helicopter.'},
 {id:'sound',short:'The note A',name:'The note A',T:1/440,one:'sound wave',many:'sound waves of the note A',scene:'sound',wave:'sine',col:C.yellow,k5:'Sound is air pulsing. The note an orchestra tunes to pushes the air back and forth 440 times a second.',more:'You can hear this rhythm: your ear counts the pulses and your brain turns their speed into pitch. Faster pulses sound higher.'},
 {id:'cesium',short:'Atomic clock',name:'The atom that sets the clock',T:1/9192631770,one:'tick of the atomic clock',many:'ticks of the atomic clock',scene:'cesium',wave:'tick',col:C.blue,k5:'Deep inside a cesium atom something flips back and forth. The second is defined by this tick.',more:'One second is exactly 9,192,631,770 of these ticks. The world’s official time is kept by atomic clocks, and your phone’s clock is corrected from it.'},
 {id:'bond',short:'Molecule',name:'A molecule wobbles',T:1.1e-14,one:'wobble',many:'molecule wobbles',scene:'bond',wave:'sine',col:C.pink,k5:'The atoms in a molecule are joined like balls on a spring, and they never stop wobbling.',more:'A carbon–hydrogen bond stretches and squeezes about 90 trillion times a second. It never stops, not even at absolute zero, and chemists identify molecules by these wobbles.'},
 {id:'light',short:'Light wave',name:'One wave of light',T:1.8e-15,one:'wave of light',many:'waves of light',scene:'light',wave:'sine',col:C.green,k5:'Light is a wave. Green light rises and falls this fast as it flies.',more:'Green light wiggles about 560 trillion times a second. Your eye reads the speed of the wiggle as colour.'},
 {id:'electron',short:'Electron',name:'An electron goes round',T:1.5e-16,one:'lap of the electron',many:'electron laps',scene:'electron',wave:'sine',col:C.blue,k5:'In the simplest picture of an atom, a tiny electron circles the middle, over and over.',more:'In hydrogen that lap takes about 150 attoseconds. The real electron is a cloud, but the timescale is real: attosecond flashes of light now film electrons moving (Nobel Prize, 2023).'},
 {id:'planck',short:'Planck time',name:'The Planck time',T:5.39e-44,one:'Planck time',many:'Planck times',scene:'foam',wave:'noise',col:C.yellow,k5:'Down here there is no steady beat at all. Nobody knows what happens. Tap A to poke it.',more:'5.4 × 10⁻⁴⁴ seconds. Below this, our ideas of before and after may stop working. No experiment has come close.'},
];
const UP=[
 DOWN[0],
 {id:'breath',short:'Breath',name:'Your breath',T:4,one:'breath',many:'breaths',scene:'breath',wave:'breath',col:C.blue,k5:'Breathe in… and out. About every four seconds your whole body takes in air.',more:'Twelve to twenty breaths a minute at rest, over half a billion in a life.'},
 {id:'tide',short:'Tide',name:'The tide',T:44700,one:'tide',many:'tides',scene:'tide',wave:'sine',col:C.blue,k5:'The sea breathes too. For about six hours it comes in, for about six hours it goes out.',more:'One full tide takes 12 hours 25 minutes. The Moon’s pull drags the oceans into a bulge that the Earth turns under.'},
 {id:'tree',short:'Trees breathe',name:'Trees breathe',T:86400,one:'day',many:'days',scene:'tree',wave:'breath',col:C.green,k5:'By day a tree breathes in carbon dioxide and breathes out oxygen. At night it breathes the other way.',more:'Leaves open tiny mouths called stomata in sunlight to make food from air. At night only the breathing-out goes on.'},
 {id:'moon',short:'Moon',name:'The Moon waxes and wanes',T:2.55e6,one:'moon',many:'moons',scene:'moon',wave:'sine',col:C.chalk,k5:'The Moon grows from a sliver to full and back again, over and over.',more:'29.5 days from new moon to new moon. The word month comes from moon.'},
 {id:'planet',short:'Planet breathes',name:'The planet breathes',T:3.156e7,one:'year',many:'years',scene:'planet',wave:'sine',col:C.green,k5:'Every spring the northern forests grow leaves and breathe in carbon dioxide. Every autumn it comes back out. The whole Earth breathes once a year.',more:'Measured at Mauna Loa since 1958: the air’s carbon dioxide falls about 6 parts per million each summer and rises each winter, on top of a rise that people cause.'},
 {id:'cicada',short:'Cicadas',name:'The cicadas rise',T:17*3.156e7,one:'cicada cycle',many:'cicada cycles',scene:'cicada',wave:'spike',col:C.yellow,k5:'Some cicadas live underground for 17 years, then come up all together in one noisy summer.',more:'Periodical cicadas come up every 13 or 17 years, in their billions, then vanish underground again.'},
 {id:'ice',short:'Ice ages',name:'The ice ages come and go',T:1e5*3.156e7,one:'ice-age cycle',many:'ice-age cycles',scene:'ice',wave:'breath',col:C.chalk,k5:'The Earth breathes ice. Great ice sheets grow over the land, then melt away, then grow again.',more:'For the last million years the ice has come and gone about every 100,000 years, paced by slow wobbles in Earth’s orbit.'},
 {id:'galaxy',short:'Galactic year',name:'The Sun goes round the galaxy',T:2.3e8*3.156e7,one:'galactic year',many:'galactic years',scene:'galaxy',wave:'sine',col:C.yellow,k5:'The Sun and all its planets swing around the middle of the Milky Way. One lap is the slowest heartbeat we can see.',more:'About 230 million years a lap. The last time the Sun was here, the first dinosaurs were appearing.'},
];
/* pulse-line shapes: value in about [-1,1] for a phase fraction f, and where the beat peaks */
const WAVE={
 ecg:{peak:.3,f:f=>f<.12?.12*Math.sin(f/.12*Math.PI):f<.26?0:f<.3?-(f-.26)/.04*.25:f<.33?-.25+(f-.3)/.03*1.25:f<.37?1-(f-.33)/.04*1.45:f<.4?-.45+(f-.37)/.03*.45:f<.52?0:f<.68?.28*Math.sin((f-.52)/.16*Math.PI):0},
 sine:{peak:.25,f:f=>Math.sin(f*TAU)},
 breath:{peak:.35,f:f=>Math.sin(Math.pow(f,.9)*TAU)*.9},
 spike:{peak:.2,f:f=>f<.15?0:f<.2?(f-.15)/.05:f<.26?1-(f-.2)/.06*1.35:f<.45?-.35+(f-.26)/.19*.35:0},
 tick:{peak:.1,f:f=>f<.2?1:-.2},
 noise:{peak:-1,f:f=>Math.sin(f*97+Math.sin(f*31)*4)*.6+Math.sin(f*613.7)*.3+Math.sin(f*271.3+1.7)*.25},
};
function words(n){if(n<1000)return String(Math.round(n));const W=[[1e24,'septillion'],[1e21,'sextillion'],[1e18,'billion billion'],[1e15,'quadrillion'],[1e12,'trillion'],[1e9,'billion'],[1e6,'million'],[1e3,'thousand']];for(const [v,w] of W)if(n>=v){const x=n/v;return (x>=100?Math.round(x):x>=10?Math.round(x):x.toFixed(1).replace(/\.0$/,''))+' '+w}return String(Math.round(n))}
function dur(T){const Y=3.156e7;if(T>=Y*1e6)return words(T/Y)+' years';if(T>=Y)return (T/Y>=2?Math.round(T/Y).toLocaleString('en-US'):+(T/Y).toFixed(1))+' years';if(T>=86400*2)return +(T/86400).toFixed(1)+' days';if(T>=3600*1.5){const h=Math.floor(T/3600),m=Math.round((T-h*3600)/60);return `${h} hours${m?' '+m+' minutes':''}`}if(T>=86400)return '1 day';if(T>=1)return +T.toFixed(2)+' seconds';const U=[[1e-3,'milliseconds'],[1e-6,'microseconds'],[1e-9,'nanoseconds'],[1e-12,'picoseconds'],[1e-15,'femtoseconds'],[1e-18,'attoseconds'],[1e-21,'zeptoseconds'],[1e-24,'yoctoseconds']];for(const [v,u] of U)if(T>=v*.999){const x=T/v;return `${x>=10?Math.round(x):+x.toFixed(2)} ${u}`}return sci(T)}
function sci(S){const e=Math.floor(Math.log10(S)),m=S/Math.pow(10,e);return `${m.toFixed(1)} × 10${sup(e)} s`}
/* scenes: (ctx,x,y,R,p,s) with p the phase in cycles; one beat is one cycle */
const SC={};const fr=p=>p-Math.floor(p);const bump=p=>.5-.5*Math.cos(fr(p)*TAU);
SC.heart=(c,x,y,R,p)=>{const f=fr(p),k=WAVE.ecg.f(f);const s=1+Math.max(0,k)*.16;glow(c,x,y,R*1.2,C.pink,.18+.25*Math.max(0,k));c.save();c.translate(x,y);c.scale(s,s);c.fillStyle=rgba(C.pink,.35);c.strokeStyle=C.pink;c.lineWidth=3;c.beginPath();c.moveTo(0,R*.55);c.bezierCurveTo(-R*1.1,-R*.1,-R*.6,-R*.9,0,-R*.35);c.bezierCurveTo(R*.6,-R*.9,R*1.1,-R*.1,0,R*.55);c.fill();c.stroke();c.restore()};
SC.breath=(c,x,y,R,p)=>{const b=bump(p-.1);poly(c,[[x,y-R*.9],[x,y-R*.2]],C.chalk,3,.8);for(const sg of[-1,1]){c.save();c.translate(x+sg*R*.1,y-R*.15);c.scale(1+.18*b,1+.18*b);c.fillStyle=rgba(C.blue,.18+.2*b);c.strokeStyle=C.blue;c.lineWidth=2.5;c.beginPath();c.ellipse(sg*R*.35,R*.25,R*.33,R*.55,sg*.15,0,TAU);c.fill();c.stroke();c.restore()}text(c,b>.5?'in':'out',x,y+R*.95,{size:18,alpha:.6})};
SC.tide=(c,x,y,R,p,s)=>{const b=Math.sin(fr(p)*TAU),lvl=y+R*.1-b*R*.35;c.save();c.beginPath();c.rect(x-R*1.3,y-R,R*2.6,R*2);c.clip();poly(c,[[x-R*1.3,y+R*.8],[x+R*1.3,y-R*.1]],C.yellow,2.5,.7);c.fillStyle=rgba(C.yellow,.12);c.beginPath();c.moveTo(x-R*1.3,y+R*.8);c.lineTo(x+R*1.3,y-R*.1);c.lineTo(x+R*1.3,y+R);c.lineTo(x-R*1.3,y+R);c.fill();c.fillStyle=rgba(C.blue,.3);c.beginPath();c.moveTo(x-R*1.3,y+R);for(let i=0;i<=40;i++){const u=i/40,px=x-R*1.3+u*R*2.6;c.lineTo(px,lvl+Math.sin(u*18+s.t*2)*3)}c.lineTo(x+R*1.3,y+R);c.fill();c.strokeStyle=C.blue;c.lineWidth=2;c.beginPath();for(let i=0;i<=40;i++){const u=i/40,px=x-R*1.3+u*R*2.6;const py=lvl+Math.sin(u*18+s.t*2)*3;i?c.lineTo(px,py):c.moveTo(px,py)}c.stroke();c.restore();box(c,x+R*.55,y-R*.62,R*.18,R*.9,rgba(C.chalk,.15),C.chalk,4,2);text(c,b>0?'coming in':'going out',x-R*.6,y-R*.7,{size:16,color:C.blue,alpha:.8})};
SC.tree=(c,x,y,R,p)=>{const f=fr(p),day=Math.sin(f*TAU)>0;const a=Math.PI+f*TAU;const sx=x+Math.cos(a)*R*1.1,sy=y+R*.2+Math.sin(a)*R*.9;if(day){glow(c,sx,sy,R*.4,C.yellow,.5);circle(c,sx,sy,R*.12,C.yellow)}else{circle(c,x-Math.cos(a)*R*1.1,y+R*.2-Math.sin(a)*R*.9,R*.09,null,C.chalk,2)}
  poly(c,[[x-R*1.2,y+R*.7],[x+R*1.2,y+R*.7]],C.chalk,2,.5);poly(c,[[x,y+R*.7],[x,y]],C.chalk,6,.7);const lf=day?1:.6;for(const [ox,oy,r] of[[0,-.35,.45],[-.4,-.1,.35],[.4,-.1,.35]])circle(c,x+ox*R,y+oy*R,r*R,rgba(C.green,.12*lf+.05),C.green,2.5);
  const k=bump(p);for(let i=0;i<3;i++){const u=fr(p*2+i/3);const inw=day;const px=x+(i-1)*R*.5,py0=y-R*1.05,py1=y-R*.45;const py=inw?py0+(py1-py0)*u:py1+(py0-py1)*u;text(c,inw?'CO₂':'CO₂',px,py,{size:13,fam:'body',color:inw?C.chalk:C.pink,alpha:.35+.5*Math.sin(u*Math.PI)})}
  text(c,day?'day: breathing in CO₂, out O₂':'night: breathing out CO₂',x,y+R*.95,{size:15,alpha:.7})};
SC.moon=(c,x,y,R,p)=>{const f=fr(p);circle(c,x,y,R*.7,'#0d1512',rgba(C.chalk,.3),1.5);const k=Math.cos(f*TAU);c.save();c.beginPath();c.arc(x,y,R*.7,0,TAU);c.clip();c.fillStyle=rgba(C.chalk,.85);c.beginPath();if(f<.5){c.arc(x,y,R*.7,-Math.PI/2,Math.PI/2,false);c.ellipse(x,y,Math.abs(k)*R*.7,R*.7,0,Math.PI/2,-Math.PI/2,k>0)}else{c.arc(x,y,R*.7,Math.PI/2,-Math.PI/2,false);c.ellipse(x,y,Math.abs(k)*R*.7,R*.7,0,-Math.PI/2,Math.PI/2,k>0)}c.fill();c.restore()};
SC.planet=(c,x,y,R,p,s)=>{const f=fr(p);circle(c,x,y-R*.2,R*.45,rgba(C.blue,.25),C.blue,2.5);const g=Math.sin(f*TAU);c.save();c.beginPath();c.arc(x,y-R*.2,R*.45,Math.PI*1.05,Math.PI*1.95);c.lineTo(x,y-R*.2);c.fillStyle=g>0?rgba(C.green,.2+.4*g):rgba('#8a6a3a',.3-.2*g);c.fill();c.restore();text(c,g>0?'north: summer, leaves out':'north: winter, leaves gone',x,y-R*.8,{size:14,alpha:.7});
  const pts=[];for(let i=0;i<=60;i++){const u=i/60,ph=p-1.5+u*1.5;pts.push([x-R*1.1+u*R*2.2,y+R*.7-(-Math.sin(fr(ph)*TAU)*R*.18+u*R*.08)])}poly(c,pts,C.green,2.5,.9);text(c,'carbon dioxide in the air',x,y+R*.98,{size:13,fam:'body',alpha:.6})};
SC.cicada=(c,x,y,R,p,s)=>{const f=fr(p),up=f>.15&&f<.3;poly(c,[[x-R*1.2,y+R*.3],[x+R*1.2,y+R*.3]],C.chalk,2,.6);const g=rng(5);for(let i=0;i<22;i++){const px=x+(g()-.5)*R*2.2,dy=g()*R*.6;const py=up?y+R*.3-R*.5-dy*.8+Math.sin(s.t*20+i)*2:y+R*.45+dy*.6;c.save();c.fillStyle=up?C.yellow:rgba(C.yellow,.35);c.beginPath();c.ellipse(px,py,5,3,0,0,TAU);c.fill();c.restore()}if(up)text(c,'bzzzzzz',x,y-R*.6,{size:22,color:C.yellow});else text(c,'underground, waiting',x,y+R*.95,{size:15,alpha:.6})};
SC.ice=(c,x,y,R,p)=>{const b=bump(p);circle(c,x,y,R*.7,rgba(C.blue,.25),C.blue,2.5);c.save();c.beginPath();c.arc(x,y,R*.7,0,TAU);c.clip();c.fillStyle=rgba(C.chalk,.8);c.fillRect(x-R,y-R*.7,R*2,R*(.15+.45*b));c.fillRect(x-R,y+R*.7-R*(.12+.25*b),R*2,R*(.12+.25*b));c.restore();text(c,b>.5?'ice growing':'ice melting',x,y+R*.95,{size:15,alpha:.7})};
SC.galaxy=(c,x,y,R,p,s)=>{const a0=fr(p)*TAU;c.save();c.translate(x,y);c.scale(1,.55);for(let arm=0;arm<2;arm++){const pts=[];for(let i=0;i<60;i++){const u=i/60,a=a0*.15+arm*Math.PI+u*5;pts.push([Math.cos(a)*R*u*1.1,Math.sin(a)*R*u*1.1])}poly(c,pts,C.chalk,2,.5)}glow(c,0,0,R*.4,C.yellow,.5);const sa=-a0;const sx=Math.cos(sa)*R*.7,sy=Math.sin(sa)*R*.7;circle(c,sx,sy,5,C.yellow);c.restore();text(c,'the Sun',x+Math.cos(-a0)*R*.7,y+Math.sin(-a0)*R*.7*.55-14,{size:14,color:C.yellow})};
SC.bird=(c,x,y,R,p)=>{const a=Math.sin(fr(p)*TAU)*.95;c.save();c.translate(x,y);for(const sg of[-1,1]){c.save();c.rotate(sg*a*.8);c.fillStyle=rgba(C.green,.18);c.strokeStyle=C.green;c.lineWidth=2.5;c.beginPath();c.ellipse(sg*R*.55,-R*.05,R*.55,R*.14,sg*-.2,0,TAU);c.fill();c.stroke();c.restore()}c.fillStyle=rgba(C.green,.6);c.beginPath();c.ellipse(0,R*.05,R*.13,R*.35,0,0,TAU);c.fill();circle(c,0,-R*.32,R*.12,rgba(C.green,.8));poly(c,[[0,-R*.36],[0,-R*.7]],C.chalk,2);c.restore()};
SC.sound=(c,x,y,R,p)=>{const f=fr(p),sq=Math.sin(f*TAU);c.save();c.strokeStyle=C.chalk;c.lineWidth=4;c.lineCap='round';const gap=R*.14+sq*R*.03;c.beginPath();c.moveTo(x-R*.9-gap,y-R*.35);c.lineTo(x-R*.9-gap,y+R*.15);c.quadraticCurveTo(x-R*.9,y+R*.35,x-R*.9+gap,y+R*.15);c.lineTo(x-R*.9+gap,y-R*.35);c.moveTo(x-R*.9,y+R*.28);c.lineTo(x-R*.9,y+R*.7);c.stroke();c.restore();
  for(let k=0;k<4;k++){const u=fr(p-k)*.0+k+f;const rr=R*(.25+.28*u);c.save();c.strokeStyle=rgba(C.yellow,Math.max(0,.8-u*.18));c.lineWidth=2.5;c.beginPath();c.arc(x-R*.75,y-R*.1,rr,-.7,.7);c.stroke();c.restore()}text(c,'440 pushes of air a second',x+R*.2,y+R*.75,{size:14,alpha:.65})};
SC.cesium=(c,x,y,R,p)=>{const f=fr(p),on=f<.2;circle(c,x,y,R*.2,rgba(C.blue,.5),C.blue,2);for(const r of[.45,.75])circle(c,x,y,R*r,null,rgba(C.chalk,.3),1.5);const rr=on?.75:.45;circle(c,x+R*rr*.7,y-R*rr*.7,7,C.chalk);if(on)glow(c,x,y,R,C.blue,.35);text(c,on?'tick':'',x,y+R*.95,{size:22,color:C.blue})};
SC.bond=(c,x,y,R,p)=>{const s=R*(.55+.22*Math.sin(fr(p)*TAU));const pts=[];for(let i=0;i<=18;i++)pts.push([x-s+2*s*i/18,y+(i%2?1:-1)*R*.12*(i>0&&i<18?1:0)]);poly(c,pts,C.chalk,2,.8);circle(c,x-s,y,R*.32,rgba(C.pink,.55),C.pink,2.5);circle(c,x+s,y,R*.2,rgba(C.chalk,.5),C.chalk,2.5);text(c,'carbon',x-s,y+R*.55,{size:14,alpha:.6});text(c,'hydrogen',x+s,y+R*.45,{size:14,alpha:.6})};
SC.light=(c,x,y,R,p)=>{const pts=[];for(let i=0;i<=80;i++){const u=i/80;pts.push([x-R*1.2+u*R*2.4,y+Math.sin((u*2-p)*TAU)*R*.4])}poly(c,pts,C.green,3,.95);arrow(c,x+R*1.05,y+R*.6,R*.25,0,C.chalk,2)};
SC.electron=(c,x,y,R,p)=>{circle(c,x,y,R*.75,null,rgba(C.blue,.35),1.5);glow(c,x,y,R*.3,C.pink,.5);circle(c,x,y,R*.12,C.pink);const a=fr(p)*TAU;const ex=x+Math.cos(a)*R*.75,ey=y+Math.sin(a)*R*.75;glow(c,ex,ey,R*.2,C.blue,.6);circle(c,ex,ey,6,C.chalk)};
SC.foam=(c,x,y,R,p,s)=>{const g=rng(Math.floor(s.t*3));c.save();c.strokeStyle=C.yellow;c.lineWidth=1.5;c.globalAlpha=.6;for(let k=0;k<3;k++){c.beginPath();for(let i=0;i<=48;i++){const a=i/48*TAU,rr=R*(.35+k*.25)*(.8+g()*.4);i?c.lineTo(x+Math.cos(a)*rr,y+Math.sin(a)*rr):c.moveTo(x+Math.cos(a)*rr,y+Math.sin(a)*rr)}c.closePath();c.stroke()}c.restore();for(let i=0;i<24;i++)circle(c,x+(g()-.5)*R*2,y+(g()-.5)*R*2,1+g()*2.5,rgba(C.chalk,.7))};
function makeShaft(id,px,floors,outKey){
  const backKey=outKey==='down'?'up':'down';
  const s=makeSim(id,{
    init(s){s.i=0;s.p=0;s.trans=null;s.taps=[];s.good=0;s.synced=new Set();s.seen=new Set([floors[0].id]);s.poked=0;s.ring=[];s.pops=[];s.xray=false;try{s.xray=localStorage.getItem('chalk:xray')==='1'}catch(e){}},
    go(s,d){if(s.trans)return;const j=clamp(s.i+d,0,floors.length-1);if(j===s.i){sfx('no');return}const a=floors[s.i],b=floors[j];s.trans={from:s.i,to:j,t:0,len:(b.id==='planck'||a.id==='planck')?3:1.6};sfx(d>0?'push':'tick');s.good=0},
    say(s,t,col,size){s.pops.push({t,col:col||C.chalk,size:size||20,age:0})},
    tap(s){const F=floors[s.i];if(F.id==='planck'){s.poked++;s.say(s,['you poked the Planck time. Nobody knows what is down here.','maybe time comes in grains here','maybe there is no time at all here','gravity and quantum physics collide here'][(s.poked-1)%4],C.yellow,18);sfx('big');s.ring.push({t:0,good:true});return}
      const W=WAVE[F.wave],f=fr(s.p);let e=f-W.peak;if(e>.5)e-=1;if(e<-.5)e+=1;const good=Math.abs(e)<.13;s.ring.push({t:0,good});if(good){s.good++;sfx('blip');if(s.good===4){s.synced.add(F.id);s.say(s,`in sync: ${F.name}`,C.green,22);sfx('park')}}else{s.good=0}},
    step(dt,s){if(s.trans){s.trans.t+=dt/s.trans.len;if(s.trans.t>=1){s.i=s.trans.to;s.seen.add(floors[s.i].id);s.trans=null;s.p=0}}else s.p+=dt/PS;
      for(const r of s.ring)r.t+=dt;s.ring=s.ring.filter(r=>r.t<.6);for(const q of s.pops)q.age+=dt;s.pops=s.pops.filter(q=>q.age<2.6)},
    draw(s){const{ctx,w,h}=s;ctx.clearRect(0,0,w,h);const wide=w>=520;const gw=wide?Math.min(118,w*.2):34;const L=gw+10,W=w-L-10,cx=L+W/2;const lineY=h-58,lineH=34;const F0=floors[s.i];const capTxt=[F0.k5].concat(at('g8')?[F0.more]:[]);const capY=lineY-lineH-18-capTxt.length*17-(capTxt.join(' ').length>90?17:0);const cy=(100+capY-20)/2,R=Math.max(30,Math.min(W*.3,(capY-20-100)*.42));
      // the shaft
      const top=40,bot=h-40,n=floors.length;const yOf=i=>outKey==='down'?top+(bot-top)*i/(n-1):bot-(bot-top)*i/(n-1);poly(ctx,[[18,top],[18,bot]],C.chalk,2,.35);
      const pos=s.trans?s.trans.from+(s.trans.to-s.trans.from)*(.5-.5*Math.cos(Math.min(1,s.trans.t)*Math.PI)):s.i;
      floors.forEach((F,i)=>{const y=yOf(i),on=Math.round(pos)===i;if(F.id==='heart'){ctx.save();ctx.fillStyle=C.pink;ctx.font='16px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('♥',18,y);ctx.restore()}else circle(ctx,18,y,on?5:3,s.seen.has(F.id)?F.col:rgba(C.chalk,.35));if(wide)text(ctx,F.short,30,y,{size:12,fam:'body',align:'left',alpha:on?.95:.4,color:on?F.col:C.chalk})});
      const yy=outKey==='down'?top+(bot-top)*pos/(n-1):bot-(bot-top)*pos/(n-1);ctx.save();ctx.fillStyle=C.yellow;ctx.beginPath();ctx.moveTo(8,yy);ctx.lineTo(0,yy-5);ctx.lineTo(0,yy+5);ctx.closePath();ctx.fill();ctx.restore();
      if(s.trans){s.drawDive(s,ctx,cx,cy,W,L,lineY,lineH);return}
      const F=floors[s.i];
      // name and what one pulse is
      text(ctx,F.name,cx,30,{size:Math.min(34,W*.07),color:F.col});text(ctx,F.id==='planck'?'no steady pulse at all':`one pulse: ${dur(F.T)}`,cx,58,{size:14,fam:'body',alpha:.8});
      SC[F.scene](ctx,cx,cy,R,s.p,s);
      // the pulse line: same tempo on every floor, a different shape
      const Wv=WAVE[F.wave],pxp=W/3;ctx.save();ctx.strokeStyle=F.col;ctx.lineWidth=2.5;ctx.globalAlpha=.9;ctx.beginPath();for(let x=L;x<=L+W;x+=2){const ph=s.p-(L+W-x)/pxp;const v=Wv.f(fr(ph));const y=lineY-v*lineH*.8;x===L?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.stroke();ctx.restore();
      poly(ctx,[[L,lineY+lineH],[L+W,lineY+lineH]],C.chalk,1,.2);if(Wv.peak>=0){const hx=L+W;circle(ctx,hx,lineY-Wv.f(fr(s.p))*lineH*.8,4,C.chalk)}
      for(const r of s.ring){const u=r.t/.6;circle(ctx,L+W-6,lineY,8+u*30,null,rgba(r.good?C.green:C.chalk,1-u),2.5)}
      if(s.good>0&&s.good<4)text(ctx,'•'.repeat(s.good)+'◦'.repeat(4-s.good),L+W-40,lineY-lineH-10,{size:18,color:C.green});
      // your heart, for scale
      const hr=F.T/HEART;let you;if(F.id==='heart')you='';else if(F.id==='planck')you='your heart will not beat again for a very, very long time';else if(hr>1)you=`your heart beats ${words(hr)} times in one ${F.one}`;else you=`${words(1/hr)} ${F.many} between two of your heartbeats`;
      if(you){const buzz=hr>1?Math.sin(s.t*60)*1.5:0;ctx.save();const ysz=Math.min(12,(W-40)*1.9/you.length);ctx.font=`700 ${ysz}px Nunito, system-ui, sans-serif`;const tw=Math.min(ctx.measureText(you).width,W-30);ctx.restore();const hx=cx-tw/2-12;ctx.save();ctx.fillStyle=hr>1?C.pink:rgba(C.pink,.5);ctx.font='16px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('♥',hx+buzz,82);ctx.restore();text(ctx,you,hx+12,82,{size:Math.min(12,(W-40)*1.9/you.length),fam:'body',align:'left',alpha:.85,color:C.pink})}
      const cap=[F.k5];if(at('g8'))cap.push(F.more);readout(ctx,cap,cx,lineY-lineH-18-cap.length*17-(cap.join(' ').length>90?17:0),{align:'center',size:12});
      if(s.xray&&at('g8')){const lines=[`one pulse = ${sci(F.T)}`,`${words(1/F.T)} pulses per second`];if(at('hs'))lines.push(`f = 1/T = ${(1/F.T).toExponential(2)} Hz`);if(at('col'))lines.push(`10^${Math.log10(F.T).toFixed(1)} s: ${Math.abs(Math.log10(F.T/HEART)).toFixed(1)} powers of ten from your heart`);readout(ctx,lines,L+4,78,{size:12})}
      s.pops.forEach((q,i)=>{const u=q.age/2.6;text(ctx,q.t,cx,cy-R-14-i*24-u*10,{size:Math.min(q.size,W*1.8/Math.max(10,q.t.length)),color:q.col,alpha:u<.75?1:Math.max(0,1-(u-.75)/.25)})});
      if(s.i===0&&s.t<10&&cy-R>100)text(ctx,outKey==='down'?'press ▼ to go inside one heartbeat':'press ▲ to see slower heartbeats',cx,84,{size:17,color:C.yellow,alpha:.6+.3*Math.sin(s.t*3)})},
    drawDive(s,ctx,cx,cy,W,L,lineY,lineH){const T=s.trans,a=floors[T.from],b=floors[T.to],inward=b.T<a.T,u=T.t,ratio=inward?a.T/b.T:b.T/a.T;
      // one beat of the old floor stretches until it is flat, and the new beats appear inside it (or the other way round)
      const big=inward?a:b,small=inward?b:a;const z=inward?Math.pow(Math.min(ratio,60),u):Math.pow(Math.min(ratio,60),1-u);
      const Wa=WAVE[big.wave],Wb=WAVE[small.wave];const pxBig=W/3*z;
      ctx.save();ctx.strokeStyle=big.col;ctx.lineWidth=2.5;ctx.globalAlpha=inward?1-u*.8:.2+u*.8;ctx.beginPath();for(let x=L;x<=L+W;x+=2){const ph=.3+(x-cx)/pxBig;const y=lineY-Wa.f(fr(ph))*lineH*.8;x===L?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.stroke();ctx.restore();
      const pxSmall=W/3*z/Math.min(ratio,60)*1;ctx.save();ctx.strokeStyle=small.col;ctx.lineWidth=1.8;ctx.globalAlpha=inward?u:1-u;ctx.beginPath();for(let x=L;x<=L+W;x+=2){const ph=(x-cx)/Math.max(pxSmall,.5);const y=lineY-Wb.f(fr(ph))*lineH*.45;x===L?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.stroke();ctx.restore();
      const planck=b.id==='planck'||a.id==='planck';const head=inward?`Inside one ${a.one}:`:`One ${b.one} holds`;const count=planck?'about 3 × 10²⁷ Planck times: hundreds of millions of times more than all the grains of sand on Earth':`${words(ratio)} ${inward?b.many:a.many}`;
      text(ctx,head,cx,cy-30,{size:22,alpha:clamp(u*3,0,1)});text(ctx,count,cx,cy+14,{size:Math.min(planck?20:38,W*1.7/Math.max(10,count.length)),color:b.col,alpha:clamp((u-.25)*3,0,1)});
      if(!planck&&at('g8'))text(ctx,`${dur(a.T)} ÷ ${dur(b.T)}`,cx,cy+50,{size:14,fam:'body',alpha:clamp((u-.4)*3,0,.7)})}
  });
  if(!s)return null;
  Chalk.pad(s,{labels:{[outKey]:outKey==='down'?'faster pulse':'slower pulse',[backKey]:'back toward your heart',a:'tap the beat',b:'x-ray',start:'your heart'},help:`<b>${outKey==='down'?'▼':'▲'}</b> dives ${outKey==='down'?'inside one beat to a faster pulse':'out to a slower pulse'}, <b>${outKey==='down'?'▲':'▼'}</b> comes back. Tap <b>A</b> on the beat: four in a row and you are in sync. <b>B</b> shows the numbers.<span class="keys"> Keys: arrows, <kbd>Z</kbd> or <kbd>Space</kbd>, <kbd>X</kbd>, <kbd>Enter</kbd>.</span>`,
    on(k,d){if(!d)return;if(k===outKey)s.go(s,1);else if(k===backKey)s.go(s,-1);else if(k==='a'){if(!s.trans)s.tap(s)}else if(k==='b'){s.xray=!s.xray;try{localStorage.setItem('chalk:xray',s.xray?'1':'0')}catch(e){}sfx('blip')}else if(k==='start'){if(!s.trans&&s.i!==0)s.trans={from:s.i,to:0,t:.99,len:.3};sfx('blip')}}});
  return s}
const down=makeShaft('cv-fast','fa',DOWN,'down'),up=makeShaft('cv-slow','sl',UP,'up');
const seen=(s,id)=>!!(s&&s.seen.has(id));
Chalk.start({key:'time',missions:MISSION_DEFS,unitWhy:UNIT_WHY,checks:Object.assign({
  p1:()=>seen(down,'bird'),p1b:()=>seen(down,'cesium'),p1c:()=>seen(down,'planck'),p1d:()=>!!(down&&down.synced.size+(up?up.synced.size:0)>=3),p1e:()=>!!(down&&down.poked>0),
  p2:()=>seen(up,'tide'),p2b:()=>seen(up,'planet'),p2c:()=>seen(up,'ice'),p2d:()=>seen(up,'galaxy'),p2e:()=>!!(up&&up.synced.has('tide'))
},Object.fromEntries(Array.from({length:2},(_,i)=>[`tb${i+1}`,()=>Chalk.checkPassed(`ch${i+1}`)])))});
